//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPRequestOperationManager.h"

@interface AFHTTPRequestOperationManager (Promises)
- (id)promiseForNetworkOperation:(int)arg1 withURL:(id)arg2 andParameters:(id)arg3;
- (id)operationSequenceWithType:(int)arg1 urls:(id)arg2 parameters:(id)arg3;
- (id)HEADMultiple:(id)arg1 parameters:(id)arg2;
- (id)HEAD:(id)arg1 parameters:(id)arg2;
- (id)PATCHMultiple:(id)arg1 parameters:(id)arg2;
- (id)PATCH:(id)arg1 parameters:(id)arg2;
- (id)DELETEMultiple:(id)arg1 parameters:(id)arg2;
- (id)DELETE:(id)arg1 parameters:(id)arg2;
- (id)PUTMultiple:(id)arg1 parameters:(id)arg2;
- (id)PUT:(id)arg1 parameters:(id)arg2;
- (id)GETMultiple:(id)arg1 parameters:(id)arg2;
- (id)GET:(id)arg1 parameters:(id)arg2;
- (id)POST:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(CDUnknownBlockType)arg3;
- (id)POSTMultiple:(id)arg1 parameters:(id)arg2;
- (id)POST:(id)arg1 parameters:(id)arg2;
@end

