//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPRequestOperation.h"

@interface AFHTTPRequestOperation (Promises)
+ (id)request:(id)arg1 queue:(id)arg2;
+ (id)request:(id)arg1;
- (id)promiseByStartingImmediately:(_Bool)arg1;
- (id)promiseAndStartImmediately;
- (id)promise;
@end

