//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFURLConnectionOperation.h"

@interface AFURLConnectionOperation (_UIProgressView)

// Remaining properties
@property(nonatomic, setter=af_setDownloadProgressAnimated:) _Bool af_downloadProgressAnimated; // @dynamic af_downloadProgressAnimated;
@property(nonatomic, setter=af_setUploadProgressAnimated:) _Bool af_uploadProgressAnimated; // @dynamic af_uploadProgressAnimated;
@property(copy, nonatomic) CDUnknownBlockType downloadProgress; // @dynamic downloadProgress;
@property(copy, nonatomic) CDUnknownBlockType uploadProgress; // @dynamic uploadProgress;
@end

