//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface APAddressBook : NSObject
{
    unsigned long long _fieldsMask;
    CDUnknownBlockType _filterBlock;
    NSArray *_sortDescriptors;
    void *_addressBook;
    CDUnknownBlockType _changeCallback;
}

+ (void)requestAccessOnQueue:(struct dispatch_queue_s *)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)requestAccess:(CDUnknownBlockType)arg1;
+ (unsigned long long)access;
@property(copy, nonatomic) CDUnknownBlockType changeCallback; // @synthesize changeCallback=_changeCallback;
@property(readonly) void *addressBook; // @synthesize addressBook=_addressBook;
@property(retain, nonatomic) NSArray *sortDescriptors; // @synthesize sortDescriptors=_sortDescriptors;
@property(copy, nonatomic) CDUnknownBlockType filterBlock; // @synthesize filterBlock=_filterBlock;
@property(nonatomic) unsigned long long fieldsMask; // @synthesize fieldsMask=_fieldsMask;
- (void).cxx_destruct;
- (id)getContactByRecordID:(id)arg1;
- (void)stopObserveChanges;
- (void)startObserveChangesWithCallback:(CDUnknownBlockType)arg1;
- (void)loadContactsOnQueue:(struct dispatch_queue_s *)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadContacts:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

