//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface APPhoneWithLabel : NSObject
{
    NSString *_phone;
    NSString *_originalLabel;
    NSString *_localizedLabel;
}

@property(readonly, nonatomic) NSString *localizedLabel; // @synthesize localizedLabel=_localizedLabel;
@property(readonly, nonatomic) NSString *originalLabel; // @synthesize originalLabel=_originalLabel;
@property(readonly, nonatomic) NSString *phone; // @synthesize phone=_phone;
- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) NSString *label;
- (id)initWithPhone:(id)arg1 originalLabel:(id)arg2 localizedLabel:(id)arg3;

@end

