//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface APSocialProfile : NSObject
{
    unsigned long long _socialNetwork;
    NSString *_username;
    NSString *_userIdentifier;
    NSURL *_url;
}

@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *userIdentifier; // @synthesize userIdentifier=_userIdentifier;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(nonatomic) unsigned long long socialNetwork; // @synthesize socialNetwork=_socialNetwork;
- (void).cxx_destruct;
- (unsigned long long)socialNetworkTypeFromString:(id)arg1;
- (id)initWithSocialDictionary:(id)arg1;

@end

