//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "BMCellButtonPressDelegate.h"
#import "BMContactImporterDelegate.h"
#import "BMFindFriendViewDelegate.h"
#import "BMImportContactsTableViewCellDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BMContactImporter, BMFindFriendView, NSArray, NSString, UITableView;

@interface BMAddPeopleViewController : BMViewController <UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate, BMContactImporterDelegate, BMImportContactsTableViewCellDelegate, BMFindFriendViewDelegate, BMCellButtonPressDelegate>
{
    _Bool _shouldDisplayCloseButton;
    _Bool _shouldHaveFindFriendsTitle;
    BMFindFriendView *_findFriendView;
    BMContactImporter *_contactImporter;
    NSArray *_contactsArray;
    NSArray *_strangersArray;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSArray *strangersArray; // @synthesize strangersArray=_strangersArray;
@property(retain, nonatomic) NSArray *contactsArray; // @synthesize contactsArray=_contactsArray;
@property(retain, nonatomic) BMContactImporter *contactImporter; // @synthesize contactImporter=_contactImporter;
@property(retain, nonatomic) BMFindFriendView *findFriendView; // @synthesize findFriendView=_findFriendView;
@property(nonatomic) _Bool shouldHaveFindFriendsTitle; // @synthesize shouldHaveFindFriendsTitle=_shouldHaveFindFriendsTitle;
@property(nonatomic) _Bool shouldDisplayCloseButton; // @synthesize shouldDisplayCloseButton=_shouldDisplayCloseButton;
- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)userForIndexPath:(id)arg1;
- (void)contactImporter:(id)arg1 didCompleteWithPhoneNumbers:(id)arg2;
- (void)contactImporter:(id)arg1 failedWithAccessDeniedError:(id)arg2;
- (id)importContactsCell;
- (void)displayContactsImporting:(_Bool)arg1;
- (void)findFriendFollowButtonWasSelected:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)didPressReportButton:(id)arg1;
- (void)didPressFollowButton:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)importContactsButtonWasSelected:(id)arg1;
- (void)refreshStrangers;
- (void)defineLayout;
- (void)setupSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setup;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

