//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "BMMainViewPresenterDelegate.h"
#import "JSApplicationStateDelegate.h"

@class BMMainViewPresenter, NSString;

@interface BMAppDelegate : UIResponder <BMMainViewPresenterDelegate, JSApplicationStateDelegate>
{
    BMMainViewPresenter *_mainViewPresenter;
}

+ (void)load;
@property(retain, nonatomic) BMMainViewPresenter *mainViewPresenter; // @synthesize mainViewPresenter=_mainViewPresenter;
- (void).cxx_destruct;
- (void)captureSessionDidFinishNotification:(id)arg1;
- (void)mainViewPresenter:(id)arg1 didChangeMainViewController:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

