//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JSApplicationURLResourceOpeningDelegate.h"

@class NSString;

@interface BMAppURLResourceOpeningDelegate : NSObject <JSApplicationURLResourceOpeningDelegate>
{
}

+ (void)load;
- (void)setupBranchWithLaunchOptions:(id)arg1;
- (void)setupRoutes;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

