//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@protocol BMCaptureSessionProtocol <NSObject>
@property(nonatomic) __weak id <BMCaptureSessionDelegate> delegate;
@property(readonly, nonatomic, getter=isCapturing) _Bool capturing;
@property(readonly, nonatomic) _Bool cancelRequested;
- (_Bool)isReady;
- (void)cancelCaptureSession;
- (void)startCaptureSessionWithTimeRange:(CDStruct_e83c9415)arg1;
- (void)setupCaptureSessionForNewCapture;
- (id)initWithTargetDirectoryURL:(NSURL *)arg1;

@optional
- (_Bool)isAvailable;
@end

