//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

@class UIButton, UILabel, UIView;

@interface BMCaptureTutorialController : BMViewController
{
    UILabel *_topText;
    UILabel *_subText1;
    UILabel *_subText2;
    UILabel *_subText3;
    UIView *_containerView;
    UILabel *_bottomText;
    UIButton *_dismissButton;
}

@property(retain, nonatomic) UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) UILabel *bottomText; // @synthesize bottomText=_bottomText;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UILabel *subText3; // @synthesize subText3=_subText3;
@property(retain, nonatomic) UILabel *subText2; // @synthesize subText2=_subText2;
@property(retain, nonatomic) UILabel *subText1; // @synthesize subText1=_subText1;
@property(retain, nonatomic) UILabel *topText; // @synthesize topText=_topText;
- (void).cxx_destruct;
- (void)defineLayout;
- (void)setupSubview;
- (void)viewDidLoad;

@end

