//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMProximityControl.h"

@class GPUImageLuminosity, GPUImageVideoCamera, NSString;

@interface BMCameraProximityControl : NSObject <BMProximityControl>
{
    _Bool _enabled;
    _Bool _isFirst;
    id <BMProximityControlDelegate> _delegate;
    GPUImageVideoCamera *_frontVideoCamera;
    GPUImageLuminosity *_luminosityFilter;
    double _previousLuminosityValue;
    unsigned long long _sampleCounter;
    double _proximityThreshold;
}

@property(nonatomic) _Bool isFirst; // @synthesize isFirst=_isFirst;
@property(nonatomic) double proximityThreshold; // @synthesize proximityThreshold=_proximityThreshold;
@property(nonatomic) unsigned long long sampleCounter; // @synthesize sampleCounter=_sampleCounter;
@property(nonatomic) double previousLuminosityValue; // @synthesize previousLuminosityValue=_previousLuminosityValue;
@property(retain, nonatomic) GPUImageLuminosity *luminosityFilter; // @synthesize luminosityFilter=_luminosityFilter;
@property(retain, nonatomic) GPUImageVideoCamera *frontVideoCamera; // @synthesize frontVideoCamera=_frontVideoCamera;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <BMProximityControlDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)isEngaged;
- (void)reset;
- (void)disable;
- (void)enable;
- (void)updateWithLuminosity:(double)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

