//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMSystemSound;

@interface BMCaptureFeedbackController : NSObject
{
    double _duration;
    BMSystemSound *_startedSound;
    BMSystemSound *_finishedSound;
    BMSystemSound *_negativeSound;
}

@property(retain, nonatomic) BMSystemSound *negativeSound; // @synthesize negativeSound=_negativeSound;
@property(retain, nonatomic) BMSystemSound *finishedSound; // @synthesize finishedSound=_finishedSound;
@property(retain, nonatomic) BMSystemSound *startedSound; // @synthesize startedSound=_startedSound;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void).cxx_destruct;
- (void)stopVibrate;
- (void)playVibrate;
- (void)finishCaptureFeedback;
- (void)cancelCaptureFeedback;
- (void)startCaptureVibrateFeedbackWithDuration:(double)arg1;
- (void)startCaptureFeedbackWithCompletion:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

