//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

@class CAShapeLayer, NSTimer, UILabel;

@interface BMCaptureViewController : BMViewController
{
    CAShapeLayer *_circle;
    UILabel *_indicatorLabel;
    NSTimer *_recordingPulseTimer;
}

@property(retain, nonatomic) NSTimer *recordingPulseTimer; // @synthesize recordingPulseTimer=_recordingPulseTimer;
@property(retain, nonatomic) UILabel *indicatorLabel; // @synthesize indicatorLabel=_indicatorLabel;
@property(retain, nonatomic) CAShapeLayer *circle; // @synthesize circle=_circle;
- (void).cxx_destruct;
- (void)updateRecording;
- (void)resetRecordingTimer;
- (void)startRecordingTimer;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)circleDown;
- (void)circleUp:(_Bool)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)cancelAndDismiss;
- (void)proximityDidDisengage;
- (void)finishedCapture;
- (void)canceledCapture;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

