//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@protocol BMCaptureSessionDelegate <NSObject>
- (void)captureSessionDidCancel:(id <BMCaptureSessionProtocol>)arg1;
- (void)captureSessionDidFinishSaving:(id <BMCaptureSessionProtocol>)arg1 withVideoFileURL:(NSURL *)arg2;
- (void)captureSessionDidStart:(id <BMCaptureSessionProtocol>)arg1;

@optional
- (void)captureSessionUnavailable:(id <BMCaptureSessionProtocol>)arg1;
- (void)captureSessionAvailable:(id <BMCaptureSessionProtocol>)arg1;
- (void)captureSessionProgress:(id <BMCaptureSessionProtocol>)arg1 progress:(double)arg2;
- (void)captureSessionDidFinish:(id <BMCaptureSessionProtocol>)arg1;
@end

