//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CTCheckbox, UIButton, UILabel;

@interface BMCheckBoxPolicyView : UIView
{
    _Bool _checked;
    id <BMCheckBoxPolicyViewDelegate> _delegate;
    UIView *_containerView;
    UILabel *_label;
    CTCheckbox *_checkBox;
    UIButton *_button;
}

@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) CTCheckbox *checkBox; // @synthesize checkBox=_checkBox;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) _Bool checked; // @synthesize checked=_checked;
@property(nonatomic) __weak id <BMCheckBoxPolicyViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)init;

@end

