//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSNumber, NSString, NSURL;

@protocol BMClipProtocol <NSObject>
@property(copy, nonatomic) NSString *localIdentifier;
@property(copy, nonatomic) NSNumber *userIdentifier;
@property(copy, nonatomic) NSDate *uploadURLExpirey;
@property(copy, nonatomic) NSString *uploadURL;
@property(copy, nonatomic) NSString *uploadToken;
@property(nonatomic) unsigned long long state;
@property(copy, nonatomic) NSDate *postedAt;
@property(readonly, copy, nonatomic) NSNumber *longitude;
@property(readonly, copy, nonatomic) NSNumber *latitude;
@property(copy, nonatomic) NSURL *remoteURL;
@property(copy, nonatomic) NSString *localFilename;
@property(copy, nonatomic) NSDate *recordedAt;
@property(copy, nonatomic) NSString *identifier;
@end

