//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMClipProtocol.h"

@class NSDate, NSNumber, NSString, NSURL;

@interface BMClipProtocol_ProtocolMethodContainer : NSObject <BMClipProtocol>
{
}

+ (void)load;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSString *identifier;
@property(readonly, copy, nonatomic) NSNumber *latitude;
@property(copy, nonatomic) NSString *localFilename;
@property(copy, nonatomic) NSString *localIdentifier;
@property(readonly, copy, nonatomic) NSNumber *longitude;
@property(copy, nonatomic) NSDate *postedAt;
@property(copy, nonatomic) NSDate *recordedAt;
@property(copy, nonatomic) NSURL *remoteURL;
@property(nonatomic) unsigned long long state;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *uploadToken;
@property(copy, nonatomic) NSString *uploadURL;
@property(copy, nonatomic) NSDate *uploadURLExpirey;
@property(copy, nonatomic) NSNumber *userIdentifier;

@end

