//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@interface BMClipOperation : NSOperation
{
    id <BMClipProtocol> _clip;
    unsigned long long _exitState;
    CDUnknownBlockType _didStartBlock;
    CDUnknownBlockType _successFailureBlock;
}

+ (id)name;
@property(copy, nonatomic) CDUnknownBlockType successFailureBlock; // @synthesize successFailureBlock=_successFailureBlock;
@property(copy, nonatomic) CDUnknownBlockType didStartBlock; // @synthesize didStartBlock=_didStartBlock;
@property(nonatomic) unsigned long long exitState; // @synthesize exitState=_exitState;
@property(copy, nonatomic) id <BMClipProtocol> clip; // @synthesize clip=_clip;
- (void).cxx_destruct;
- (void)performOperation;
- (void)main;
- (id)initWithClip:(id)arg1 didStartBlock:(CDUnknownBlockType)arg2;
- (id)initWithDidStartBlock:(CDUnknownBlockType)arg1;
- (id)initWithClip:(id)arg1;
- (id)init;

@end

