//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class APAddressBook, NBPhoneNumberUtil, NSArray, NSMutableArray, NSOperationQueue;

@interface BMContactImporter : NSObject
{
    _Bool _loading;
    id <BMContactImporterDelegate> _delegate;
    APAddressBook *_addressBook;
    NSArray *_contacts;
    NSOperationQueue *_operationQueue;
    NSMutableArray *_phoneNumbers;
    NBPhoneNumberUtil *_phoneNumberUtil;
}

@property(retain, nonatomic) NBPhoneNumberUtil *phoneNumberUtil; // @synthesize phoneNumberUtil=_phoneNumberUtil;
@property(retain) NSMutableArray *phoneNumbers; // @synthesize phoneNumbers=_phoneNumbers;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(copy, nonatomic) NSArray *contacts; // @synthesize contacts=_contacts;
@property(retain, nonatomic) APAddressBook *addressBook; // @synthesize addressBook=_addressBook;
@property(getter=isLoading) _Bool loading; // @synthesize loading=_loading;
@property(nonatomic) __weak id <BMContactImporterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)normalizationOfContactsComplete;
- (void)normalizeContactPhoneNumbers:(id)arg1;
- (void)normalizeAllContacts;
- (void)loadContacts;
- (void)reset;
- (void)cancel;
- (void)start;
- (id)init;

@end

