//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableDictionary, NSNumber, NSString;

@interface BMCurrentUser : NSObject
{
    _Bool _active;
    _Bool _rejectAnonymousReactions;
    _Bool _allowSearchBySMS;
    NSString *_authTierString;
    NSNumber *_beenSeconds;
    NSNumber *_beenUsers;
    NSString *_userName;
    NSNumber *_identifier;
    NSNumber *_followerCount;
    NSNumber *_followingCount;
    unsigned long long _reactionCount;
    unsigned long long _watchedStacks;
    NSString *_smsChallengeRequest;
    NSString *_pendingUsername;
    NSMutableDictionary *_following;
}

+ (id)keyPathsForValuesAffectingIsReserved;
+ (id)keyPathsForValuesAffectingIsAuthenticated;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *following; // @synthesize following=_following;
@property(copy, nonatomic) NSString *pendingUsername; // @synthesize pendingUsername=_pendingUsername;
@property(copy, nonatomic) NSString *smsChallengeRequest; // @synthesize smsChallengeRequest=_smsChallengeRequest;
@property(nonatomic) unsigned long long watchedStacks; // @synthesize watchedStacks=_watchedStacks;
@property(nonatomic) _Bool allowSearchBySMS; // @synthesize allowSearchBySMS=_allowSearchBySMS;
@property(nonatomic) _Bool rejectAnonymousReactions; // @synthesize rejectAnonymousReactions=_rejectAnonymousReactions;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) unsigned long long reactionCount; // @synthesize reactionCount=_reactionCount;
@property(copy, nonatomic) NSNumber *followingCount; // @synthesize followingCount=_followingCount;
@property(copy, nonatomic) NSNumber *followerCount; // @synthesize followerCount=_followerCount;
@property(copy, nonatomic) NSNumber *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSNumber *beenUsers; // @synthesize beenUsers=_beenUsers;
@property(copy, nonatomic) NSNumber *beenSeconds; // @synthesize beenSeconds=_beenSeconds;
@property(copy, nonatomic) NSString *authTierString; // @synthesize authTierString=_authTierString;
- (void).cxx_destruct;
@property(nonatomic) _Bool skipOnboardingCards;
@property(nonatomic) _Bool skipPushNag;
@property(nonatomic) _Bool skipSMSNag;
@property(nonatomic) _Bool skipCaptureTutorial;
@property(nonatomic) NSDate *endDate;
@property(nonatomic) _Bool skipFollowNag;
@property(nonatomic) _Bool skipHoldToPlayNag;
- (_Bool)authIsNamed;
@property(readonly, nonatomic, getter=isReserved) _Bool reserved; // @dynamic reserved;
- (void)setApiSecret:(id)arg1;
- (id)apiSecret;
- (void)setApiKey:(id)arg1;
- (id)apiKey;
@property(readonly, nonatomic, getter=isAuthenticated) _Bool authenticated; // @dynamic authenticated;
- (id)applyAccessCode:(id)arg1;
- (id)validateAccessCode:(id)arg1;
- (id)reserveUserName:(id)arg1;
- (id)applySMSValidationCode:(id)arg1;
- (id)verifyWithNumber:(id)arg1;
- (id)verifyWithUserName:(id)arg1 mobileNumber:(id)arg2;
- (id)signInWithValidationCode:(id)arg1;
- (void)clearUser;
- (id)authenticate;
- (_Bool)isCurrentUser:(id)arg1;
- (void)migrateDataIfNeeded;
- (void)updateFollowingForUserIdentifier:(id)arg1 following:(_Bool)arg2 at:(id)arg3;
- (_Bool)isFollowingUserWithIdentifier:(id)arg1;
- (_Bool)isFollowingUser:(id)arg1;
- (void)updateSearchBySMSSetting:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)updateAnonymousReactionsSetting:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)updateWithLatestInfo:(id)arg1;
- (void)observeDefaultsKeyPath:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) _Bool isAuthenticated;
@property(readonly, nonatomic) _Bool isReserved;

@end

