//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "BMCurrentUserInfoHeaderCellDelegate.h"
#import "BMCurrentUserInfoProfileImageGestureView.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BMCurrentUserInfoProfileImageGestureView, BMSnakeProgressView, NSArray, NSString, UIImageView, UITableView;

@interface BMCurrentUserInfoViewController : BMViewController <UITableViewDelegate, UITableViewDataSource, BMCurrentUserInfoHeaderCellDelegate, BMCurrentUserInfoProfileImageGestureView>
{
    _Bool _displayLoadingProfileImage;
    UIImageView *_backgroundImageView;
    UITableView *_tableView;
    NSArray *_dataSource;
    BMSnakeProgressView *_profileImageDownloadProgressView;
    BMCurrentUserInfoProfileImageGestureView *_profileImageGestureView;
}

@property(retain, nonatomic) BMCurrentUserInfoProfileImageGestureView *profileImageGestureView; // @synthesize profileImageGestureView=_profileImageGestureView;
@property(nonatomic) _Bool displayLoadingProfileImage; // @synthesize displayLoadingProfileImage=_displayLoadingProfileImage;
@property(retain, nonatomic) BMSnakeProgressView *profileImageDownloadProgressView; // @synthesize profileImageDownloadProgressView=_profileImageDownloadProgressView;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
- (void).cxx_destruct;
- (id)standardCellAtIndexPath:(id)arg1;
- (id)headerCellAtIndexPath:(id)arg1;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveMenuItemWasSelected:(id)arg1;
- (void)shareLinkWasSelected;
- (void)shareLinkButtonWasSelected:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)updateProfileImageURL:(id)arg1;
- (void)displaySettings;
- (void)displayFollowers;
- (void)displayFollowing;
- (void)displayFindFriends;
- (void)updateBackgroundImageLayoutConstraintsWithContentOffsetY:(double)arg1;
- (void)defineLayout;
- (void)setupSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

