//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UILabel, UIView;

@interface BMCurrentUserInfoHeaderCell : UITableViewCell
{
    id <BMCurrentUserInfoHeaderCellDelegate> _delegate;
    UIButton *_shareLinkButton;
    UIView *_labelContainerView;
    UILabel *_headerLabel;
}

+ (double)height;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(retain, nonatomic) UIView *labelContainerView; // @synthesize labelContainerView=_labelContainerView;
@property(retain, nonatomic) UIButton *shareLinkButton; // @synthesize shareLinkButton=_shareLinkButton;
@property(nonatomic) __weak id <BMCurrentUserInfoHeaderCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)shareLinkButtonWasSelected:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

