//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSDate, NSTimer, UILabel;

@interface BMDateCounter : UIView
{
    NSArray *_seperators;
    NSArray *_dateLabels;
    _Bool _blinkToggle;
    NSTimer *_clockTimer;
    NSDate *_targetDate;
    UILabel *_dayLabel;
    UILabel *_sep1Label;
    UILabel *_hourLabel;
    UILabel *_sep2Label;
    UILabel *_minLabel;
    UILabel *_sep3Label;
    UILabel *_secLabel;
}

@property(retain, nonatomic) UILabel *secLabel; // @synthesize secLabel=_secLabel;
@property(retain, nonatomic) UILabel *sep3Label; // @synthesize sep3Label=_sep3Label;
@property(retain, nonatomic) UILabel *minLabel; // @synthesize minLabel=_minLabel;
@property(retain, nonatomic) UILabel *sep2Label; // @synthesize sep2Label=_sep2Label;
@property(retain, nonatomic) UILabel *hourLabel; // @synthesize hourLabel=_hourLabel;
@property(retain, nonatomic) UILabel *sep1Label; // @synthesize sep1Label=_sep1Label;
@property(retain, nonatomic) UILabel *dayLabel; // @synthesize dayLabel=_dayLabel;
@property(retain, nonatomic) NSDate *targetDate; // @synthesize targetDate=_targetDate;
@property _Bool blinkToggle; // @synthesize blinkToggle=_blinkToggle;
@property(retain, nonatomic) NSTimer *clockTimer; // @synthesize clockTimer=_clockTimer;
- (void).cxx_destruct;
- (double)getDateDifference;
- (void)updateDate;
- (void)updateClock;
- (void)setSeperatorsHidden:(_Bool)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)removeFromSuperview;
- (void)setup;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

