//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMUserDefaultDB.h"

@interface BMDockDB : BMUserDefaultDB
{
}

+ (id)sharedInstance;
- (void)cleanupDatabaseAndVideoFiles:(CDUnknownBlockType)arg1;
- (void)purge;
- (id)retrieveAll;
- (void)delete:(id)arg1;
- (void)update:(id)arg1;
- (void)add:(id)arg1;
- (void)performRetrievalSorting:(id)arg1;
- (id)init;

@end

