//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue, PMKPromise;

@interface BMDockManager : NSObject
{
    NSOperationQueue *_processingQueue;
    PMKPromise *_currentOperation;
}

+ (id)performOperation:(id)arg1;
+ (id)sharedInstance;
@property(retain) PMKPromise *currentOperation; // @synthesize currentOperation=_currentOperation;
@property(retain, nonatomic) NSOperationQueue *processingQueue; // @synthesize processingQueue=_processingQueue;
- (void).cxx_destruct;
- (void)dealloc;
- (void)monitorReachabilityChanges;
- (id)notificationUserInfoForClip:(id)arg1;
- (void)postDidCompleteNotificationForOperation:(id)arg1 withClip:(id)arg2 error:(id)arg3;
- (void)postDidStartNotificationForOperation:(id)arg1 withClip:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)clipNoLongerProcessing;
- (void)processClip:(id)arg1;
- (void)announceProcessingComplete;
- (void)announceProcessing;
- (void)processRemainingClips;
- (_Bool)isProcessing;
- (int)publishClip:(id)arg1;
- (void)activate;
- (id)init;

@end

