//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "UITextFieldDelegate.h"

@class MASConstraint, NSString, NSTimer, UIActivityIndicatorView, UILabel, UITextField, UIView;

@interface BMEarlyAccessViewController : BMViewController <UITextFieldDelegate>
{
    id <BMEarlyAccessViewControllerDelegate> _delegate;
    UIView *_containerView;
    UIView *_topView;
    UIView *_bottomView;
    MASConstraint *_containerBottomConstraint;
    UIActivityIndicatorView *_loadingIndicator;
    UILabel *_topLabel;
    UIView *_accessCodeContainerView;
    UIView *_usernameContainerView;
    UITextField *_accessCodeTextField;
    UITextField *_usernameTextField;
    NSString *_incomingCode;
    NSTimer *_autoTyper;
    UIView *_bottomPolicyView;
    UIView *_bottomPolicyViewContainer;
}

@property(retain, nonatomic) UIView *bottomPolicyViewContainer; // @synthesize bottomPolicyViewContainer=_bottomPolicyViewContainer;
@property(retain, nonatomic) UIView *bottomPolicyView; // @synthesize bottomPolicyView=_bottomPolicyView;
@property(retain, nonatomic) NSTimer *autoTyper; // @synthesize autoTyper=_autoTyper;
@property(retain, nonatomic) NSString *incomingCode; // @synthesize incomingCode=_incomingCode;
@property(retain, nonatomic) UITextField *usernameTextField; // @synthesize usernameTextField=_usernameTextField;
@property(retain, nonatomic) UITextField *accessCodeTextField; // @synthesize accessCodeTextField=_accessCodeTextField;
@property(retain, nonatomic) UIView *usernameContainerView; // @synthesize usernameContainerView=_usernameContainerView;
@property(retain, nonatomic) UIView *accessCodeContainerView; // @synthesize accessCodeContainerView=_accessCodeContainerView;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) MASConstraint *containerBottomConstraint; // @synthesize containerBottomConstraint=_containerBottomConstraint;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <BMEarlyAccessViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)hideUsernameField;
- (void)showUsernameField;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidChange;
- (void)accessCodeApplicationSuccessful;
- (void)applyCodeForValidUser;
- (void)applyCodeAndUsername;
- (void)accessCodeValidated;
- (void)validateAccessCode;
- (void)resetUsername;
- (void)resetAccessCode;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)updateAccessCodeInput;
- (void)animateCodeInput;
- (void)defineLayout;
- (void)setupSubview;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithIncomingCode:(id)arg1 delegate:(id)arg2;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

