//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BMFeedStatsViewModel, NSTimer, UIButton, UILabel;

@interface BMFeedStatsView : UIView
{
    BMFeedStatsViewModel *_model;
    id <BMFeedStatsViewDelegate> _delegate;
    UIView *_containerView;
    UIView *_leftContainerView;
    UIView *_rightContainerView;
    UIButton *_reactionsButton;
    UIButton *_unlockButton;
    NSTimer *_publishingPulseTimer;
    UILabel *_publishingStatusLabel;
    UIButton *_settingsButton;
    UILabel *_statsLabel;
    UIButton *_userNameButton;
}

@property(retain, nonatomic) UIButton *userNameButton; // @synthesize userNameButton=_userNameButton;
@property(retain, nonatomic) UILabel *statsLabel; // @synthesize statsLabel=_statsLabel;
@property(retain, nonatomic) UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UILabel *publishingStatusLabel; // @synthesize publishingStatusLabel=_publishingStatusLabel;
@property(retain, nonatomic) NSTimer *publishingPulseTimer; // @synthesize publishingPulseTimer=_publishingPulseTimer;
@property(retain, nonatomic) UIButton *unlockButton; // @synthesize unlockButton=_unlockButton;
@property(retain, nonatomic) UIButton *reactionsButton; // @synthesize reactionsButton=_reactionsButton;
@property(retain, nonatomic) UIView *rightContainerView; // @synthesize rightContainerView=_rightContainerView;
@property(retain, nonatomic) UIView *leftContainerView; // @synthesize leftContainerView=_leftContainerView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <BMFeedStatsViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) BMFeedStatsViewModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)unlockButtonWasSelected:(id)arg1;
- (void)settingsButtonWasSelected:(id)arg1;
- (void)reactionsButtonWasSelected:(id)arg1;
- (void)updatePosting;
- (void)resetPostingTimer;
- (void)startPostingTimer;
- (void)displayPosting;
- (void)displayUserName;
- (void)layoutSubviews;
- (void)update;
- (void)setup;
- (void)dealloc;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

