//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface BMFeedStatsViewModel : NSObject
{
    _Bool _active;
    _Bool _authenticated;
    _Bool _reservedUser;
    NSNumber *_beenSeconds;
    NSNumber *_beenUsers;
    NSString *_userName;
    unsigned long long _reactionsCount;
}

+ (id)timeStringFromTimeInterval:(double)arg1;
+ (id)attributedStringForUpdatedStatsWithNumberOfPeople:(id)arg1 timeInSeconds:(id)arg2;
@property(nonatomic) _Bool reservedUser; // @synthesize reservedUser=_reservedUser;
@property(nonatomic) _Bool authenticated; // @synthesize authenticated=_authenticated;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(nonatomic) unsigned long long reactionsCount; // @synthesize reactionsCount=_reactionsCount;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSNumber *beenUsers; // @synthesize beenUsers=_beenUsers;
@property(copy, nonatomic) NSNumber *beenSeconds; // @synthesize beenSeconds=_beenSeconds;
- (void).cxx_destruct;
- (id)reactionsString;
- (id)init;

@end

