//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@class UIButton, UIImageView, UILabel;

@interface BMFeedFooterView : UITableViewHeaderFooterView
{
    _Bool _showAddMoreButton;
    id <BMFeedFooterViewDelegate> _delegate;
    UIImageView *_arrowView;
    UILabel *_descriptionLabel;
    UILabel *_friendsLabel;
    UIButton *_friendsButton;
}

+ (double)getFooterHeightForTableView:(id)arg1;
@property(retain, nonatomic) UIButton *friendsButton; // @synthesize friendsButton=_friendsButton;
@property(retain, nonatomic) UILabel *friendsLabel; // @synthesize friendsLabel=_friendsLabel;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(nonatomic) _Bool showAddMoreButton; // @synthesize showAddMoreButton=_showAddMoreButton;
@property(nonatomic) __weak id <BMFeedFooterViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)friendsLabelString;
- (void)friendButtonPressed:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

