//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "BMFeedFooterViewDelegate.h"
#import "BMPermissionRequestDelegate.h"
#import "BMPlayerViewControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDelegate.h"

@class BMFeedCell, BMFeedDataSourceController, BMStackModel, NSDate, NSDictionary, NSIndexPath, NSString, NSTimer, UITableView, UIView;

@interface BMFeedViewController : BMViewController <UITableViewDelegate, BMPlayerViewControllerDelegate, BMFeedFooterViewDelegate, BMPermissionRequestDelegate, UIGestureRecognizerDelegate>
{
    id <BMFeedViewControllerDelegate> _delegate;
    UITableView *_tableView;
    BMFeedCell *_lastTouchedCell;
    UIView *_footerView;
    BMFeedDataSourceController *_feedDataSourceController;
    BMStackModel *_currentPlayingStack;
    NSIndexPath *_currentPlayingIndexPath;
    NSTimer *_touchTimer;
    NSDate *_touchTimerStartTime;
    unsigned long long _watchedStacks;
    NSDictionary *_lastResponseCursor;
}

@property(retain, nonatomic) NSDictionary *lastResponseCursor; // @synthesize lastResponseCursor=_lastResponseCursor;
@property(nonatomic) unsigned long long watchedStacks; // @synthesize watchedStacks=_watchedStacks;
@property(retain, nonatomic) NSDate *touchTimerStartTime; // @synthesize touchTimerStartTime=_touchTimerStartTime;
@property(retain, nonatomic) NSTimer *touchTimer; // @synthesize touchTimer=_touchTimer;
@property(retain, nonatomic) NSIndexPath *currentPlayingIndexPath; // @synthesize currentPlayingIndexPath=_currentPlayingIndexPath;
@property(retain, nonatomic) BMStackModel *currentPlayingStack; // @synthesize currentPlayingStack=_currentPlayingStack;
@property(retain, nonatomic) BMFeedDataSourceController *feedDataSourceController; // @synthesize feedDataSourceController=_feedDataSourceController;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(nonatomic) __weak BMFeedCell *lastTouchedCell; // @synthesize lastTouchedCell=_lastTouchedCell;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <BMFeedViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clearDataAndPerformVisibleRefresh;
- (void)didSelectBlock:(id)arg1;
- (void)didSelectReport:(id)arg1;
- (void)touchingEndedWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)touchingBeganWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)removeNotifications;
- (void)addNotifications;
- (void)playerViewControllerPlaybackDidEndWithReportRequest:(id)arg1;
- (void)playerViewControllerPlaybackFailed:(id)arg1;
- (void)playerViewControllerPlaybackDidEnd:(id)arg1;
- (void)showTutorial;
- (void)dismissNaggingCells;
- (void)dismissedPlayerCompletionWithTimeWatched:(double)arg1;
- (void)dismissPlayerViewController:(id)arg1;
- (void)playVideoFromCellAtIndexPath:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)feedFooterFindFriendsButtonWasSelected:(id)arg1;
- (void)determineIfFooterEnabled;
- (void)didRefreshWithResults:(id)arg1;
- (void)loadDataFromStart:(CDUnknownBlockType)arg1;
- (void)loadDataFrom:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)loadAdditionalDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)insertRowAtBottom;
- (void)insertRowAtTop;
- (_Bool)automaticallyAdjustsScrollViewInsets;
- (void)defineLayout;
- (void)setupSubviews;
- (void)handleLongPress:(id)arg1;
- (void)handleTap:(id)arg1;
- (void)setupTableView;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)notifyPermissionOfType:(int)arg1 isEnabled:(_Bool)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

