//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "BMTableViewCellProtocol.h"

@class BMFollowStyleButton, BMHoldToWatchView, BMStyleButton, NSString, UIColor, UILabel, UIView;

@interface BMFeedCell : UITableViewCell <BMTableViewCellProtocol>
{
    _Bool _finishedSelectionAnimation;
    unsigned long long _cellType;
    id <BMCellButtonPressDelegate> _delegate;
    UIColor *_cellBackgroundColor;
    UILabel *_createdAtLabel;
    UILabel *_displayNameLabel;
    BMFollowStyleButton *_followButton;
    BMStyleButton *_gotItButton;
    BMHoldToWatchView *_holdToWatchView;
    UIView *_lineView;
    UILabel *_locationLabel;
    UILabel *_nagLabel;
    UILabel *_recommendedLabel;
    UIView *_rightBorderView;
    UIView *_pressAnimationView;
}

+ (id)attributedStringPairs:(id)arg1;
+ (id)holdToWatchAttributedString;
+ (id)attributedStringWithName:(id)arg1;
+ (id)labelStringFormatForStackCreatedDate:(id)arg1;
@property(nonatomic) _Bool finishedSelectionAnimation; // @synthesize finishedSelectionAnimation=_finishedSelectionAnimation;
@property(retain, nonatomic) UIView *pressAnimationView; // @synthesize pressAnimationView=_pressAnimationView;
@property(retain, nonatomic) UIView *rightBorderView; // @synthesize rightBorderView=_rightBorderView;
@property(retain, nonatomic) UILabel *recommendedLabel; // @synthesize recommendedLabel=_recommendedLabel;
@property(retain, nonatomic) UILabel *nagLabel; // @synthesize nagLabel=_nagLabel;
@property(retain, nonatomic) UILabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) BMHoldToWatchView *holdToWatchView; // @synthesize holdToWatchView=_holdToWatchView;
@property(retain, nonatomic) BMStyleButton *gotItButton; // @synthesize gotItButton=_gotItButton;
@property(retain, nonatomic) BMFollowStyleButton *followButton; // @synthesize followButton=_followButton;
@property(retain, nonatomic) UILabel *displayNameLabel; // @synthesize displayNameLabel=_displayNameLabel;
@property(retain, nonatomic) UILabel *createdAtLabel; // @synthesize createdAtLabel=_createdAtLabel;
@property(retain, nonatomic) UIColor *cellBackgroundColor; // @synthesize cellBackgroundColor=_cellBackgroundColor;
@property(nonatomic) __weak id <BMCellButtonPressDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long cellType; // @synthesize cellType=_cellType;
- (void).cxx_destruct;
- (void)flashHoldAnimation;
- (void)invalidateHoldAnimation;
- (_Bool)isCellSelectable;
- (void)gotItButtonTapped:(id)arg1;
- (void)followButtonTapped:(id)arg1;
- (void)setupWithDataObject:(id)arg1;
- (void)prepareForReuse;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)unPress:(_Bool)arg1;
- (void)press:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setup;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

