//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMUserListViewController.h"

#import "BMContactImporterDelegate.h"
#import "BMFindFriendViewDelegate.h"

@class BMContactImporter, BMFindFriendView, NSString, UIActivityIndicatorView, UIButton, UILabel;

@interface BMFindFriendsViewController : BMUserListViewController <BMFindFriendViewDelegate, BMContactImporterDelegate>
{
    BMFindFriendView *_findFriendView;
    BMContactImporter *_contactImporter;
    UILabel *_tableLabel;
    UIButton *_addContactsButton;
    UIActivityIndicatorView *_importingContactsIndicator;
}

@property(retain, nonatomic) UIActivityIndicatorView *importingContactsIndicator; // @synthesize importingContactsIndicator=_importingContactsIndicator;
@property(retain, nonatomic) UIButton *addContactsButton; // @synthesize addContactsButton=_addContactsButton;
@property(retain, nonatomic) UILabel *tableLabel; // @synthesize tableLabel=_tableLabel;
@property(retain, nonatomic) BMContactImporter *contactImporter; // @synthesize contactImporter=_contactImporter;
@property(retain, nonatomic) BMFindFriendView *findFriendView; // @synthesize findFriendView=_findFriendView;
- (void).cxx_destruct;
- (void)contactImporter:(id)arg1 didCompleteWithPhoneNumbers:(id)arg2;
- (void)contactImporter:(id)arg1 failedWithAccessDeniedError:(id)arg2;
- (void)displayContactsImporting:(_Bool)arg1;
- (void)addContactsButtonPressed;
- (void)findFriendFollowButtonWasSelected:(id)arg1;
- (void)setupTableview;
- (void)defineLayout;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

