//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CABasicAnimation, CAShapeLayer, NSString, NSTimer, UIButton;

@interface BMGoProView : UIView
{
    CABasicAnimation *_pulseAnimation;
    int _connectionLostCount;
    id <BMGoProViewDelegate> _delegate;
    UIView *_containerView;
    UIButton *_captureButton;
    UIView *_progressView;
    UIView *_lineView;
    NSTimer *_ellipsisPulseTimer;
    NSTimer *_connectionLostTimer;
    NSString *_buttonTextCache;
    CAShapeLayer *_lineLayer;
}

@property(retain, nonatomic) CAShapeLayer *lineLayer; // @synthesize lineLayer=_lineLayer;
@property(retain, nonatomic) NSString *buttonTextCache; // @synthesize buttonTextCache=_buttonTextCache;
@property(retain, nonatomic) NSTimer *connectionLostTimer; // @synthesize connectionLostTimer=_connectionLostTimer;
@property(retain, nonatomic) NSTimer *ellipsisPulseTimer; // @synthesize ellipsisPulseTimer=_ellipsisPulseTimer;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIButton *captureButton; // @synthesize captureButton=_captureButton;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <BMGoProViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateEllipsis;
- (void)resetEllipsisTimer;
- (void)startEllipsisTimer;
- (void)updateConnectionLostTimer;
- (void)resetConnectionLostTimer;
- (void)startConnectionLostTimer;
- (void)capturePressed:(id)arg1;
- (void)stopPulseButton;
- (void)startPulseButton;
- (void)updateGoProStatus:(id)arg1;
- (void)setProgressLine:(double)arg1;
- (void)updateProgress:(id)arg1;
- (void)createProgressLine;
- (void)layoutSubviews;
- (void)setup;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

