//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OVCHTTPSessionManager.h"

@interface BMGoProClient : OVCHTTPSessionManager
{
}

+ (void)performRequest:(id)arg1 withRetry:(int)arg2 withRetryDelay:(int)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
+ (id)createGoProRequest:(id)arg1 params:(id)arg2;
+ (id)URLStringFromMediaListRaw:(id)arg1;
+ (id)getDestinationURLforFile:(id)arg1 fromFolder:(id)arg2;
+ (id)modelClassesByResourcePath;
+ (id)sharedInstance;
- (id)performRequest:(id)arg1 withRetry:(int)arg2 withRetryDelay:(int)arg3;
- (id)deleteFile:(id)arg1;
- (id)deleteFile:(id)arg1 from:(id)arg2;
- (void)downloadClip:(id)arg1 inBackgroundTo:(id)arg2;
- (id)downloadFileTo:(id)arg1 from:(id)arg2;
- (id)getMediaListRaw;
- (id)stopRecord;
- (id)startRecord;
- (id)setMediumFOV;
- (id)set720Mode;
- (id)setVideoMode;
- (id)setReady;
- (id)sendKeepAlive;
- (id)init;

@end

