//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPSessionManager.h"

@interface BMGoProBackgroundSessionManager : AFHTTPSessionManager
{
    CDUnknownBlockType _savedCompletionHandler;
}

+ (id)sharedManager;
@property(copy, nonatomic) CDUnknownBlockType savedCompletionHandler; // @synthesize savedCompletionHandler=_savedCompletionHandler;
- (void).cxx_destruct;
- (void)configureBackgroundSessionFinished;
- (void)configureProgressUpdates;
- (void)configureDownloadFinished;
- (id)init;

@end

