//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

@class BMGoProMediaModel;

@interface BMGoProResponseModel : MTLModel
{
    BMGoProMediaModel *_media;
}

+ (id)mediaJSONTransformer;
@property(readonly, nonatomic) BMGoProMediaModel *media; // @synthesize media=_media;
- (void).cxx_destruct;

@end

