//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMCaptureSessionProtocol.h"

@class BMGoProClient, NSString, NSTimer, NSURL;

@interface BMGoProManager : NSObject <BMCaptureSessionProtocol>
{
    _Bool _capturing;
    id <BMCaptureSessionDelegate> _delegate;
    long long _currentState;
    NSTimer *_keepAliveTimer;
    BMGoProClient *_goProClient;
    NSURL *_targetDirectoryURL;
    unsigned long long _clipsDownloading;
    CDStruct_e83c9415 _recordingTimeRange;
}

+ (void)receivedError:(id)arg1 forFile:(id)arg2 from:(id)arg3;
+ (void)receivedFile:(id)arg1 from:(id)arg2;
+ (id)sharedInstance;
@property unsigned long long clipsDownloading; // @synthesize clipsDownloading=_clipsDownloading;
@property(retain, nonatomic) NSURL *targetDirectoryURL; // @synthesize targetDirectoryURL=_targetDirectoryURL;
@property(nonatomic) CDStruct_e83c9415 recordingTimeRange; // @synthesize recordingTimeRange=_recordingTimeRange;
@property(retain, nonatomic) BMGoProClient *goProClient; // @synthesize goProClient=_goProClient;
@property(retain) NSTimer *keepAliveTimer; // @synthesize keepAliveTimer=_keepAliveTimer;
@property(nonatomic) long long currentState; // @synthesize currentState=_currentState;
@property(nonatomic) __weak id <BMCaptureSessionDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic, getter=isCapturing) _Bool capturing; // @synthesize capturing=_capturing;
- (void).cxx_destruct;
- (void)cancelCaptureSession;
- (void)startCaptureSessionWithTimeRange:(CDStruct_e83c9415)arg1;
- (_Bool)isReady;
- (void)setupCaptureSessionForNewCapture;
- (id)initWithTargetDirectoryURL:(id)arg1;
- (void)postFinishedSavingNotificationWitClip:(id)arg1;
- (void)postFinishedRecordingNotification;
- (void)postStartNotification;
- (void)postNotAvailableNotification;
- (void)postAvailableNotification;
- (void)handleError:(id)arg1;
- (void)downloadClip:(id)arg1;
- (void)getRemoteFiles;
@property(readonly, nonatomic) _Bool cancelRequested;
- (_Bool)isProcessing;
- (void)saveClipForDownload;
- (void)delayedDownloadClip;
- (void)startRecording;
- (void)performCapture;
- (void)keepAlive:(id)arg1;
- (_Bool)capture;
- (void)requestStateBroadcast;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

