//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface BMHoldToWatchView : UIView
{
    _Bool _animating;
    UIView *_holdToWatchLabel;
}

@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(retain, nonatomic) UIView *holdToWatchLabel; // @synthesize holdToWatchLabel=_holdToWatchLabel;
- (void).cxx_destruct;
- (void)invalidateHoldAnimation;
- (void)flashHoldAnimation;
- (void)holdToWatchFadeIn:(CDUnknownBlockType)arg1;
- (void)holdToWatchFadeout:(CDUnknownBlockType)arg1;
- (void)layoutSubviews;
- (void)setup;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

