//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFJSONRequestSerializer.h"

@class NSData, NSNumber, NSString;

@interface BMHTTPRequestSerializer : AFJSONRequestSerializer
{
    NSString *_buildDate;
    NSNumber *_userIdentifier;
    NSString *_accessKey;
    NSData *_secret;
}

@property(copy, nonatomic) NSData *secret; // @synthesize secret=_secret;
@property(copy, nonatomic) NSString *accessKey; // @synthesize accessKey=_accessKey;
@property(copy, nonatomic) NSNumber *userIdentifier; // @synthesize userIdentifier=_userIdentifier;
@property(copy, nonatomic) NSString *buildDate; // @synthesize buildDate=_buildDate;
- (void).cxx_destruct;
- (id)requestWithMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 error:(id *)arg4;
- (id)requestBySettingAuthorizationHeadersForRequest:(id)arg1 error:(id *)arg2;
- (void)setAccessKeyID:(id)arg1 secret:(id)arg2;
- (id)init;

@end

