//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing.h"

@class BMUserModel, NSDate, NSNumber, NSString, NSURL;

@interface BMInviteModel : MTLModel <MTLJSONSerializing>
{
    NSString *_code;
    NSURL *_codeURL;
    NSDate *_createdAt;
    NSNumber *_usesRemaining;
    BMUserModel *_createdByUser;
}

+ (id)inviteJSONTransformer;
+ (id)createdByUserJSONTransformer;
+ (id)createdAtJSONTransformer;
+ (id)codeURLJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(readonly, copy, nonatomic) BMUserModel *createdByUser; // @synthesize createdByUser=_createdByUser;
@property(readonly, copy, nonatomic) NSNumber *usesRemaining; // @synthesize usesRemaining=_usesRemaining;
@property(readonly, copy, nonatomic) NSDate *createdAt; // @synthesize createdAt=_createdAt;
@property(readonly, copy, nonatomic) NSURL *codeURL; // @synthesize codeURL=_codeURL;
@property(readonly, copy, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;

@end

