//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing.h"

@class BMInviteModel;

@interface BMInviteResultModel : MTLModel <MTLJSONSerializing>
{
    BMInviteModel *_inviteModel;
}

+ (id)inviteModelJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(readonly, nonatomic) BMInviteModel *inviteModel; // @synthesize inviteModel=_inviteModel;
- (void).cxx_destruct;

@end

