//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "BMRecentNameReceiverDelegate.h"
#import "UITableViewDelegate.h"

@class BMCountdownView, BMNameListDataSourceController, BMRecentNameRetriever, NSString, UIButton, UILabel, UITableView, UIView;

@interface BMLandingViewController : BMViewController <BMRecentNameReceiverDelegate, UITableViewDelegate>
{
    id <BMLandingViewControllerDelegate> _delegate;
    BMNameListDataSourceController *_nameListDataSourceController;
    BMRecentNameRetriever *_fakeNameRetriever;
    UIView *_topContainerView;
    BMCountdownView *_countdownView;
    UILabel *_countDownLabel;
    UIView *_reserveView;
    UILabel *_reserveLabel;
    UIButton *_reserveButton;
    UIButton *_signinButton;
    UIView *_signinButtonContainerView;
    UIView *_tableContainerView;
    UILabel *_tableLabel;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UILabel *tableLabel; // @synthesize tableLabel=_tableLabel;
@property(retain, nonatomic) UIView *tableContainerView; // @synthesize tableContainerView=_tableContainerView;
@property(retain, nonatomic) UIView *signinButtonContainerView; // @synthesize signinButtonContainerView=_signinButtonContainerView;
@property(retain, nonatomic) UIButton *signinButton; // @synthesize signinButton=_signinButton;
@property(retain, nonatomic) UIButton *reserveButton; // @synthesize reserveButton=_reserveButton;
@property(retain, nonatomic) UILabel *reserveLabel; // @synthesize reserveLabel=_reserveLabel;
@property(retain, nonatomic) UIView *reserveView; // @synthesize reserveView=_reserveView;
@property(retain, nonatomic) UILabel *countDownLabel; // @synthesize countDownLabel=_countDownLabel;
@property(retain, nonatomic) BMCountdownView *countdownView; // @synthesize countdownView=_countdownView;
@property(retain, nonatomic) UIView *topContainerView; // @synthesize topContainerView=_topContainerView;
@property(retain, nonatomic) BMRecentNameRetriever *fakeNameRetriever; // @synthesize fakeNameRetriever=_fakeNameRetriever;
@property(retain, nonatomic) BMNameListDataSourceController *nameListDataSourceController; // @synthesize nameListDataSourceController=_nameListDataSourceController;
@property(nonatomic) __weak id <BMLandingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onRecentUsernameReceived:(id)arg1;
- (void)reserveButtonWasSelected:(id)arg1;
- (void)signinButtonPressed:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)showOnboarding;
- (void)setupTableView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)hideSigninButton;
- (void)showSigninButton;
- (void)hideReserve;
- (void)showReserve;
- (void)defineLayout;
- (void)setupSubviews;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

