//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "BMRecentNameReceiverDelegate.h"
#import "UITableViewDelegate.h"

@class BMCountdownView, BMNameListDataSourceController, BMRecentNameRetriever, NSString, UIButton, UILabel, UITableView, UIView;

@interface BMLandingViewController : BMViewController <BMRecentNameReceiverDelegate, UITableViewDelegate>
{
    id <BMLandingViewControllerDelegate> _delegate;
    BMNameListDataSourceController *_nameListDataSourceController;
    BMRecentNameRetriever *_recentNameRetriever;
    UIView *_topContainerView;
    BMCountdownView *_countdownView;
    UILabel *_countDownLabel;
    UIButton *_signInButton;
    UIView *_signInButtonContainerView;
    UIView *_signUpView;
    UIButton *_signUpButton;
    UILabel *_signUpLabel;
    UIView *_tableContainerView;
    UILabel *_tableLabel;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UILabel *tableLabel; // @synthesize tableLabel=_tableLabel;
@property(retain, nonatomic) UIView *tableContainerView; // @synthesize tableContainerView=_tableContainerView;
@property(retain, nonatomic) UILabel *signUpLabel; // @synthesize signUpLabel=_signUpLabel;
@property(retain, nonatomic) UIButton *signUpButton; // @synthesize signUpButton=_signUpButton;
@property(retain, nonatomic) UIView *signUpView; // @synthesize signUpView=_signUpView;
@property(retain, nonatomic) UIView *signInButtonContainerView; // @synthesize signInButtonContainerView=_signInButtonContainerView;
@property(retain, nonatomic) UIButton *signInButton; // @synthesize signInButton=_signInButton;
@property(retain, nonatomic) UILabel *countDownLabel; // @synthesize countDownLabel=_countDownLabel;
@property(retain, nonatomic) BMCountdownView *countdownView; // @synthesize countdownView=_countdownView;
@property(retain, nonatomic) UIView *topContainerView; // @synthesize topContainerView=_topContainerView;
@property(retain, nonatomic) BMRecentNameRetriever *recentNameRetriever; // @synthesize recentNameRetriever=_recentNameRetriever;
@property(retain, nonatomic) BMNameListDataSourceController *nameListDataSourceController; // @synthesize nameListDataSourceController=_nameListDataSourceController;
@property(nonatomic) __weak id <BMLandingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onRecentUsernameReceived:(id)arg1;
- (void)signUpButtonWasSelected:(id)arg1;
- (void)signInButtonWasSelected:(id)arg1;
- (void)showOnboarding;
- (void)setupTableView;
- (void)hideSignInButton;
- (void)showSignInButton;
- (void)hideReserve;
- (void)showReserve;
- (void)defineLayout;
- (void)setupSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

