//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSNumber, NSString, NSTimer, UIColor;

@interface BMMainTopViewModel : NSObject
{
    _Bool _reactionsButtonEnabled;
    _Bool _active;
    _Bool _authenticated;
    _Bool _reservedUser;
    unsigned long long _displayState;
    NSAttributedString *_infoString;
    UIColor *_mainLabelColor;
    NSString *_mainLabelString;
    NSString *_reactionsString;
    NSNumber *_beenSeconds;
    NSNumber *_beenUsers;
    NSString *_userName;
    unsigned long long _postingInfoStatus;
    double _postingProgressPercentage;
    unsigned long long _postingProgressRemainingBytes;
    NSTimer *_postingPulseTimer;
    NSTimer *_postingStatsTimer;
}

@property(nonatomic) _Bool reservedUser; // @synthesize reservedUser=_reservedUser;
@property(retain, nonatomic) NSTimer *postingStatsTimer; // @synthesize postingStatsTimer=_postingStatsTimer;
@property(retain, nonatomic) NSTimer *postingPulseTimer; // @synthesize postingPulseTimer=_postingPulseTimer;
@property(nonatomic) unsigned long long postingProgressRemainingBytes; // @synthesize postingProgressRemainingBytes=_postingProgressRemainingBytes;
@property(nonatomic) double postingProgressPercentage; // @synthesize postingProgressPercentage=_postingProgressPercentage;
@property(nonatomic) unsigned long long postingInfoStatus; // @synthesize postingInfoStatus=_postingInfoStatus;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSNumber *beenUsers; // @synthesize beenUsers=_beenUsers;
@property(copy, nonatomic) NSNumber *beenSeconds; // @synthesize beenSeconds=_beenSeconds;
@property(nonatomic) _Bool authenticated; // @synthesize authenticated=_authenticated;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(copy, nonatomic) NSString *reactionsString; // @synthesize reactionsString=_reactionsString;
@property(nonatomic) _Bool reactionsButtonEnabled; // @synthesize reactionsButtonEnabled=_reactionsButtonEnabled;
@property(copy, nonatomic) NSString *mainLabelString; // @synthesize mainLabelString=_mainLabelString;
@property(copy, nonatomic) UIColor *mainLabelColor; // @synthesize mainLabelColor=_mainLabelColor;
@property(copy, nonatomic) NSAttributedString *infoString; // @synthesize infoString=_infoString;
@property(nonatomic) unsigned long long displayState; // @synthesize displayState=_displayState;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (id)_timeIntervalToString:(double)arg1;
- (void)_updateProgress:(id)arg1;
- (id)_progressAttributedString;
- (id)_statsAttributedString;
- (id)_reactionsCountToString:(unsigned long long)arg1;
- (void)_resetPostingStatsTimer;
- (void)_resetPostingPulseTimer;
- (void)_startPostingStatsTimer;
- (void)_startPostingPulseTimer;
- (void)_updateInfoString;
- (void)_updateMainLabelString;
- (void)_updateReactionsStringWithCount:(unsigned long long)arg1;
- (void)_updateDisplayState;
- (void)_addObservation;
- (void)_togglePostingStatsDisplay;
- (void)postingWasSelected:(id)arg1;

@end

