//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

@class BMMainTopViewModel, UIButton, UILabel;

@interface BMMainTopViewController : BMViewController
{
    id <BMMainTopViewControllerDelegate> _delegate;
    BMMainTopViewModel *_viewModel;
    UIButton *_mainButton;
    UILabel *_infoLabel;
    UIButton *_reactionsButton;
    UIButton *_settingsButton;
}

@property(retain, nonatomic) UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UIButton *reactionsButton; // @synthesize reactionsButton=_reactionsButton;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) UIButton *mainButton; // @synthesize mainButton=_mainButton;
@property(retain, nonatomic) BMMainTopViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <BMMainTopViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)settingsButtonWasSelected:(id)arg1;
- (void)reactionsButtonWasSelected:(id)arg1;
- (void)mainButtonWasSelected:(id)arg1;
- (void)defineLayout;
- (void)setupSubviews;
- (void)viewDidLoad;

@end

