//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@interface BMMainViewPresenter : NSObject
{
    _Bool _shouldDisplayFeed;
    id <BMMainViewPresenterDelegate> _delegate;
    UIViewController *_viewController;
}

@property(nonatomic) _Bool shouldDisplayFeed; // @synthesize shouldDisplayFeed=_shouldDisplayFeed;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) __weak id <BMMainViewPresenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (Class)_viewControllerClassForDisplayFeedValue:(_Bool)arg1;
- (id)_viewControllerForDisplayFeedValue:(_Bool)arg1;
- (void)_refresh;
- (id)initialViewController;
- (id)init;

@end

