//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "BMFeedStatsViewDelegate.h"

@class BMFeedStatsView, NSString;

@interface BMMainTopViewController : BMViewController <BMFeedStatsViewDelegate>
{
    id <BMMainTopViewControllerDelegate> _delegate;
    BMFeedStatsView *_statsView;
}

@property(retain, nonatomic) BMFeedStatsView *statsView; // @synthesize statsView=_statsView;
@property(nonatomic) __weak id <BMMainTopViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)settingsButtonWasSelected:(id)arg1;
- (void)unlockButtonWasSelected:(id)arg1;
- (void)reactionsButtonWasSelected:(id)arg1;
- (void)removeNotifications;
- (void)addNotifications;
- (void)defineLayout;
- (void)setupSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

