//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing.h"

@class BMUserModel, NSDictionary, NSNumber, NSString;

@interface BMMeta : MTLModel <MTLJSONSerializing>
{
    NSString *_message;
    NSNumber *_status;
    BMUserModel *_user;
    NSString *_authTierString;
    NSDictionary *_cursor;
}

+ (id)userJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(readonly, copy, nonatomic) NSDictionary *cursor; // @synthesize cursor=_cursor;
@property(readonly, copy, nonatomic) NSString *authTierString; // @synthesize authTierString=_authTierString;
@property(readonly, nonatomic) BMUserModel *user; // @synthesize user=_user;
@property(readonly, copy, nonatomic) NSNumber *status; // @synthesize status=_status;
@property(readonly, copy, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;

@end

