//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMDataSourceController.h"

@interface BMNameListDataSourceController : BMDataSourceController
{
}

- (void)setAnchorPoint:(struct CGPoint)arg1 forView:(id)arg2;
- (void)addData:(id)arg1;

@end

