//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMMotionManager, NSOperationQueue;

@interface BMOrientationObserver : NSObject
{
    double rotationRateZ;
    int _currentOrientation;
    id <BMOrientationObserver> _delegate;
    CMMotionManager *_motionManager;
    NSOperationQueue *_motionQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSOperationQueue *motionQueue; // @synthesize motionQueue=_motionQueue;
@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
@property(nonatomic) int currentOrientation; // @synthesize currentOrientation=_currentOrientation;
@property(nonatomic) __weak id <BMOrientationObserver> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)checkMotion:(id)arg1 withError:(id)arg2;
- (void)checkAccelerometerData:(id)arg1 withError:(id)arg2;
- (void)resetFrame;
- (void)stopDeviceMotionUpdates;
- (void)startDeviceMotionUpdates;
- (id)init;

@end

