//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSString, UIView;

@interface BMPermissionController : NSObject <CLLocationManagerDelegate>
{
    int _permissionType;
    id <BMPermissionRequestDelegate> _delegate;
    UIView *_sourceView;
    CLLocationManager *_locationManager;
}

+ (_Bool)hasPermission:(int)arg1;
+ (id)permissionRequesterFromView:(id)arg1 delegate:(id)arg2 permission:(int)arg3;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(nonatomic) int permissionType; // @synthesize permissionType=_permissionType;
@property(nonatomic) __weak UIView *sourceView; // @synthesize sourceView=_sourceView;
@property(nonatomic) __weak id <BMPermissionRequestDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)requestSystemPermissionContacts;
- (void)determinePermissionContacts;
- (void)requestSystemPermissionCamera:(CDUnknownBlockType)arg1;
- (void)requestSystemPermissionMic:(CDUnknownBlockType)arg1;
- (void)requestSystemPermissionMicCamera;
- (void)determinePermissionMicCamera;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)requestSystemPermissionLocation;
- (void)determinePermissionLocation;
- (void)requestSystemPermissionPush;
- (void)determinePermissionPush;
- (void)determinePermissionPushAndLocation;
- (void)notifyPermissionEnabled:(_Bool)arg1;
- (void)permissionRequestAcknowledged;
- (void)displayAlertView:(id)arg1 message:(id)arg2;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

