//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMPlayerViewController;

@protocol BMPlayerViewControllerDelegate <NSObject>
- (void)playerViewControllerPlaybackDidEndWithReportRequest:(BMPlayerViewController *)arg1;
- (void)playerViewControllerPlaybackFailed:(BMPlayerViewController *)arg1;
- (void)playerViewControllerPlaybackDidEnd:(BMPlayerViewController *)arg1;
@end

