//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BMReactionCaptureViewDelegate.h"
#import "BMVideoTouchEventDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class AVPlayerItem, AVPlayerLayer, BMPlayer, BMPlayerInfoLabelView, BMReactionCaptureController, BMReactionCaptureView, BMSnakeProgressView, BMStackModel, BMVideoTouchRecognizer, NSMutableDictionary, NSString, UIImageView, UIView;

@interface BMPlayerViewController : UIViewController <BMVideoTouchEventDelegate, BMReactionCaptureViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _reactionsEnabled;
    id <BMPlayerViewControllerDelegate> _delegate;
    double _timeWatched;
    BMStackModel *_stack;
    unsigned long long _captureStatus;
    BMReactionCaptureController *_reactionCapture;
    BMReactionCaptureView *_reactionCaptureView;
    UIView *_flashView;
    BMPlayerInfoLabelView *_labelView;
    UIImageView *_loadingView;
    BMPlayer *_player;
    UIView *_playerContainerView;
    AVPlayerItem *_playerItem;
    AVPlayerLayer *_playerLayer;
    BMSnakeProgressView *_progressView;
    BMVideoTouchRecognizer *_touchRecognizer;
    UIView *_touchView;
    NSMutableDictionary *_logEvents;
}

@property(retain, nonatomic) NSMutableDictionary *logEvents; // @synthesize logEvents=_logEvents;
@property(retain, nonatomic) UIView *touchView; // @synthesize touchView=_touchView;
@property(retain, nonatomic) BMVideoTouchRecognizer *touchRecognizer; // @synthesize touchRecognizer=_touchRecognizer;
@property(retain, nonatomic) BMSnakeProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) UIView *playerContainerView; // @synthesize playerContainerView=_playerContainerView;
@property(retain, nonatomic) BMPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) UIImageView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) BMPlayerInfoLabelView *labelView; // @synthesize labelView=_labelView;
@property(retain, nonatomic) UIView *flashView; // @synthesize flashView=_flashView;
@property(nonatomic) _Bool reactionsEnabled; // @synthesize reactionsEnabled=_reactionsEnabled;
@property(retain, nonatomic) BMReactionCaptureView *reactionCaptureView; // @synthesize reactionCaptureView=_reactionCaptureView;
@property(retain, nonatomic) BMReactionCaptureController *reactionCapture; // @synthesize reactionCapture=_reactionCapture;
@property(nonatomic) unsigned long long captureStatus; // @synthesize captureStatus=_captureStatus;
@property(nonatomic) __weak BMStackModel *stack; // @synthesize stack=_stack;
@property(nonatomic) double timeWatched; // @synthesize timeWatched=_timeWatched;
@property(nonatomic) __weak id <BMPlayerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onTouchButton;
- (void)onNoLongerTouching;
- (void)showCaptureTriggered;
- (void)touchEnergyHighTriggered;
- (void)captureTriggered;
- (void)playbackEndedByReporting;
- (void)playbackDidEnd;
- (void)playbackFailed;
@property(readonly, nonatomic) double elapseTime;
- (void)captureUICompleted;
- (void)flashScreen;
- (void)triggerReactionCapture;
- (void)hidePreview;
- (void)showPreview;
- (void)hideLabel;
- (void)hideOverlay;
- (void)showOverlay;
- (void)teardownReactionCapture;
- (void)setupReactionCapture;
- (void)playURL:(id)arg1;
- (void)handleErrorNotification:(id)arg1;
- (void)handleAccessNotification:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

