//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface BMPolicyView : UIView
{
}

+ (id)defaultPolicyView;
- (void)tapOnPrivacyPolicyLink:(id)arg1;
- (void)tapOnTermsOfServiceLink:(id)arg1;
- (void)applyPolicyLabelToPolicyView:(id)arg1;
- (id)initWithString:(id)arg1;

@end

