//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BMProximityControlTargetActionObject : NSObject
{
    id _target;
    SEL _action;
    unsigned long long _events;
}

@property(nonatomic) unsigned long long events; // @synthesize events=_events;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
- (void).cxx_destruct;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2 proximityEvents:(unsigned long long)arg3;

@end

