//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OVCResponse.h"

@class BMMeta;

@interface BMResponse : OVCResponse
{
    BMMeta *_meta;
    long long _statusCode;
}

+ (id)resultKeyPathForJSONDictionary:(id)arg1;
+ (id)metaJSONTransformer;
+ (id)responseWithHTTPResponse:(id)arg1 JSONObject:(id)arg2 resultClass:(Class)arg3;
@property(nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;
@property(readonly, nonatomic) BMMeta *meta; // @synthesize meta=_meta;
- (void).cxx_destruct;

@end

