//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSSet, NSString;

@interface BMReaction : NSObject
{
    NSArray *_dataSource;
    NSSet *_viewedReactions;
    NSString *_dataSourceCacheInvalidationContext;
}

@property(retain, nonatomic) NSString *dataSourceCacheInvalidationContext; // @synthesize dataSourceCacheInvalidationContext=_dataSourceCacheInvalidationContext;
@property(retain, nonatomic) NSSet *viewedReactions; // @synthesize viewedReactions=_viewedReactions;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)addViewedItems:(id)arg1;
- (id)allItems;
- (id)refresh;
- (void)updateCurrentUsersReactionCount;
- (id)init;

@end

