//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing.h"

@class NSArray;

@interface BMReactionListModel : MTLModel <MTLJSONSerializing>
{
    NSArray *_reactions;
}

+ (id)reactionsJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(readonly, nonatomic) NSArray *reactions; // @synthesize reactions=_reactions;
- (void).cxx_destruct;

@end

