//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSNumber, NSString;

@protocol BMReactionProtocol <NSObject>
@property(copy, nonatomic) NSString *localFilename;
@property(nonatomic) unsigned long long state;
@property(copy, nonatomic) NSDate *postedAt;
@property(copy, nonatomic) NSNumber *longitude;
@property(copy, nonatomic) NSNumber *latitude;
@property(copy, nonatomic) NSNumber *secsIntoClip;
@property(copy, nonatomic) NSString *clipId;
@property(copy, nonatomic) NSString *recipientUserId;
@property(copy, nonatomic) NSString *senderUserId;
@property(copy, nonatomic) NSString *identifier;
@property(copy, nonatomic) NSString *localIdentifier;
@end

