//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface BMReportButton : UIButton
{
    CDUnknownBlockType _reportAction;
}

+ (id)reportButtonFlagView;
+ (id)reportButtonListView;
@property(copy, nonatomic) CDUnknownBlockType reportAction; // @synthesize reportAction=_reportAction;
- (void).cxx_destruct;
- (void)onTouchUpInside;
- (id)init;

@end

