//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class GPUImageSharpenFilter, GPUImageStillCamera, GPUImageView, UIImageView, UILabel;

@interface BMReactionCaptureView : UIView
{
    _Bool _capturing;
    id <BMReactionCaptureViewDelegate> _delegate;
    id <BMReactionCaptureImageDelegate> _imageDelegate;
    GPUImageStillCamera *_frontStillCamera;
    UILabel *_label;
    GPUImageView *_previewView;
    UIImageView *_imageView;
    GPUImageSharpenFilter *_sharpenFilter;
}

@property(getter=isCapturing) _Bool capturing; // @synthesize capturing=_capturing;
@property(retain, nonatomic) GPUImageSharpenFilter *sharpenFilter; // @synthesize sharpenFilter=_sharpenFilter;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) GPUImageView *previewView; // @synthesize previewView=_previewView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) GPUImageStillCamera *frontStillCamera; // @synthesize frontStillCamera=_frontStillCamera;
@property(nonatomic) __weak id <BMReactionCaptureImageDelegate> imageDelegate; // @synthesize imageDelegate=_imageDelegate;
@property(nonatomic) __weak id <BMReactionCaptureViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)finishCapture;
- (void)captureCompletedWith:(id)arg1;
- (void)stop;
- (void)capture;
- (void)start;
- (void)layoutSubviews;
- (void)setup;
- (void)dealloc;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

