//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "BMReactionProtocol.h"
#import "MTLJSONSerializing.h"

@class BMUploadURLModel, NSDate, NSNumber, NSString;

@interface BMReactionModel : MTLModel <MTLJSONSerializing, BMReactionProtocol>
{
    NSString *_localIdentifier;
    NSString *_identifier;
    NSString *_senderUserId;
    NSString *_recipientUserId;
    NSString *_clipId;
    NSNumber *_secsIntoClip;
    NSNumber *_latitude;
    NSNumber *_longitude;
    NSDate *_postedAt;
    unsigned long long _state;
    NSString *_localFilename;
    BMUploadURLModel *_uploadURLs;
}

+ (id)uploadURLsJSONTransformer;
+ (id)stateJSONTransformer;
+ (id)postedAtJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(copy, nonatomic) BMUploadURLModel *uploadURLs; // @synthesize uploadURLs=_uploadURLs;
@property(copy, nonatomic) NSString *localFilename; // @synthesize localFilename=_localFilename;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSDate *postedAt; // @synthesize postedAt=_postedAt;
@property(copy, nonatomic) NSNumber *longitude; // @synthesize longitude=_longitude;
@property(copy, nonatomic) NSNumber *latitude; // @synthesize latitude=_latitude;
@property(copy, nonatomic) NSNumber *secsIntoClip; // @synthesize secsIntoClip=_secsIntoClip;
@property(copy, nonatomic) NSString *clipId; // @synthesize clipId=_clipId;
@property(copy, nonatomic) NSString *recipientUserId; // @synthesize recipientUserId=_recipientUserId;
@property(copy, nonatomic) NSString *senderUserId; // @synthesize senderUserId=_senderUserId;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *localIdentifier; // @synthesize localIdentifier=_localIdentifier;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

