//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMReactionCaptureImageDelegate.h"

@class BMReactionModel, BMStackModel, NSString;

@interface BMReactionCaptureController : NSObject <BMReactionCaptureImageDelegate>
{
    BMStackModel *_stackModel;
    BMReactionModel *_reactionModel;
    double _captureTime;
}

+ (id)generateCaptureWith:(id)arg1 videoPlayer:(id)arg2 onStack:(id)arg3 atTime:(double)arg4;
@property(nonatomic) double captureTime; // @synthesize captureTime=_captureTime;
@property(retain, nonatomic) BMReactionModel *reactionModel; // @synthesize reactionModel=_reactionModel;
@property(retain, nonatomic) BMStackModel *stackModel; // @synthesize stackModel=_stackModel;
- (void).cxx_destruct;
- (id)uploadReactionToURL:(id)arg1 imageData:(id)arg2;
- (void)onImageRetrieved:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

