//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMReactionProtocol.h"

@class NSDate, NSNumber, NSString;

@interface BMReactionProtocol_ProtocolMethodContainer : NSObject <BMReactionProtocol>
{
}

+ (void)load;

// Remaining properties
@property(copy, nonatomic) NSString *clipId;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSString *identifier;
@property(copy, nonatomic) NSNumber *latitude;
@property(copy, nonatomic) NSString *localFilename;
@property(copy, nonatomic) NSString *localIdentifier;
@property(copy, nonatomic) NSNumber *longitude;
@property(copy, nonatomic) NSDate *postedAt;
@property(copy, nonatomic) NSString *recipientUserId;
@property(copy, nonatomic) NSNumber *secsIntoClip;
@property(copy, nonatomic) NSString *senderUserId;
@property(nonatomic) unsigned long long state;
@property(readonly) Class superclass;

@end

