//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "BMReportActionDelegate.h"

@class BMPlayerInfoLabelView, BMReactionItemModel, NSArray, NSMutableArray, NSString, UIButton, UIImageView, UILabel;

@interface BMReactionsViewController : BMViewController <BMReportActionDelegate>
{
    _Bool _hadReportEvent;
    _Bool _loadingReactions;
    _Bool _endOfReactions;
    NSArray *_reactions;
    NSMutableArray *_viewedReactions;
    long long _currentReactionIndex;
    NSMutableArray *_loadedReactions;
    BMReactionItemModel *_currentReaction;
    UIButton *_dismissButton;
    UIImageView *_reactionImageView;
    UIImageView *_thumbnailImageView;
    BMPlayerInfoLabelView *_detailLabelView;
    UILabel *_endOfReactionsLabel;
    UIImageView *_bemeLabelImageView;
    UIImageView *_loadingView;
    UIImageView *_filteredView;
}

@property(retain, nonatomic) UIImageView *filteredView; // @synthesize filteredView=_filteredView;
@property(retain, nonatomic) UIImageView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIImageView *bemeLabelImageView; // @synthesize bemeLabelImageView=_bemeLabelImageView;
@property(retain, nonatomic) UILabel *endOfReactionsLabel; // @synthesize endOfReactionsLabel=_endOfReactionsLabel;
@property(retain, nonatomic) BMPlayerInfoLabelView *detailLabelView; // @synthesize detailLabelView=_detailLabelView;
@property(retain, nonatomic) UIImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
@property(retain, nonatomic) UIImageView *reactionImageView; // @synthesize reactionImageView=_reactionImageView;
@property(retain, nonatomic) UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) BMReactionItemModel *currentReaction; // @synthesize currentReaction=_currentReaction;
@property(retain, nonatomic) NSMutableArray *loadedReactions; // @synthesize loadedReactions=_loadedReactions;
@property(nonatomic) _Bool endOfReactions; // @synthesize endOfReactions=_endOfReactions;
@property(nonatomic) long long currentReactionIndex; // @synthesize currentReactionIndex=_currentReactionIndex;
@property(nonatomic, getter=isLoadingReactions) _Bool loadingReactions; // @synthesize loadingReactions=_loadingReactions;
@property(nonatomic) _Bool hadReportEvent; // @synthesize hadReportEvent=_hadReportEvent;
@property(retain, nonatomic) NSMutableArray *viewedReactions; // @synthesize viewedReactions=_viewedReactions;
@property(copy, nonatomic) NSArray *reactions; // @synthesize reactions=_reactions;
- (void).cxx_destruct;
- (void)clearDataAndPerformVisibleRefresh;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)removeFilterIfApplied;
- (void)didSelectReport:(id)arg1;
- (void)didSelectBlock:(id)arg1;
- (void)didSelectCancel;
- (void)reportWasSelected:(id)arg1;
- (void)reactionViewDidReceiveGesture:(id)arg1;
- (void)dismissButtonWasSelected:(id)arg1;
- (void)reset;
- (void)displayEndOfReactions;
- (void)displayLoading;
- (void)displayReaction;
- (void)updateDisplay;
- (void)displayNextReaction;
- (void)flagReactionAsViewed:(id)arg1;
- (void)prefetchReactions;
- (void)defineLayout;
- (void)setupSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

