//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface BMReactionContentViewControllerModel : NSObject
{
    unsigned long long _index;
    NSString *_nameLabelText;
    NSString *_locationLabelText;
    UIImage *_bigImage;
    UIImage *_smallImage;
}

@property(copy, nonatomic) UIImage *smallImage; // @synthesize smallImage=_smallImage;
@property(copy, nonatomic) UIImage *bigImage; // @synthesize bigImage=_bigImage;
@property(copy, nonatomic) NSString *locationLabelText; // @synthesize locationLabelText=_locationLabelText;
@property(copy, nonatomic) NSString *nameLabelText; // @synthesize nameLabelText=_nameLabelText;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
- (void).cxx_destruct;

@end

