//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class BMReactionContentViewControllerModel, UIImageView, UILabel;

@interface BMReactionContentViewController : UIViewController
{
    BMReactionContentViewControllerModel *_model;
    UILabel *_nameLabel;
    UILabel *_locationLabel;
    UIImageView *_bigImageView;
    UIImageView *_videoImageView;
}

@property(retain, nonatomic) UIImageView *videoImageView; // @synthesize videoImageView=_videoImageView;
@property(retain, nonatomic) UIImageView *bigImageView; // @synthesize bigImageView=_bigImageView;
@property(retain, nonatomic) UILabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) BMReactionContentViewControllerModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end

