//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFAmazonS3Manager.h"

@interface BMS3NetworkClient : AFAmazonS3Manager
{
}

+ (id)sharedInstance;
- (id)uploadObjectWithMethod:(id)arg1 file:(id)arg2 destinationPath:(id)arg3 parameters:(id)arg4 progress:(CDUnknownBlockType)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (id)uploadFile:(id)arg1 toKey:(id)arg2;
- (id)uploadClip:(id)arg1;
- (id)init;

@end

