//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UISwitch, UIView;

@interface BMSettingToggleTableViewCell : UITableViewCell
{
    _Bool _value;
    CDUnknownBlockType _didChangeHandler;
    UIView *_lineView;
    UISwitch *_toggle;
}

@property(retain, nonatomic) UISwitch *toggle; // @synthesize toggle=_toggle;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(copy, nonatomic) CDUnknownBlockType didChangeHandler; // @synthesize didChangeHandler=_didChangeHandler;
@property(nonatomic) _Bool value; // @synthesize value=_value;
- (void).cxx_destruct;
- (void)switchValueDidChange:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

