//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "UITextFieldDelegate.h"

@class MASConstraint, NBPhoneNumberUtil, NSString, UIActivityIndicatorView, UIButton, UILabel, UITextField, UIView;

@interface BMSignInViewController : BMViewController <UITextFieldDelegate>
{
    UITextField *_usernameField;
    UITextField *_textFieldNumber;
    UITextField *_textFieldCountryCode;
    UIButton *_submitButton;
    UIActivityIndicatorView *_loadingIndicator;
    UILabel *_topLabel;
    UIView *_bottomView;
    UIView *_bottomPolicyView;
    id <BMSignInViewControllerViewControllerDelegate> _delegate;
    UIView *_containerView;
    UIView *_topView;
    MASConstraint *_containerBottomConstraint;
    UIView *_textField1ContainerView;
    UIView *_textField2ContainerView;
    NBPhoneNumberUtil *_phoneNumberUtil;
    NSString *_fullPhoneNumberString;
}

+ (id)kHeight;
@property(retain, nonatomic) NSString *fullPhoneNumberString; // @synthesize fullPhoneNumberString=_fullPhoneNumberString;
@property(retain, nonatomic) NBPhoneNumberUtil *phoneNumberUtil; // @synthesize phoneNumberUtil=_phoneNumberUtil;
@property(retain, nonatomic) UIView *textField2ContainerView; // @synthesize textField2ContainerView=_textField2ContainerView;
@property(retain, nonatomic) UIView *textField1ContainerView; // @synthesize textField1ContainerView=_textField1ContainerView;
@property(retain, nonatomic) MASConstraint *containerBottomConstraint; // @synthesize containerBottomConstraint=_containerBottomConstraint;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <BMSignInViewControllerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *bottomPolicyView; // @synthesize bottomPolicyView=_bottomPolicyView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) UIButton *submitButton; // @synthesize submitButton=_submitButton;
@property(retain, nonatomic) UITextField *textFieldCountryCode; // @synthesize textFieldCountryCode=_textFieldCountryCode;
@property(retain, nonatomic) UITextField *textFieldNumber; // @synthesize textFieldNumber=_textFieldNumber;
@property(retain, nonatomic) UITextField *usernameField; // @synthesize usernameField=_usernameField;
- (void).cxx_destruct;
- (void)requestValidationCode;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidChange;
- (void)updateTextFieldCountryCode;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)resetLogin;
- (void)requestValidationWithNumber:(id)arg1;
- (_Bool)hasValidPhoneNumber;
- (void)submit;
- (void)defineLayout;
- (void)setupSubview;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

