//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "BMCheckBoxPolicyViewDelegate.h"
#import "UITextFieldDelegate.h"

@class BMButton, BMCheckBoxPolicyView, BMSnakeProgressView, BMTextField, NBPhoneNumberUtil, NSString, UILabel, UIView;

@interface BMSignUpViewController : BMViewController <UITextFieldDelegate, BMCheckBoxPolicyViewDelegate>
{
    _Bool _grantingAccess;
    _Bool _verifyingNumber;
    _Bool _isValidUserName;
    UIView *_containerView;
    UILabel *_topLabel;
    BMTextField *_textFieldUserName;
    UIView *_checkBoxPolicyContainer;
    BMCheckBoxPolicyView *_checkBoxPolicyView;
    BMButton *_submitButton;
    UIView *_secondTextFieldContainerView;
    UILabel *_plusLabel;
    BMTextField *_textFieldCountryCode;
    BMTextField *_textFieldPhoneNumber;
    BMButton *_signInButton;
    BMSnakeProgressView *_loadingIndicator;
    UIView *_policyView;
    NBPhoneNumberUtil *_phoneNumberUtil;
    NSString *_fullPhoneNumberString;
}

@property(nonatomic) _Bool isValidUserName; // @synthesize isValidUserName=_isValidUserName;
@property(nonatomic) _Bool verifyingNumber; // @synthesize verifyingNumber=_verifyingNumber;
@property(nonatomic) _Bool grantingAccess; // @synthesize grantingAccess=_grantingAccess;
@property(retain, nonatomic) NSString *fullPhoneNumberString; // @synthesize fullPhoneNumberString=_fullPhoneNumberString;
@property(retain, nonatomic) NBPhoneNumberUtil *phoneNumberUtil; // @synthesize phoneNumberUtil=_phoneNumberUtil;
@property(retain, nonatomic) UIView *policyView; // @synthesize policyView=_policyView;
@property(retain, nonatomic) BMSnakeProgressView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) BMButton *signInButton; // @synthesize signInButton=_signInButton;
@property(retain, nonatomic) BMTextField *textFieldPhoneNumber; // @synthesize textFieldPhoneNumber=_textFieldPhoneNumber;
@property(retain, nonatomic) BMTextField *textFieldCountryCode; // @synthesize textFieldCountryCode=_textFieldCountryCode;
@property(retain, nonatomic) UILabel *plusLabel; // @synthesize plusLabel=_plusLabel;
@property(retain, nonatomic) UIView *secondTextFieldContainerView; // @synthesize secondTextFieldContainerView=_secondTextFieldContainerView;
@property(retain, nonatomic) BMButton *submitButton; // @synthesize submitButton=_submitButton;
@property(retain, nonatomic) BMCheckBoxPolicyView *checkBoxPolicyView; // @synthesize checkBoxPolicyView=_checkBoxPolicyView;
@property(retain, nonatomic) UIView *checkBoxPolicyContainer; // @synthesize checkBoxPolicyContainer=_checkBoxPolicyContainer;
@property(retain, nonatomic) BMTextField *textFieldUserName; // @synthesize textFieldUserName=_textFieldUserName;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (_Bool)hasValidPhoneNumber;
- (void)updateSubmitButton;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (void)checkBoxValueDidChangeWithValue:(_Bool)arg1;
- (void)updateTopLabelString:(id)arg1;
- (void)updateSignInButtonHiddenState:(_Bool)arg1;
- (void)updateFormElementsHiddenState:(_Bool)arg1 modifiesSignInButton:(_Bool)arg2 duration:(double)arg3 options:(unsigned long long)arg4 animated:(_Bool)arg5;
- (void)disableForm;
- (void)enableFormWithPreferredFirstResponder:(id)arg1;
- (void)verifyNumberForUserWithName:(id)arg1;
- (void)signUp;
- (void)checkUsernameAvailability:(id)arg1;
- (void)updateSearchBySMSSettings:(_Bool)arg1;
- (void)grantAccess;
- (void)submitButtonWasSelected:(id)arg1;
- (void)defineLayout;
- (void)setupSubviews;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

