//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMSignInViewController.h"

#import "BMCheckBoxPolicyViewDelegate.h"

@class BMCheckBoxPolicyView, NSString;

@interface BMSMSNagViewController : BMSignInViewController <BMCheckBoxPolicyViewDelegate>
{
    BMCheckBoxPolicyView *_checkBoxPolicyView;
}

@property(retain, nonatomic) BMCheckBoxPolicyView *checkBoxPolicyView; // @synthesize checkBoxPolicyView=_checkBoxPolicyView;
- (void).cxx_destruct;
- (void)resetLogin;
- (void)requestValidationWithNumber:(id)arg1;
- (void)checkBoxValueDidChangeWithValue:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setup;
- (id)initWithDelegate:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

