//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class UIColor;

@interface BMSnakeProgressLayer : CALayer
{
    _Bool _animateCounterclockwise;
    _Bool _animating;
    _Bool _progressCounterclockwise;
    double _animationPhase;
}

+ (_Bool)needsDisplayForKey:(id)arg1;
@property(nonatomic) _Bool progressCounterclockwise; // @synthesize progressCounterclockwise=_progressCounterclockwise;
@property(nonatomic) double animationPhase; // @synthesize animationPhase=_animationPhase;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic) _Bool animateCounterclockwise; // @synthesize animateCounterclockwise=_animateCounterclockwise;
- (void)drawInContext:(struct CGContext *)arg1;
- (id)init;

// Remaining properties
@property(nonatomic) double progress; // @dynamic progress;
@property(retain, nonatomic) UIColor *progressColor; // @dynamic progressColor;
@property(nonatomic) double thickness; // @dynamic thickness;
@property(retain, nonatomic) UIColor *trackBackgroundColor; // @dynamic trackBackgroundColor;

@end

