//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UIColor;

@interface BMSnakeProgressView : UIView
{
    _Bool _counterclockwise;
    UIColor *_progressColor;
    NSTimer *_animationTimer;
}

+ (void)initialize;
+ (Class)layerClass;
@property(retain, nonatomic) NSTimer *animationTimer; // @synthesize animationTimer=_animationTimer;
@property(nonatomic) _Bool counterclockwise; // @synthesize counterclockwise=_counterclockwise;
@property(retain, nonatomic) UIColor *progressColor; // @synthesize progressColor=_progressColor;
- (void).cxx_destruct;
- (_Bool)progressCounterclockwise;
@property(nonatomic) double thickness;
- (id)progressBackgrondColor;
@property(retain, nonatomic) UIColor *trackBackgroundColor;
- (void)updateAnimating;
- (void)stopAnimating;
- (void)startAnimating;
@property(nonatomic) double progress;
- (void)didMoveToWindow;
- (id)progressLayer;
- (void)dealloc;

@end

