//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing.h"

@class NSArray;

@interface BMStrangersModel : MTLModel <MTLJSONSerializing>
{
    NSArray *_strangers;
}

+ (id)JSONTransformerForKey:(id)arg1;
+ (id)JSONKeyPathsByPropertyKey;
@property(readonly, nonatomic) NSArray *strangers; // @synthesize strangers=_strangers;
- (void).cxx_destruct;

@end

