//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BMStackModelRecommendation : NSObject
{
    NSString *_reason;
    NSString *_reasonText;
}

+ (id)recommendationWithReason:(id)arg1 reasonText:(id)arg2;
@property(readonly, nonatomic) NSString *reasonText; // @synthesize reasonText=_reasonText;
@property(readonly, nonatomic) NSString *reason; // @synthesize reason=_reason;
- (void).cxx_destruct;
- (id)initWithReason:(id)arg1 reasonText:(id)arg2;

@end

