//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMCaptureSessionProtocol.h"

@class GPUImageMovieWriter, GPUImageVideoCamera, NSCache, NSMutableDictionary, NSString, NSTimer, NSURL, TBSMStateMachine;

@interface BMSystemCameraCaptureSessionController : NSObject <BMCaptureSessionProtocol>
{
    _Bool _cancelRequested;
    _Bool _capturing;
    id <BMCaptureSessionDelegate> _delegate;
    GPUImageVideoCamera *_backVideoCamera;
    NSCache *_cancelledTasks;
    NSTimer *_captureTimer;
    GPUImageMovieWriter *_movieWriter;
    NSURL *_targetDirectoryURL;
    TBSMStateMachine *_stateMachine;
    NSMutableDictionary *_saveTasks;
    CDStruct_e83c9415 _timeRange;
}

@property(nonatomic) CDStruct_e83c9415 timeRange; // @synthesize timeRange=_timeRange;
@property(retain, nonatomic) NSMutableDictionary *saveTasks; // @synthesize saveTasks=_saveTasks;
@property(retain, nonatomic) TBSMStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) NSURL *targetDirectoryURL; // @synthesize targetDirectoryURL=_targetDirectoryURL;
@property(retain, nonatomic) GPUImageMovieWriter *movieWriter; // @synthesize movieWriter=_movieWriter;
@property(retain, nonatomic) NSTimer *captureTimer; // @synthesize captureTimer=_captureTimer;
@property(retain, nonatomic) NSCache *cancelledTasks; // @synthesize cancelledTasks=_cancelledTasks;
@property(retain, nonatomic) GPUImageVideoCamera *backVideoCamera; // @synthesize backVideoCamera=_backVideoCamera;
@property(nonatomic, getter=isCapturing) _Bool capturing; // @synthesize capturing=_capturing;
@property(nonatomic) _Bool cancelRequested; // @synthesize cancelRequested=_cancelRequested;
@property(nonatomic) __weak id <BMCaptureSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)delegatePerformSelector:(SEL)arg1;
- (void)informDelegateDidFinishSavingWithVideoFileURL:(id)arg1;
- (void)informDelegateOfProgress:(double)arg1;
- (void)informDelegateDidCancel;
- (void)informDelegateDidFinish;
- (void)informDelegateDidStart;
- (void)informDelegateUnavailable;
- (void)setupMovieWriter;
- (void)teardown;
- (void)updateProgress;
- (void)startTimer;
- (void)resetTimer;
- (void)cancelWithMovieWriter:(id)arg1 url:(id)arg2;
- (void)saveWithMovieWriter:(id)arg1 url:(id)arg2;
- (void)stopCaptureWithSave:(_Bool)arg1;
- (void)cancelCaptureSession;
- (void)startCaptureSessionWithTimeRange:(CDStruct_e83c9415)arg1;
- (void)setupCaptureSessionForNewCapture;
- (_Bool)isReady;
- (_Bool)isAvailable;
- (void)dealloc;
- (id)initWithTargetDirectoryURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

