//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMProximityControl.h"

@class NSMutableArray, NSString;

@interface BMSystemProximityControl : NSObject <BMProximityControl>
{
    _Bool _enabled;
    _Bool _engaged;
    id <BMProximityControlDelegate> _delegate;
    NSMutableArray *_targetActions;
}

@property(nonatomic) _Bool engaged; // @synthesize engaged=_engaged;
@property(retain, nonatomic) NSMutableArray *targetActions; // @synthesize targetActions=_targetActions;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <BMProximityControlDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)addTarget:(id)arg1 action:(SEL)arg2 forProximityEvents:(unsigned long long)arg3;
- (_Bool)isEngaged;
- (void)sendProximityEvent:(unsigned long long)arg1;
- (void)proximityStateDidChange:(id)arg1;
- (void)disable;
- (void)enable;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

