//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface BMSystemSound : NSObject
{
    unsigned int soundID;
    _Bool _playing;
    NSURL *_fileURL;
    CDUnknownBlockType _completion;
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic, getter=isPlaying) _Bool playing; // @synthesize playing=_playing;
@property(retain, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (void).cxx_destruct;
- (void)disposeOfSystemSound;
- (int)createSystemSound;
- (void)stop;
- (void)playbackDidComplete;
- (void)play;
- (void)playWithCompletion:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithFileURL:(id)arg1;

@end

