//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BMTargetActionPair : NSObject
{
    id _target;
    NSString *_actionString;
}

+ (id)pairWithTarget:(id)arg1 action:(SEL)arg2;
@property(readonly, nonatomic) NSString *actionString; // @synthesize actionString=_actionString;
@property(readonly, nonatomic) __weak id target; // @synthesize target=_target;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)notify;
- (_Bool)isValid;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

