//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BMTrancoderOperationDelegate.h"

@class NSMutableDictionary, NSOperationQueue, NSString;

@interface BMTranscoderManager : NSObject <BMTrancoderOperationDelegate>
{
    NSOperationQueue *_operationQueue;
    NSMutableDictionary *_operations;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableDictionary *operations; // @synthesize operations=_operations;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void).cxx_destruct;
- (void)transcoderOperationDidFinish:(id)arg1 error:(id)arg2;
- (void)transcodeClip:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

