//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMClipOperation.h"

@class AVAssetExportSession, NSURL;

@interface BMTranscoderOperation : BMClipOperation
{
    AVAssetExportSession *_exportSession;
    NSURL *_outputURL;
}

+ (id)name;
@property(retain, nonatomic) NSURL *outputURL; // @synthesize outputURL=_outputURL;
@property(retain, nonatomic) AVAssetExportSession *exportSession; // @synthesize exportSession=_exportSession;
- (void).cxx_destruct;
- (void)performOperation;
- (id)init;

@end

