//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMClipOperation.h"

@class AVAssetExportSession, NSString, NSURL;

@interface BMTranscoderOperation : BMClipOperation
{
    id <BMTrancoderOperationDelegate> _delegate;
    NSString *_identifier;
    AVAssetExportSession *_exportSession;
    NSURL *_outputURL;
}

@property(retain, nonatomic) NSURL *outputURL; // @synthesize outputURL=_outputURL;
@property(retain, nonatomic) AVAssetExportSession *exportSession; // @synthesize exportSession=_exportSession;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) __weak id <BMTrancoderOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)performOperation;
- (id)initWithClip:(id)arg1 identifier:(id)arg2 delegate:(id)arg3;
- (id)initWithClip:(id)arg1;

@end

