//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

@class BMUserListViewController, UIButton, UILabel, UIView;

@interface BMUnlockCodesViewController : BMViewController
{
    UILabel *_label;
    UIButton *_generateUnlockButton;
    UIView *_generateUnlockContainerView;
    UILabel *_tableLabel;
    BMUserListViewController *_acceptedUsersViewController;
}

@property(retain, nonatomic) BMUserListViewController *acceptedUsersViewController; // @synthesize acceptedUsersViewController=_acceptedUsersViewController;
@property(retain, nonatomic) UILabel *tableLabel; // @synthesize tableLabel=_tableLabel;
@property(retain, nonatomic) UIView *generateUnlockContainerView; // @synthesize generateUnlockContainerView=_generateUnlockContainerView;
@property(retain, nonatomic) UIButton *generateUnlockButton; // @synthesize generateUnlockButton=_generateUnlockButton;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)shareText:(id)arg1 andImage:(id)arg2 andUrl:(id)arg3;
- (void)shareButtonPressed:(id)arg1;
- (void)updateTableLabelVisible:(_Bool)arg1;
- (void)defineLayout;
- (void)setupSubviews;
- (void)viewDidLoad;

@end

