//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMClipOperation.h"

@class AFHTTPRequestOperation, AFHTTPRequestOperationManager;

@interface BMUploadOperation : BMClipOperation
{
    id <BMUploadOperationDelegate> _delegate;
    AFHTTPRequestOperationManager *_operationManager;
    AFHTTPRequestOperation *_operation;
    double _progress;
}

+ (id)name;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) AFHTTPRequestOperation *operation; // @synthesize operation=_operation;
@property(retain, nonatomic) AFHTTPRequestOperationManager *operationManager; // @synthesize operationManager=_operationManager;
@property(nonatomic) __weak id <BMUploadOperationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)clipURLHasExpired;
- (void)refetchSignedURL:(CDUnknownBlockType)arg1;
- (void)performUploadClipWithOperationManager;
- (void)performOperation;
- (void)abort;
- (id)init;
- (void)dealloc;

@end

