//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol BMUploadOperationDelegate <NSObject>
- (void)uploadProgress:(double)arg1 remainingBytes:(long long)arg2 totalBytes:(long long)arg3 forClip:(id <BMClipProtocol>)arg4;
@end

