//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMClipOperation.h"

@class NSURLSessionUploadTask;

@interface BMUploadOperation : BMClipOperation
{
    _Bool _shouldRefetchURL;
    NSURLSessionUploadTask *_uploadTask;
}

@property(nonatomic) _Bool shouldRefetchURL; // @synthesize shouldRefetchURL=_shouldRefetchURL;
@property(retain, nonatomic) NSURLSessionUploadTask *uploadTask; // @synthesize uploadTask=_uploadTask;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)BMVersionSignedURLMethod;
- (void)performOperation;
- (id)init;

@end

