//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing.h"

@class BMUserModel, NSNumber;

@interface BMUserStatsModel : MTLModel <MTLJSONSerializing>
{
    NSNumber *_beenSeconds;
    NSNumber *_beenUsers;
    NSNumber *_userIdentifier;
    NSNumber *_followerCount;
    NSNumber *_followingCount;
    BMUserModel *_user;
}

+ (id)userJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(readonly, nonatomic) BMUserModel *user; // @synthesize user=_user;
@property(readonly, copy, nonatomic) NSNumber *followingCount; // @synthesize followingCount=_followingCount;
@property(readonly, copy, nonatomic) NSNumber *followerCount; // @synthesize followerCount=_followerCount;
@property(readonly, copy, nonatomic) NSNumber *userIdentifier; // @synthesize userIdentifier=_userIdentifier;
@property(readonly, copy, nonatomic) NSNumber *beenUsers; // @synthesize beenUsers=_beenUsers;
@property(readonly, copy, nonatomic) NSNumber *beenSeconds; // @synthesize beenSeconds=_beenSeconds;
- (void).cxx_destruct;

@end

