//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing.h"

@class NSDate, NSNumber, NSString;

@interface BMUserModel : MTLModel <MTLJSONSerializing>
{
    _Bool _isFollowing;
    _Bool _filterReactions;
    NSNumber *_confirmationCode;
    NSDate *_confirmationCodeUsedAt;
    NSDate *_createdAt;
    NSString *_deviceIdentifier;
    NSString *_displayName;
    NSString *_status;
    NSNumber *_identifier;
    NSDate *_followedAt;
    NSString *_bio;
    NSString *_locationString;
}

+ (id)filterReactionsJSONTransformer;
+ (id)isFollowingJSONTransformer;
+ (id)followedAtJSONTransformer;
+ (id)createdAtJSONTransformer;
+ (id)confirmationCodeUsedAtJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(readonly, copy, nonatomic) NSString *locationString; // @synthesize locationString=_locationString;
@property(readonly, copy, nonatomic) NSString *bio; // @synthesize bio=_bio;
@property(readonly, nonatomic) NSDate *followedAt; // @synthesize followedAt=_followedAt;
@property(nonatomic) _Bool filterReactions; // @synthesize filterReactions=_filterReactions;
@property(nonatomic) _Bool isFollowing; // @synthesize isFollowing=_isFollowing;
@property(readonly, copy, nonatomic) NSNumber *identifier; // @synthesize identifier=_identifier;
@property(readonly, copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(readonly, copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, copy, nonatomic) NSString *deviceIdentifier; // @synthesize deviceIdentifier=_deviceIdentifier;
@property(readonly, nonatomic) NSDate *createdAt; // @synthesize createdAt=_createdAt;
@property(readonly, nonatomic) NSDate *confirmationCodeUsedAt; // @synthesize confirmationCodeUsedAt=_confirmationCodeUsedAt;
@property(readonly, copy, nonatomic) NSNumber *confirmationCode; // @synthesize confirmationCode=_confirmationCode;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isActive;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;

@end

