//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSNumber, NSString, NSURL;

@interface BMUserManager : NSObject
{
    _Bool _active;
    _Bool _rejectAnonymousReactions;
    _Bool _allowSearchBySMS;
    _Bool _authenticating;
    NSString *_smsChallengeRequest;
    NSString *_authTierString;
    NSNumber *_beenSeconds;
    NSNumber *_beenUsers;
    NSNumber *_followerCount;
    NSNumber *_followingCount;
    NSNumber *_identifier;
    unsigned long long _reactionCount;
    NSString *_userName;
    NSURL *_profileImageURL;
    NSDictionary *_followUserLinkInfo;
    unsigned long long _watchedStacks;
    NSString *_pendingUsername;
    NSMutableDictionary *_following;
    NSMutableArray *_followedUsersByFollowLink;
}

+ (id)keyPathsForValuesAffectingIsReserved;
+ (id)keyPathsForValuesAffectingIsAuthenticated;
+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic, getter=isAuthenticating) _Bool authenticating; // @synthesize authenticating=_authenticating;
@property(retain, nonatomic) NSMutableArray *followedUsersByFollowLink; // @synthesize followedUsersByFollowLink=_followedUsersByFollowLink;
@property(retain, nonatomic) NSMutableDictionary *following; // @synthesize following=_following;
@property(copy, nonatomic) NSString *pendingUsername; // @synthesize pendingUsername=_pendingUsername;
@property(nonatomic) unsigned long long watchedStacks; // @synthesize watchedStacks=_watchedStacks;
@property(retain, nonatomic) NSDictionary *followUserLinkInfo; // @synthesize followUserLinkInfo=_followUserLinkInfo;
@property(copy, nonatomic) NSURL *profileImageURL; // @synthesize profileImageURL=_profileImageURL;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) unsigned long long reactionCount; // @synthesize reactionCount=_reactionCount;
@property(copy, nonatomic) NSNumber *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSNumber *followingCount; // @synthesize followingCount=_followingCount;
@property(copy, nonatomic) NSNumber *followerCount; // @synthesize followerCount=_followerCount;
@property(copy, nonatomic) NSNumber *beenUsers; // @synthesize beenUsers=_beenUsers;
@property(copy, nonatomic) NSNumber *beenSeconds; // @synthesize beenSeconds=_beenSeconds;
@property(nonatomic) _Bool allowSearchBySMS; // @synthesize allowSearchBySMS=_allowSearchBySMS;
@property(nonatomic) _Bool rejectAnonymousReactions; // @synthesize rejectAnonymousReactions=_rejectAnonymousReactions;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(copy, nonatomic) NSString *authTierString; // @synthesize authTierString=_authTierString;
@property(copy, nonatomic) NSString *smsChallengeRequest; // @synthesize smsChallengeRequest=_smsChallengeRequest;
- (void).cxx_destruct;
@property(nonatomic) NSDate *endDate;
@property(nonatomic) _Bool skipWelcomeCards;
@property(nonatomic) _Bool skipSMSNag;
@property(nonatomic) _Bool skipFollowNag;
@property(nonatomic) _Bool skipHoldToPlayNag;
@property(nonatomic) _Bool skipCaptureTutorial;
@property(nonatomic) _Bool skipPushNag;
- (void)_updateWithUser:(id)arg1;
- (_Bool)_authIsReserved;
- (void)completedFollowLink;
- (void)enteredFromBranchFollowLinkWithUserName:(id)arg1 code:(id)arg2;
- (void)enteredFromFollowLinkWithUserName:(id)arg1 code:(id)arg2;
- (void)updateFollowingUserWithIdentifier:(id)arg1 following:(_Bool)arg2 at:(id)arg3;
- (id)shareLinkURL;
- (void)updateWithMeta:(id)arg1;
- (void)updateWithLatestInfo:(id)arg1;
- (void)nukeAllStacksSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)updateSearchBySMSSetting:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)updateAnonymousReactionsSetting:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic, getter=isAuthenticated) _Bool authenticated; // @dynamic authenticated;
@property(readonly, nonatomic, getter=isReserved) _Bool reserved; // @dynamic reserved;
- (_Bool)isAuthSMSVerified;
- (_Bool)isAuthNamed;
- (void)setApiSecret:(id)arg1;
- (id)apiSecret;
- (void)setApiKey:(id)arg1;
- (id)apiKey;
- (void)updateLatestMeWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)verifyWithUsername:(id)arg1 mobileNumber:(id)arg2;
- (id)verifyWithNumber:(id)arg1;
- (void)updateStatusActiveWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (id)signInWithValidationCode:(id)arg1;
- (id)signUpWithUsername:(id)arg1;
- (void)checkUsernameAvailability:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)authenticate;
- (void)migrateDataIfNeeded;
- (void)clearUser;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) _Bool isAuthenticated;
@property(readonly, nonatomic) _Bool isReserved;

@end

