//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

#import "UITableViewDelegate.h"

@class BMUserListDataSourceController, NSString, UILabel, UIRefreshControl, UITableView;

@interface BMUserListViewController : BMViewController <UITableViewDelegate>
{
    _Bool _loading;
    _Bool _hasUsers;
    _Bool _preventUserRefresh;
    BMUserListDataSourceController *_dataSourceController;
    NSString *_emptyListString;
    UITableView *_tableView;
    UILabel *_emptyLabel;
    UIRefreshControl *_refreshControl;
    CDUnknownBlockType _viewWillAppearBlock;
}

+ (id)followersViewController;
+ (id)findFriendsViewController;
+ (id)acceptedInvitesViewController;
@property(copy, nonatomic) CDUnknownBlockType viewWillAppearBlock; // @synthesize viewWillAppearBlock=_viewWillAppearBlock;
@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(retain, nonatomic) UILabel *emptyLabel; // @synthesize emptyLabel=_emptyLabel;
@property(nonatomic) _Bool preventUserRefresh; // @synthesize preventUserRefresh=_preventUserRefresh;
@property(nonatomic) _Bool hasUsers; // @synthesize hasUsers=_hasUsers;
@property(nonatomic, getter=isLoading) _Bool loading; // @synthesize loading=_loading;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSString *emptyListString; // @synthesize emptyListString=_emptyListString;
@property(retain, nonatomic) BMUserListDataSourceController *dataSourceController; // @synthesize dataSourceController=_dataSourceController;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)refresh;
- (void)defineLayout;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

