//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMDataSourceController.h"

#import "BMCellButtonPressDelegate.h"
#import "BMReportActionDelegate.h"

@class NSString;

@interface BMUserListDataSourceController : BMDataSourceController <BMCellButtonPressDelegate, BMReportActionDelegate>
{
    CDUnknownBlockType _refreshBlock;
}

@property(copy, nonatomic) CDUnknownBlockType refreshBlock; // @synthesize refreshBlock=_refreshBlock;
- (void).cxx_destruct;
- (void)didSelectBlock:(id)arg1;
- (void)didSelectReport:(id)arg1;
- (void)didPressReportButton:(id)arg1;
- (void)didPressFollowButton:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (unsigned long long)count;
- (void)refresh;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

