//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing.h"

@class BMUserModel, NSURL;

@interface BMUsersMeResponseModel : MTLModel <MTLJSONSerializing>
{
    NSURL *_profileImageURL;
    BMUserModel *_user;
}

+ (id)userJSONTransformer;
+ (id)profileImageURLJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(copy, nonatomic) BMUserModel *user; // @synthesize user=_user;
@property(copy, nonatomic) NSURL *profileImageURL; // @synthesize profileImageURL=_profileImageURL;
- (void).cxx_destruct;

@end

