//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMViewController.h"

@interface BMViewController (Modal)
- (_Bool)isModal;
- (void)addRightCloseBarButtonItem:(unsigned long long)arg1;
- (void)addLeftCloseBarButtonItem:(unsigned long long)arg1;
- (id)barButtonItemWithImage:(id)arg1 inset:(struct UIEdgeInsets)arg2;
- (id)imageForCloseButtonType:(unsigned long long)arg1;
- (void)presentViewControllerWithinNavigationController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3 dismissBlock:(CDUnknownBlockType)arg4;
- (void)dismissAnimated:(_Bool)arg1;
- (void)dismiss;

// Remaining properties
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @dynamic dismissBlock;
@end

