//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface BMViewController : UIViewController
{
    _Bool _shouldDismissWhenInModalOnApplicationWillResignActive;
    _Bool _appearDisablesCaptureSession;
    _Bool _disappearEnablesCaptureSession;
    _Bool _statusBarHidden;
}

@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden; // @synthesize statusBarHidden=_statusBarHidden;
@property(nonatomic) _Bool disappearEnablesCaptureSession; // @synthesize disappearEnablesCaptureSession=_disappearEnablesCaptureSession;
@property(nonatomic) _Bool appearDisablesCaptureSession; // @synthesize appearDisablesCaptureSession=_appearDisablesCaptureSession;
@property(nonatomic) _Bool shouldDismissWhenInModalOnApplicationWillResignActive; // @synthesize shouldDismissWhenInModalOnApplicationWillResignActive=_shouldDismissWhenInModalOnApplicationWillResignActive;
- (_Bool)isVisible;
- (void)willResignActiveNotification:(id)arg1;
- (void)removeNotifications;
- (void)addNotifications;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

