//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BNCEncodingUtils : NSObject
{
}

+ (id)decodeQueryStringToDictionary:(id)arg1;
+ (id)decodeJsonStringToDictionary:(id)arg1;
+ (id)decodeJsonDataToDictionary:(id)arg1;
+ (id)encodeDictionaryToQueryString:(id)arg1;
+ (id)urlEncodedString:(id)arg1;
+ (id)encodeArrayToJsonString:(id)arg1;
+ (id)encodeDictionaryToJsonString:(id)arg1;
+ (id)encodeDictionaryToJsonData:(id)arg1;
+ (id)sanitizedStringFromString:(id)arg1;
+ (id)iso8601StringFromDate:(id)arg1;
+ (id)md5Encode:(id)arg1;
+ (id)base64DecodeString:(id)arg1;
+ (id)base64EncodeData:(id)arg1;
+ (id)base64DecodeStringToString:(id)arg1;
+ (id)base64EncodeStringToString:(id)arg1;

@end

