//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface BNCPreferenceHelper : NSObject
{
    _Bool _isReferrable;
    _Bool _isDebug;
    _Bool _isConnectedToRemoteDebug;
    _Bool _explicitlyRequestedReferrable;
    _Bool _isUsingLiveKey;
    NSString *_branchKey;
    NSString *_appKey;
    NSString *_lastRunBranchKey;
    NSString *_appVersion;
    NSString *_deviceFingerprintID;
    NSString *_sessionID;
    NSString *_identityID;
    NSString *_linkClickIdentifier;
    NSString *_userUrl;
    NSString *_userIdentity;
    NSString *_sessionParams;
    NSString *_installParams;
    long long _retryCount;
    long long _retryInterval;
    long long _timeout;
    NSMutableDictionary *_persistenceDict;
    NSMutableDictionary *_countsDictionary;
    NSMutableDictionary *_creditsDictionary;
}

+ (id)getInstance;
+ (id)preferenceHelper;
@property(nonatomic) _Bool isUsingLiveKey; // @synthesize isUsingLiveKey=_isUsingLiveKey;
@property(retain, nonatomic) NSMutableDictionary *creditsDictionary; // @synthesize creditsDictionary=_creditsDictionary;
@property(retain, nonatomic) NSMutableDictionary *countsDictionary; // @synthesize countsDictionary=_countsDictionary;
@property(retain, nonatomic) NSMutableDictionary *persistenceDict; // @synthesize persistenceDict=_persistenceDict;
@property(nonatomic) _Bool explicitlyRequestedReferrable; // @synthesize explicitlyRequestedReferrable=_explicitlyRequestedReferrable;
@property(nonatomic) long long timeout; // @synthesize timeout=_timeout;
@property(nonatomic) long long retryInterval; // @synthesize retryInterval=_retryInterval;
@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(nonatomic) _Bool isConnectedToRemoteDebug; // @synthesize isConnectedToRemoteDebug=_isConnectedToRemoteDebug;
@property(nonatomic) _Bool isDebug; // @synthesize isDebug=_isDebug;
@property(retain, nonatomic) NSString *userUrl; // @synthesize userUrl=_userUrl;
@property(retain, nonatomic) NSString *branchKey; // @synthesize branchKey=_branchKey;
- (void).cxx_destruct;
- (id)prefsFile;
- (long long)readIntegerFromDefaults:(id)arg1;
- (_Bool)readBoolFromDefaults:(id)arg1;
- (id)readStringFromDefaults:(id)arg1;
- (id)readObjectFromDefaults:(id)arg1;
- (void)persistPrefsToDisk;
- (void)writeObjectToDefaults:(id)arg1 value:(id)arg2;
- (void)writeBoolToDefaults:(id)arg1 value:(_Bool)arg2;
- (void)writeIntegerToDefaults:(id)arg1 value:(long long)arg2;
- (long long)getActionUniqueCount:(id)arg1;
- (long long)getActionTotalCount:(id)arg1;
- (void)setActionUniqueCount:(id)arg1 withCount:(long long)arg2;
- (void)setActionTotalCount:(id)arg1 withCount:(long long)arg2;
- (long long)getCreditCountForBucket:(id)arg1;
- (long long)getCreditCount;
- (void)setCreditCount:(long long)arg1 forBucket:(id)arg2;
- (void)setCreditCount:(long long)arg1;
- (void)clearUserCreditsAndCounts;
- (_Bool)getNeedAppListCheck;
- (void)setAppListCheckDone;
@property(nonatomic) _Bool isReferrable; // @synthesize isReferrable=_isReferrable;
- (void)setUserURL:(id)arg1;
- (id)userURL;
@property(retain, nonatomic) NSString *installParams; // @synthesize installParams=_installParams;
@property(retain, nonatomic) NSString *sessionParams; // @synthesize sessionParams=_sessionParams;
@property(retain, nonatomic) NSString *linkClickIdentifier; // @synthesize linkClickIdentifier=_linkClickIdentifier;
@property(retain, nonatomic) NSString *userIdentity; // @synthesize userIdentity=_userIdentity;
@property(retain, nonatomic) NSString *identityID; // @synthesize identityID=_identityID;
@property(retain, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(retain, nonatomic) NSString *deviceFingerprintID; // @synthesize deviceFingerprintID=_deviceFingerprintID;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *lastRunBranchKey; // @synthesize lastRunBranchKey=_lastRunBranchKey;
- (id)getBranchKey:(_Bool)arg1;
@property(retain, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
- (id)getAPIURL:(id)arg1;
- (id)getAPIBaseURL;
- (void)log:(id)arg1 line:(int)arg2 message:(id)arg3;
- (id)init;

@end

