//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSTimer;

@interface BNCServerRequestQueue : NSObject
{
    NSMutableArray *_queue;
    NSObject<OS_dispatch_queue> *_asyncQueue;
    NSTimer *_writeTimer;
}

+ (id)getInstance;
@property(retain, nonatomic) NSTimer *writeTimer; // @synthesize writeTimer=_writeTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *asyncQueue; // @synthesize asyncQueue=_asyncQueue;
@property(retain, nonatomic) NSMutableArray *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (id)queueFile;
- (id)exceptionString:(id)arg1;
- (void)retrieve;
- (void)persistToDisk;
- (void)persistImmediately;
- (void)persistEventually;
- (_Bool)containsClose;
- (id)moveInstallOrOpenToFront:(long long)arg1;
- (_Bool)containsInstallOrOpen;
- (void)clearQueue;
- (id)description;
@property(readonly, nonatomic) unsigned int size;
- (id)peekAt:(unsigned int)arg1;
- (id)peek;
- (void)remove:(id)arg1;
- (id)removeAt:(unsigned int)arg1;
- (id)dequeue;
- (void)insert:(id)arg1 at:(unsigned int)arg2;
- (void)enqueue:(id)arg1;
- (id)init;

@end

