//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BNCSystemObserver : NSObject
{
}

+ (id)getOpenableAppDictFromList:(id)arg1;
+ (id)getScreenHeight;
+ (id)getScreenWidth;
+ (id)getOSVersion;
+ (id)getOS;
+ (void)setUpdateState;
+ (id)getUpdateState;
+ (id)getDeviceName;
+ (_Bool)isSimulator;
+ (id)getModel;
+ (id)getBrand;
+ (id)getCarrier;
+ (id)getBundleID;
+ (id)getAppVersion;
+ (id)getDefaultUriScheme;
+ (_Bool)adTrackingSafe;
+ (id)getUniqueHardwareId:(_Bool *)arg1 andIsDebug:(_Bool)arg2;

@end

