//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BNCServerRequest.h"

@class NSDictionary;

@interface BranchUpdateAppListRequest : BNCServerRequest
{
    NSDictionary *_appList;
}

@property(retain, nonatomic) NSDictionary *appList; // @synthesize appList=_appList;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)processResponse:(id)arg1 error:(id)arg2;
- (void)makeRequest:(id)arg1 key:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (id)initWithAppList:(id)arg1;

@end

