//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BranchOpenRequest.h"

@interface BranchInstallRequest : BranchOpenRequest
{
}

- (void)safeSetValue:(id)arg1 forKey:(id)arg2 onDict:(id)arg3;
- (void)makeRequest:(id)arg1 key:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (id)initWithCallback:(CDUnknownBlockType)arg1;

@end

