//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BNCServerRequest.h"

@class NSDate, NSString;

@interface BranchGetPromoCodeRequest : BNCServerRequest
{
    _Bool _useOld;
    unsigned long long _usageType;
    unsigned long long _rewardLocation;
    long long _amount;
    NSString *_bucket;
    NSString *_prefix;
    NSDate *_expiration;
    CDUnknownBlockType _callback;
}

@property(nonatomic) _Bool useOld; // @synthesize useOld=_useOld;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(retain, nonatomic) NSDate *expiration; // @synthesize expiration=_expiration;
@property(retain, nonatomic) NSString *prefix; // @synthesize prefix=_prefix;
@property(retain, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
@property(nonatomic) long long amount; // @synthesize amount=_amount;
@property(nonatomic) unsigned long long rewardLocation; // @synthesize rewardLocation=_rewardLocation;
@property(nonatomic) unsigned long long usageType; // @synthesize usageType=_usageType;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)processResponse:(id)arg1 error:(id)arg2;
- (void)makeRequest:(id)arg1 key:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (id)initWithUsageType:(unsigned long long)arg1 rewardLocation:(unsigned long long)arg2 amount:(long long)arg3 bucket:(id)arg4 prefix:(id)arg5 expiration:(id)arg6 useOld:(_Bool)arg7 callback:(CDUnknownBlockType)arg8;

@end

