//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivityItemProvider.h"

@class NSArray, NSDictionary, NSString;

@interface BranchActivityItemProvider : UIActivityItemProvider
{
    NSDictionary *_params;
    NSArray *_tags;
    NSString *_feature;
    NSString *_stage;
    NSString *_alias;
    NSString *_userAgentString;
    id <BranchActivityItemProviderDelegate> _delegate;
}

+ (id)humanReadableChannelWithActivityType:(id)arg1;
@property(nonatomic) __weak id <BranchActivityItemProviderDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *userAgentString; // @synthesize userAgentString=_userAgentString;
@property(retain, nonatomic) NSString *alias; // @synthesize alias=_alias;
@property(retain, nonatomic) NSString *stage; // @synthesize stage=_stage;
@property(retain, nonatomic) NSString *feature; // @synthesize feature=_feature;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
- (void).cxx_destruct;
- (id)aliasForChannel:(id)arg1;
- (id)stageForChannel:(id)arg1;
- (id)featureForChannel:(id)arg1;
- (id)tagsForChannel:(id)arg1;
- (id)paramsForChannel:(id)arg1;
- (id)item;
- (id)initWithParams:(id)arg1 tags:(id)arg2 feature:(id)arg3 stage:(id)arg4 alias:(id)arg5 delegate:(id)arg6;
- (id)initWithParams:(id)arg1 andTags:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andAlias:(id)arg5;

@end

