//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BNCServerRequest.h"

@class NSString;

@interface BranchValidatePromoCodeRequest : BNCServerRequest
{
    _Bool _useOld;
    NSString *_code;
    CDUnknownBlockType _callback;
}

@property(nonatomic) _Bool useOld; // @synthesize useOld=_useOld;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)processResponse:(id)arg1 error:(id)arg2;
- (void)makeRequest:(id)arg1 key:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (id)initWithCode:(id)arg1 useOld:(_Bool)arg2 callback:(CDUnknownBlockType)arg3;

@end

