//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BranchDeepLinkingControllerCompletionDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class BNCLinkCache, BNCPreferenceHelper, BNCServerInterface, BNCServerRequestQueue, NSMutableDictionary, NSObject<OS_dispatch_semaphore>, NSString, NSTimer, UILongPressGestureRecognizer, UIViewController;

@interface Branch : NSObject <UIGestureRecognizerDelegate, BranchDeepLinkingControllerCompletionDelegate>
{
    _Bool _isInitialized;
    _Bool _shouldCallSessionInitCallback;
    _Bool _shouldAutomaticallyDeepLink;
    BNCServerInterface *_bServerInterface;
    NSTimer *_sessionTimer;
    BNCServerRequestQueue *_requestQueue;
    NSObject<OS_dispatch_semaphore> *_processing_sema;
    CDUnknownBlockType _sessionInitWithParamsCallback;
    long long _networkCount;
    BNCLinkCache *_linkCache;
    BNCPreferenceHelper *_preferenceHelper;
    UILongPressGestureRecognizer *_debugGestureRecognizer;
    NSTimer *_debugHeartbeatTimer;
    NSString *_branchKey;
    NSMutableDictionary *_deepLinkControllers;
    UIViewController *_deepLinkPresentingController;
}

+ (id)getInstanceInternal:(id)arg1;
+ (void)setDebug;
+ (id)getBranchActivityItemWithParams:(id)arg1 andTags:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andAlias:(id)arg5;
+ (id)getBranchActivityItemWithParams:(id)arg1 andFeature:(id)arg2 andStage:(id)arg3 andAlias:(id)arg4;
+ (id)getBranchActivityItemWithParams:(id)arg1 andFeature:(id)arg2 andStage:(id)arg3 andTags:(id)arg4;
+ (id)getBranchActivityItemWithParams:(id)arg1 andFeature:(id)arg2 andStage:(id)arg3;
+ (id)getBranchActivityItemWithParams:(id)arg1 andFeature:(id)arg2;
+ (id)getBranchActivityItemWithParams:(id)arg1 feature:(id)arg2 stage:(id)arg3 tags:(id)arg4 alias:(id)arg5 delegate:(id)arg6;
+ (id)getBranchActivityItemWithParams:(id)arg1 feature:(id)arg2 stage:(id)arg3 tags:(id)arg4 alias:(id)arg5;
+ (id)getBranchActivityItemWithParams:(id)arg1 feature:(id)arg2 stage:(id)arg3 tags:(id)arg4;
+ (id)getBranchActivityItemWithParams:(id)arg1 feature:(id)arg2 stage:(id)arg3;
+ (id)getBranchActivityItemWithParams:(id)arg1 feature:(id)arg2;
+ (id)getBranchActivityItemWithParams:(id)arg1;
+ (id)getInstance:(id)arg1;
+ (id)getTestInstance;
+ (id)getInstance;
@property(nonatomic) __weak UIViewController *deepLinkPresentingController; // @synthesize deepLinkPresentingController=_deepLinkPresentingController;
@property(retain, nonatomic) NSMutableDictionary *deepLinkControllers; // @synthesize deepLinkControllers=_deepLinkControllers;
@property(retain, nonatomic) NSString *branchKey; // @synthesize branchKey=_branchKey;
@property(retain, nonatomic) NSTimer *debugHeartbeatTimer; // @synthesize debugHeartbeatTimer=_debugHeartbeatTimer;
@property(retain, nonatomic) UILongPressGestureRecognizer *debugGestureRecognizer; // @synthesize debugGestureRecognizer=_debugGestureRecognizer;
@property(retain, nonatomic) BNCPreferenceHelper *preferenceHelper; // @synthesize preferenceHelper=_preferenceHelper;
@property(retain, nonatomic) BNCLinkCache *linkCache; // @synthesize linkCache=_linkCache;
@property(nonatomic) _Bool shouldAutomaticallyDeepLink; // @synthesize shouldAutomaticallyDeepLink=_shouldAutomaticallyDeepLink;
@property(nonatomic) _Bool shouldCallSessionInitCallback; // @synthesize shouldCallSessionInitCallback=_shouldCallSessionInitCallback;
@property(nonatomic) _Bool isInitialized; // @synthesize isInitialized=_isInitialized;
@property(nonatomic) long long networkCount; // @synthesize networkCount=_networkCount;
@property(copy, nonatomic) CDUnknownBlockType sessionInitWithParamsCallback; // @synthesize sessionInitWithParamsCallback=_sessionInitWithParamsCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *processing_sema; // @synthesize processing_sema=_processing_sema;
@property(retain, nonatomic) BNCServerRequestQueue *requestQueue; // @synthesize requestQueue=_requestQueue;
@property(retain, nonatomic) NSTimer *sessionTimer; // @synthesize sessionTimer=_sessionTimer;
@property(retain, nonatomic) BNCServerInterface *bServerInterface; // @synthesize bServerInterface=_bServerInterface;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)keepDebugAlive;
- (void)endRemoteDebugging:(id)arg1;
- (void)startRemoteDebugging;
- (void)connectToDebug:(id)arg1;
- (void)addGesterRecognizer:(SEL)arg1;
- (void)addCancelDebugGestureRecognizer;
- (void)addDebugGestureRecognizer;
- (void)deepLinkingControllerCompleted;
- (void)dealloc;
- (void)handleInitFailure:(id)arg1;
- (void)handleInitSuccess;
- (void)registerInstallOrOpen:(Class)arg1;
- (void)initializeSession;
- (void)initUserSessionAndCallCallback:(_Bool)arg1;
- (void)processNextQueueItem;
- (void)insertRequestAtFront:(id)arg1;
- (void)callClose;
- (void)clearTimer;
- (void)applicationWillResignActive;
- (void)applicationDidBecomeActive;
- (id)prepareLinkDataFor:(id)arg1 andAlias:(id)arg2 andType:(unsigned long long)arg3 andMatchDuration:(unsigned long long)arg4 andChannel:(id)arg5 andFeature:(id)arg6 andStage:(id)arg7 andParams:(id)arg8 ignoreUAString:(id)arg9;
- (id)longUrlWithBaseUrl:(id)arg1 params:(id)arg2 tags:(id)arg3 feature:(id)arg4 channel:(id)arg5 stage:(id)arg6 alias:(id)arg7 duration:(unsigned long long)arg8 type:(unsigned long long)arg9;
- (id)generateLongURLWithParams:(id)arg1 andChannel:(id)arg2 andTags:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andAlias:(id)arg6;
- (id)generateShortUrl:(id)arg1 andAlias:(id)arg2 andType:(unsigned long long)arg3 andMatchDuration:(unsigned long long)arg4 andChannel:(id)arg5 andFeature:(id)arg6 andStage:(id)arg7 andParams:(id)arg8 ignoreUAString:(id)arg9;
- (void)generateShortUrl:(id)arg1 andAlias:(id)arg2 andType:(unsigned long long)arg3 andMatchDuration:(unsigned long long)arg4 andChannel:(id)arg5 andFeature:(id)arg6 andStage:(id)arg7 andParams:(id)arg8 andCallback:(CDUnknownBlockType)arg9;
- (void)log:(id)arg1;
- (void)applyPromoCode:(id)arg1 useOld:(_Bool)arg2 callback:(CDUnknownBlockType)arg3;
- (void)applyPromoCode:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)applyReferralCode:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)validatePromoCode:(id)arg1 useOld:(_Bool)arg2 callback:(CDUnknownBlockType)arg3;
- (void)validatePromoCode:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)validateReferralCode:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)getPromoCodeWithPrefix:(id)arg1 amount:(long long)arg2 expiration:(id)arg3 bucket:(id)arg4 usageType:(unsigned long long)arg5 rewardLocation:(unsigned long long)arg6 useOld:(_Bool)arg7 callback:(CDUnknownBlockType)arg8;
- (void)getPromoCodeWithPrefix:(id)arg1 amount:(long long)arg2 expiration:(id)arg3 bucket:(id)arg4 usageType:(unsigned long long)arg5 rewardLocation:(unsigned long long)arg6 callback:(CDUnknownBlockType)arg7;
- (void)getReferralCodeWithPrefix:(id)arg1 amount:(long long)arg2 expiration:(id)arg3 bucket:(id)arg4 calculationType:(unsigned long long)arg5 location:(unsigned long long)arg6 andCallback:(CDUnknownBlockType)arg7;
- (void)getReferralCodeWithPrefix:(id)arg1 amount:(long long)arg2 expiration:(id)arg3 andCallback:(CDUnknownBlockType)arg4;
- (void)getPromoCodeWithPrefix:(id)arg1 amount:(long long)arg2 expiration:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)getReferralCodeWithAmount:(long long)arg1 expiration:(id)arg2 andCallback:(CDUnknownBlockType)arg3;
- (void)getPromoCodeWithAmount:(long long)arg1 expiration:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)getReferralCodeWithPrefix:(id)arg1 amount:(long long)arg2 andCallback:(CDUnknownBlockType)arg3;
- (void)getPromoCodeWithPrefix:(id)arg1 amount:(long long)arg2 callback:(CDUnknownBlockType)arg3;
- (void)getReferralCodeWithAmount:(long long)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)getPromoCodeWithAmount:(long long)arg1 callback:(CDUnknownBlockType)arg2;
- (void)getReferralCodeWithCallback:(CDUnknownBlockType)arg1;
- (void)getPromoCodeWithCallback:(CDUnknownBlockType)arg1;
- (void)getReferralUrlWithParams:(id)arg1 andChannel:(id)arg2 andCallback:(CDUnknownBlockType)arg3;
- (void)getReferralUrlWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andCallback:(CDUnknownBlockType)arg4;
- (id)getReferralUrlWithParams:(id)arg1 andChannel:(id)arg2;
- (id)getReferralUrlWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3;
- (id)getLongURLWithParams:(id)arg1 andFeature:(id)arg2 andStage:(id)arg3 andAlias:(id)arg4;
- (id)getLongURLWithParams:(id)arg1 andFeature:(id)arg2 andStage:(id)arg3 andTags:(id)arg4;
- (id)getLongURLWithParams:(id)arg1 andFeature:(id)arg2 andStage:(id)arg3;
- (id)getLongURLWithParams:(id)arg1 andFeature:(id)arg2;
- (id)getLongURLWithParams:(id)arg1;
- (id)getLongURLWithParams:(id)arg1 andChannel:(id)arg2 andTags:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andAlias:(id)arg6;
- (void)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andCallback:(CDUnknownBlockType)arg4;
- (void)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andMatchDuration:(unsigned long long)arg5 andCallback:(CDUnknownBlockType)arg6;
- (void)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andType:(unsigned long long)arg5 andCallback:(CDUnknownBlockType)arg6;
- (void)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andAlias:(id)arg5 andCallback:(CDUnknownBlockType)arg6;
- (void)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andCallback:(CDUnknownBlockType)arg5;
- (void)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andMatchDuration:(unsigned long long)arg6 andCallback:(CDUnknownBlockType)arg7;
- (void)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andType:(unsigned long long)arg6 andCallback:(CDUnknownBlockType)arg7;
- (void)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andAlias:(id)arg6 andCallback:(CDUnknownBlockType)arg7;
- (void)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andCallback:(CDUnknownBlockType)arg6;
- (void)getShortURLWithParams:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)getShortURLWithCallback:(CDUnknownBlockType)arg1;
- (id)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3;
- (id)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andMatchDuration:(unsigned long long)arg5;
- (id)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andType:(unsigned long long)arg5;
- (id)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4 andAlias:(id)arg5;
- (id)getShortURLWithParams:(id)arg1 andChannel:(id)arg2 andFeature:(id)arg3 andStage:(id)arg4;
- (id)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andMatchDuration:(unsigned long long)arg6;
- (id)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andType:(unsigned long long)arg6;
- (id)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andAlias:(id)arg6 ignoreUAString:(id)arg7;
- (id)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5 andAlias:(id)arg6;
- (id)getShortURLWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andFeature:(id)arg4 andStage:(id)arg5;
- (id)getShortURLWithParams:(id)arg1;
- (id)getShortURL;
- (void)getContentUrlWithParams:(id)arg1 andChannel:(id)arg2 andCallback:(CDUnknownBlockType)arg3;
- (void)getContentUrlWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3 andCallback:(CDUnknownBlockType)arg4;
- (id)getContentUrlWithParams:(id)arg1 andTags:(id)arg2 andChannel:(id)arg3;
- (id)getContentUrlWithParams:(id)arg1 andChannel:(id)arg2;
- (id)getLatestReferringParams;
- (id)getFirstReferringParams;
- (void)getCreditHistoryForBucket:(id)arg1 after:(id)arg2 number:(long long)arg3 order:(unsigned long long)arg4 andCallback:(CDUnknownBlockType)arg5;
- (void)getCreditHistoryAfter:(id)arg1 number:(long long)arg2 order:(unsigned long long)arg3 andCallback:(CDUnknownBlockType)arg4;
- (void)getCreditHistoryForBucket:(id)arg1 andCallback:(CDUnknownBlockType)arg2;
- (void)getCreditHistoryWithCallback:(CDUnknownBlockType)arg1;
- (void)redeemRewards:(long long)arg1 forBucket:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)redeemRewards:(long long)arg1 forBucket:(id)arg2;
- (long long)getCreditsForBucket:(id)arg1;
- (void)redeemRewards:(long long)arg1 callback:(CDUnknownBlockType)arg2;
- (void)redeemRewards:(long long)arg1;
- (long long)getCredits;
- (void)loadRewardsWithCallback:(CDUnknownBlockType)arg1;
- (void)userCompletedAction:(id)arg1 withState:(id)arg2;
- (void)userCompletedAction:(id)arg1;
- (long long)getUniqueCountsForAction:(id)arg1;
- (long long)getTotalCountsForAction:(id)arg1;
- (void)loadActionCountsWithCallback:(CDUnknownBlockType)arg1;
- (void)logout;
- (void)setIdentity:(id)arg1 withCallback:(CDUnknownBlockType)arg2;
- (void)setIdentity:(id)arg1;
- (void)registerDeepLinkController:(id)arg1 forKey:(id)arg2;
- (_Bool)handleDeepLink:(id)arg1;
- (void)initSessionWithLaunchOptions:(id)arg1 isReferrable:(_Bool)arg2 explicitlyRequestedReferrable:(_Bool)arg3 automaticallyDisplayController:(_Bool)arg4 registerDeepLinkHandler:(CDUnknownBlockType)arg5;
- (void)initSessionWithLaunchOptions:(id)arg1 automaticallyDisplayDeepLinkController:(_Bool)arg2 isReferrable:(_Bool)arg3 deepLinkHandler:(CDUnknownBlockType)arg4;
- (void)initSessionAndAutomaticallyDisplayDeepLinkController:(_Bool)arg1 isReferrable:(_Bool)arg2 deepLinkHandler:(CDUnknownBlockType)arg3;
- (void)initSessionWithLaunchOptions:(id)arg1 isReferrable:(_Bool)arg2 automaticallyDisplayDeepLinkController:(_Bool)arg3;
- (void)initSessionWithLaunchOptions:(id)arg1 automaticallyDisplayDeepLinkController:(_Bool)arg2 deepLinkHandler:(CDUnknownBlockType)arg3;
- (void)initSessionWithLaunchOptions:(id)arg1 isReferrable:(_Bool)arg2 andRegisterDeepLinkHandler:(CDUnknownBlockType)arg3;
- (void)initSessionAndAutomaticallyDisplayDeepLinkController:(_Bool)arg1 deepLinkHandler:(CDUnknownBlockType)arg2;
- (void)initSession:(_Bool)arg1 automaticallyDisplayDeepLinkController:(_Bool)arg2;
- (void)initSession:(_Bool)arg1 andRegisterDeepLinkHandler:(CDUnknownBlockType)arg2;
- (void)initSessionWithLaunchOptions:(id)arg1 automaticallyDisplayDeepLinkController:(_Bool)arg2;
- (void)initSessionWithLaunchOptions:(id)arg1 isReferrable:(_Bool)arg2;
- (void)initSessionWithLaunchOptions:(id)arg1 andRegisterDeepLinkHandler:(CDUnknownBlockType)arg2;
- (void)initSessionAndRegisterDeepLinkHandler:(CDUnknownBlockType)arg1;
- (void)initSession:(_Bool)arg1;
- (void)initSessionWithLaunchOptions:(id)arg1;
- (void)initSessionAndAutomaticallyDisplayDeepLinkController:(_Bool)arg1;
- (void)initSession;
- (void)setRetryInterval:(double)arg1;
- (void)setMaxRetries:(long long)arg1;
- (void)setNetworkTimeout:(double)arg1;
- (_Bool)isUserIdentified;
- (void)resetUserSession;
- (void)setDebug;
- (id)initWithInterface:(id)arg1 queue:(id)arg2 cache:(id)arg3 preferenceHelper:(id)arg4 key:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

