//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImagePicture.h"

@interface GPUImagePicture (TextureSubimage)
- (void)replaceTextureWithSubCGImage:(struct CGImage *)arg1 inRect:(struct CGRect)arg2;
- (void)replaceTextureWithSubimage:(id)arg1 inRect:(struct CGRect)arg2;
- (void)replaceTextureWithSubCGImage:(struct CGImage *)arg1;
- (void)replaceTextureWithSubimage:(id)arg1;
@end

