//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GVUserDefaults.h"

@class NSNumber, NSString;

@interface GVUserDefaults (BeMe)
- (id)transformKey:(id)arg1;
- (id)setupDefaults;

// Remaining properties
@property(nonatomic) _Bool active; // @dynamic active;
@property(nonatomic) _Bool allowSearchBySMS; // @dynamic allowSearchBySMS;
@property(nonatomic) __weak NSString *apnsToken; // @dynamic apnsToken;
@property(nonatomic) __weak NSString *authTierString; // @dynamic authTierString;
@property(nonatomic) __weak NSNumber *beenSeconds; // @dynamic beenSeconds;
@property(nonatomic) __weak NSNumber *beenUsers; // @dynamic beenUsers;
@property(nonatomic) _Bool isFirstLaunch; // @dynamic isFirstLaunch;
@property(nonatomic) _Bool rejectAnonymousReactions; // @dynamic rejectAnonymousReactions;
@property(nonatomic) _Bool uploadedAPNSToken; // @dynamic uploadedAPNSToken;
@property(nonatomic) __weak NSNumber *userIdentifier; // @dynamic userIdentifier;
@property(nonatomic) __weak NSString *userName; // @dynamic userName;
@end

