//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSUserDefaults;

@interface GVUserDefaults : NSObject
{
    NSMutableDictionary *_mapping;
    NSUserDefaults *_userDefaults;
}

+ (id)standardUserDefaults;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(retain, nonatomic) NSMutableDictionary *mapping; // @synthesize mapping=_mapping;
- (void).cxx_destruct;
- (void)generateAccessorMethods;
- (id)_suiteName;
- (id)_transformKey:(id)arg1;
- (id)init;
- (id)defaultsKeyForSelector:(SEL)arg1;
- (id)defaultsKeyForPropertyNamed:(const char *)arg1;

@end

