//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLDBBase.h"

#import "LLUploaderDataSource.h"

@class NSString;

@interface LLAnalyticsDB : LLDBBase <LLUploaderDataSource>
{
}

- (unsigned long long)greatestDatapointId;
- (id)getUploadDataWithMaxId:(unsigned long long)arg1;
- (void)fullUploadDidFinish;
- (void)uploadBatchDidCompleteWithHighestUploadNumber:(unsigned long long)arg1;
- (_Bool)incrementNextSessionNumber;
- (_Bool)incrementNextHeaderNumber;
- (_Bool)incrementHeaderNumberAndAddEvent:(id)arg1;
- (id)eventAndHeaderBlobFromEvent:(id)arg1;
- (_Bool)removeQueuedCloseEvent;
- (_Bool)addQueuedCloseEvent;
- (_Bool)queueCloseEvent:(id)arg1;
- (_Bool)setOptedOut:(_Bool)arg1 withEvent:(id)arg2;
- (_Bool)openSessionWithEvent:(id)arg1 sessionStartTimeInterval:(double)arg2;
- (id)userType;
- (_Bool)setCustomerId:(id)arg1 userType:(id)arg2;
- (id)customerId;
- (id)identifiers;
- (_Bool)deleteIdentifer:(id)arg1;
- (id)valueForIdentifier:(id)arg1;
- (_Bool)setValue:(id)arg1 forIdentifier:(id)arg2;
- (_Bool)addEvent:(id)arg1;
- (unsigned long long)nextSessionNumber;
- (unsigned long long)nextHeaderNumber;
- (id)customDimensions;
- (_Bool)deleteCustomDimension:(unsigned long long)arg1;
- (_Bool)setValue:(id)arg1 forCustomDimension:(unsigned long long)arg2;
- (id)customDimension:(unsigned long long)arg1;
- (_Bool)updateFirstAdid:(id)arg1;
- (id)firstAdid;
- (_Bool)isFirstAdidNull;
- (void)setPushToken:(id)arg1;
- (_Bool)updateDevPushToken:(id)arg1;
- (id)devPushToken;
- (_Bool)isDevPushTokenNull;
- (_Bool)updatePushToken:(id)arg1;
- (id)pushToken;
- (_Bool)isPushTokenNull;
- (_Bool)updateAppVersion:(id)arg1;
- (_Bool)isAppVersionNull;
- (id)appVersion;
- (_Bool)setOptedOut:(_Bool)arg1;
- (_Bool)isOptedOut;
- (_Bool)setLastSessionStartTimestamp:(double)arg1;
- (double)lastSessionStartTimestamp;
- (_Bool)updateAppKey:(id)arg1;
- (id)appKey;
- (id)installId;
- (void)migrateFromV2Database:(id)arg1;
- (_Bool)initializeDatabase:(id)arg1;
- (id)initWithLocalyticsDelegate:(id)arg1;
- (id)migrations;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

