//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLUploaderBase.h"

@interface LLAnalyticsUploader : LLUploaderBase
{
}

- (id)gzipDeflatedDataWithData:(id)arg1;
- (id)createRequestWithURL:(id)arg1 installId:(id)arg2 libraryVersion:(id)arg3 customerId:(id)arg4 uploadData:(id)arg5;
- (void)uploadData:(id)arg1 withApplicationKey:(id)arg2 installId:(id)arg3 libraryVersion:(id)arg4 customerId:(id)arg5;

@end

