//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSNumber, NSString;

@protocol LLAnalyticsDelegate <NSObject>

@optional
- (void)localyticsSessionWillClose;
- (void)localyticsDidTagEvent:(NSString *)arg1 attributes:(NSDictionary *)arg2 customerValueIncrease:(NSNumber *)arg3;
- (void)localyticsSessionDidOpen:(_Bool)arg1 isUpgrade:(_Bool)arg2 isResume:(_Bool)arg3;
- (void)localyticsSessionWillOpen:(_Bool)arg1 isUpgrade:(_Bool)arg2 isResume:(_Bool)arg3;
@end

