//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LLTestButton, UINavigationController;

@interface LLCampaignTestModeController : NSObject
{
    _Bool _testModeEnabled;
    id <LLLocalyticsDelegate> _localyticsDelegate;
    LLTestButton *_testModeButton;
    UINavigationController *_campaignControlPanel;
}

+ (id)rootViewController;
+ (void)controlPanelClosed;
+ (_Bool)testModeEnabled;
+ (void)setTestModeEnabled:(_Bool)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) UINavigationController *campaignControlPanel; // @synthesize campaignControlPanel=_campaignControlPanel;
@property(retain, nonatomic) LLTestButton *testModeButton; // @synthesize testModeButton=_testModeButton;
@property(nonatomic) __weak id <LLLocalyticsDelegate> localyticsDelegate; // @synthesize localyticsDelegate=_localyticsDelegate;
@property(nonatomic) _Bool testModeEnabled; // @synthesize testModeEnabled=_testModeEnabled;
- (void).cxx_destruct;
- (void)dragTestButton:(id)arg1 withEvent:(id)arg2;
- (void)controlPanelClosed;
- (void)launchControlPanel;
- (void)hideTestModeButton;
- (void)showTestModeButton;
- (id)init;

@end

