//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LLCampaignTuple : NSObject
{
    _Bool _didDisplay;
    long long _ruleId;
}

@property(nonatomic) _Bool didDisplay; // @synthesize didDisplay=_didDisplay;
@property(nonatomic) long long ruleId; // @synthesize ruleId=_ruleId;

@end

