//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface LLCampaignCondition : NSObject
{
    int _op;
    NSString *_attributeName;
    NSArray *_values;
}

@property(retain, nonatomic) NSArray *values; // @synthesize values=_values;
@property(nonatomic) int op; // @synthesize op=_op;
@property(retain, nonatomic) NSString *attributeName; // @synthesize attributeName=_attributeName;
- (void).cxx_destruct;
- (id)toString;
- (_Bool)isSatisfiedByNumber:(id)arg1;
- (_Bool)isSatisfiedByString:(id)arg1;
- (_Bool)isSatisfiedWithAttributes:(id)arg1;
- (_Bool)areAttributesValid:(id)arg1;
- (_Bool)isConditionValid;
- (id)initWithSerializedCondition:(id)arg1;
- (id)formatOperatorToString;
- (int)formatStringToOperator:(id)arg1;

@end

