//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImage;

@interface LLCloseButton : UIButton
{
    _Bool isModal;
    _Bool _displayButtonOnLeft;
    UIImage *_dismissButtonImage;
}

+ (id)buttonWithType:(long long)arg1 forModalCampaignView:(_Bool)arg2;
@property(nonatomic) _Bool displayButtonOnLeft; // @synthesize displayButtonOnLeft=_displayButtonOnLeft;
@property(retain, nonatomic) UIImage *dismissButtonImage; // @synthesize dismissButtonImage=_dismissButtonImage;
@property(nonatomic) _Bool isModal; // @synthesize isModal;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

