//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface LLCustomerIdTuple : NSObject
{
    NSString *_customerId;
    NSString *_userType;
}

+ (id)tuple;
@property(copy, nonatomic) NSString *userType; // @synthesize userType=_userType;
@property(copy, nonatomic) NSString *customerId; // @synthesize customerId=_customerId;
- (void).cxx_destruct;

@end

