//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LLDatapointHelper : NSObject
{
}

+ (_Bool)remoteNotificationsEnabled;
+ (id)bundleIdentifier;
+ (id)identifierForVendor;
+ (_Bool)advertisingTrackingEnabled;
+ (id)advertisingIdentifier;
+ (double)availableMemory;
+ (id)modelSizeString;
+ (id)deviceModel;
+ (_Bool)isDevBuild;
+ (_Bool)isDeviceJailbroken;
+ (id)appVersion;

@end

