//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LL_FMDatabase;

@interface LLDBBase : NSObject
{
    unsigned long long _maxDatabaseSize;
    id <LLLocalyticsDelegate> _localyticsDelegate;
    LL_FMDatabase *_db;
}

@property(retain, nonatomic) LL_FMDatabase *db; // @synthesize db=_db;
@property(nonatomic) __weak id <LLLocalyticsDelegate> localyticsDelegate; // @synthesize localyticsDelegate=_localyticsDelegate;
@property(nonatomic) unsigned long long maxDatabaseSize; // @synthesize maxDatabaseSize=_maxDatabaseSize;
- (void).cxx_destruct;
- (_Bool)updateDB:(id)arg1 and:(id)arg2;
- (id)queryDB:(id)arg1 and:(id)arg2;
- (id)dictionaryForKeyValueTable:(id)arg1;
- (_Bool)incrementColumn:(id)arg1 inTable:(id)arg2;
- (_Bool)updateColumn:(id)arg1 toValue:(id)arg2 inTable:(id)arg3;
- (_Bool)replaceValueOne:(id)arg1 value2:(id)arg2 inTable:(id)arg3;
- (int)intForColumn:(id)arg1 inTable:(id)arg2;
- (double)doubleForColumn:(id)arg1 inTable:(id)arg2;
- (_Bool)boolForColumn:(id)arg1 inTable:(id)arg2;
- (id)stringForColumn:(id)arg1 inTable:(id)arg2 whereColumn:(id)arg3 equalsValue:(id)arg4;
- (id)stringForColumn:(id)arg1 inTable:(id)arg2;
- (_Bool)isValueNullForColumn:(id)arg1 inTable:(id)arg2;
- (_Bool)executeTransaction:(CDUnknownBlockType)arg1;
- (_Bool)vacuumIfRequired;
- (double)createdTimestamp;
- (unsigned long long)databaseSize;
- (void)migrateDatabaseIfNeeded;
- (void)v2DB:(id)arg1 withQuery:(id)arg2 andRowMigration:(CDUnknownBlockType)arg3;
- (id)migrations;
- (void)migrateFromV2Database:(id)arg1;
- (void)migrateFromV2DatabaseAt:(id)arg1;
- (_Bool)initializeDatabase:(id)arg1;
- (void)prepareForOpen;
- (id)connectAndOpenNewDBWithFilePath:(id)arg1;
- (void)dealloc;
- (id)initWithLocalyticsDelegate:(id)arg1 databasePath:(id)arg2;

@end

