//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LLDBUtils : NSObject
{
}

+ (_Bool)updateDB:(id)arg1 with:(id)arg2 and:(id)arg3;
+ (id)queryDB:(id)arg1 with:(id)arg2 and:(id)arg3;
+ (id)transform:(id)arg1 with:(id)arg2;
+ (id)sanitizedTransform:(id)arg1 with:(id)arg2;

@end

