//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLInAppMsgView.h"

#import "UIWebViewDelegate.h"

@class NSString;

@interface LLInAppMsgBannerView : LLInAppMsgView <UIWebViewDelegate>
{
    _Bool _topDocked;
}

+ (id)sharedViewWithLocalyticsDelegate:(id)arg1;
@property _Bool topDocked; // @synthesize topDocked=_topDocked;
- (void)keyWindowDidChange:(id)arg1;
- (void)dismiss;
- (void)dismissWithAnimate:(_Bool)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (id)dismissButton;
- (void)positionAMPMessage:(id)arg1;
- (void)setBannerPosition;
- (struct CGSize)maxPhoneSize;
- (struct CGSize)maxTabletSize;
- (struct CGSize)targetPhoneSize;
- (struct CGSize)targetTabletSize;
- (id)overlayWindow;
- (id)webView;
- (void)layoutButton;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 andLocalyticsDelegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

