//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLInAppMsgView.h"

@interface LLInAppMsgFullScreenView : LLInAppMsgView
{
}

+ (id)sharedViewWithLocalyticsDelegate:(id)arg1;
- (void)positionAMPMessage:(id)arg1;
- (void)layoutButton;
- (id)webView;
- (id)overlayWindow;
- (id)initWithFrame:(struct CGRect)arg1 andLocalyticsDelegate:(id)arg2;

@end

