//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIWebViewDelegate.h"

@class LLCloseButton, NSDate, NSDictionary, NSString, UIWebView, UIWindow;

@interface LLInAppMsgView : UIView <UIWebViewDelegate>
{
    UIView *_ampMessageView;
    UIView *_overlayView;
    UIWindow *_overlayWindow;
    UIWebView *_webView;
    LLCloseButton *_dismissButton;
    _Bool _isVisible;
    _Bool _hasUploadedViewEvent;
    NSDictionary *_ruleDictionary;
    NSDate *_showTime;
    unsigned long long _buttonLocation;
    id <LLMessagingDelegate> _delegate;
    UIWindow *_previousKeyWindow;
    id _isShowing;
    NSDictionary *triggeringAttributes;
    id <LLLocalyticsDelegate> _localyticsDelegate;
    NSDictionary *_identifiers;
    NSDictionary *_customDimensions;
}

+ (struct CGSize)landscapeFlipIOS8:(struct CGRect)arg1;
+ (struct CGRect)screenBounds;
+ (id)sharedViewWithLocalyticsDelegate:(id)arg1;
+ (_Bool)anInAppMsgIsShowingWithLocalyticsDelegate:(id)arg1;
+ (id)inAppMsgViewForMessagePosition:(id)arg1 withLocalyticsDelegate:(id)arg2;
@property(retain, nonatomic) NSDictionary *customDimensions; // @synthesize customDimensions=_customDimensions;
@property(retain, nonatomic) NSDictionary *identifiers; // @synthesize identifiers=_identifiers;
@property(nonatomic) __weak id <LLLocalyticsDelegate> localyticsDelegate; // @synthesize localyticsDelegate=_localyticsDelegate;
@property(retain, nonatomic) NSDictionary *triggeringAttributes; // @synthesize triggeringAttributes;
@property(nonatomic) _Bool hasUploadedViewEvent; // @synthesize hasUploadedViewEvent=_hasUploadedViewEvent;
@property(nonatomic) _Bool isVisible; // @synthesize isVisible=_isVisible;
@property(retain, nonatomic) NSDate *showTime; // @synthesize showTime=_showTime;
@property(retain, nonatomic) NSDictionary *ruleDictionary; // @synthesize ruleDictionary=_ruleDictionary;
@property(retain, nonatomic) UIWindow *previousKeyWindow; // @synthesize previousKeyWindow=_previousKeyWindow;
@property(nonatomic) __weak id <LLMessagingDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) id isShowing; // @synthesize isShowing=_isShowing;
- (id)urlByAppendingQueryString:(id)arg1 url:(id)arg2;
- (id)urlWithAdvertisingInfo:(id)arg1;
- (id)javascriptFromDictionary:(id)arg1;
- (void)inlineRequiredJavascript:(id)arg1;
- (void)tagAmpActionEventWithAction:(id)arg1;
- (void)tagAmpActionForURL:(id)arg1;
- (_Bool)ampDidHandleCustomProtocolRequest:(id)arg1 shouldLoadRequest:(_Bool *)arg2;
- (_Bool)ampDidHandleLocalyticsRequest:(id)arg1 shouldLoadRequest:(_Bool *)arg2;
- (_Bool)ampDidHandleHTTPRequest:(id)arg1 shouldLoadRequest:(_Bool *)arg2;
- (_Bool)ampDidHandleLocalFileRequest:(id)arg1 shouldLoadRequest:(_Bool *)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)moveToPoint:(struct CGPoint)arg1 rotateAngle:(double)arg2;
- (void)keyWindowDidChange:(id)arg1;
- (void)positionAMPMessageNormal:(id)arg1;
- (void)positionAMPMessageScaled:(id)arg1;
- (void)positionAMPMessage:(id)arg1;
- (void)registerNotifications;
- (void)unregisterNotifications;
- (void)layoutButton;
@property(readonly, nonatomic) LLCloseButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(readonly, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (struct CGSize)scaleDownIfNecessary:(struct CGSize)arg1 bounds:(struct CGSize)arg2;
- (struct CGSize)creativeSize;
- (float)buttonDiameter;
- (struct CGSize)maxPhoneSize;
- (struct CGSize)maxTabletSize;
- (struct CGSize)targetPhoneSize;
- (struct CGSize)targetTabletSize;
@property(readonly, nonatomic) UIView *ampMessageView; // @synthesize ampMessageView=_ampMessageView;
@property(readonly, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(readonly, nonatomic) UIWindow *overlayWindow; // @synthesize overlayWindow=_overlayWindow;
- (void)dismiss:(_Bool)arg1;
- (void)dismiss;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)showWithDictionary:(id)arg1 identifiers:(id)arg2 customDimensions:(id)arg3 buttonImage:(id)arg4 buttonLocation:(unsigned long long)arg5;
- (id)initWithFrame:(struct CGRect)arg1 andLocalyticsDelegate:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

