//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLManagerBase.h"

#import "LLAnalyticsDelegate.h"
#import "LLDownloaderDataDestination.h"
#import "LLMessagingDelegate.h"

@class LLMarketingDB, LLMarketingDownloader, NSString, UIAlertView, UIImage;

@interface LLInAppManager : LLManagerBase <LLAnalyticsDelegate, LLMessagingDelegate, LLDownloaderDataDestination>
{
    _Bool _requestPushTestOnBackgrounded;
    unsigned long long _inAppMessageDismissButtonLocation;
    UIImage *_dismissButtonImage;
    LLMarketingDB *_db;
    LLMarketingDownloader *_networkHandler;
    CDUnknownBlockType _startSessionBlock;
    NSString *_pushTestModeCampaignId;
    NSString *_pushTestModeCreativeId;
    UIAlertView *_pushTestModeAlertView;
    NSString *_appKey;
    NSString *_installId;
}

+ (id)zipFilePathForRuleId:(long long)arg1;
+ (id)inAppMsgDataDirectory;
+ (_Bool)ampRulePointsToZip:(id)arg1;
+ (_Bool)downloadAndSaveZipForAmpRule:(id)arg1 destination:(id)arg2;
+ (id)URLForAmpRule:(id)arg1;
+ (_Bool)shouldUseTabletCreative:(id)arg1;
@property(readonly, copy, nonatomic) NSString *installId; // @synthesize installId=_installId;
@property(readonly, copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) UIAlertView *pushTestModeAlertView; // @synthesize pushTestModeAlertView=_pushTestModeAlertView;
@property(copy, nonatomic) NSString *pushTestModeCreativeId; // @synthesize pushTestModeCreativeId=_pushTestModeCreativeId;
@property(copy, nonatomic) NSString *pushTestModeCampaignId; // @synthesize pushTestModeCampaignId=_pushTestModeCampaignId;
@property(nonatomic) _Bool requestPushTestOnBackgrounded; // @synthesize requestPushTestOnBackgrounded=_requestPushTestOnBackgrounded;
@property(copy) CDUnknownBlockType startSessionBlock; // @synthesize startSessionBlock=_startSessionBlock;
@property(retain, nonatomic) LLMarketingDownloader *networkHandler; // @synthesize networkHandler=_networkHandler;
@property(retain, nonatomic) LLMarketingDB *db; // @synthesize db=_db;
@property(nonatomic) unsigned long long inAppMessageDismissButtonLocation; // @synthesize inAppMessageDismissButtonLocation=_inAppMessageDismissButtonLocation;
- (void).cxx_destruct;
- (void)downloadDidCompleteWithResponseData:(id)arg1;
- (void)setInAppDismissButtonLocation:(unsigned long long)arg1;
@property(retain, nonatomic) UIImage *dismissButtonImage; // @synthesize dismissButtonImage=_dismissButtonImage;
- (void)setDismissButtonImageWithName:(id)arg1;
- (void)localyticsDidDismissInAppMessage;
- (void)localyticsWillDismissInAppMessage;
- (void)localyticsDidDisplayInAppMessage;
- (void)localyticsWillDisplayInAppMessage;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (void)requestPushTest;
- (_Bool)handleURL:(id)arg1;
- (_Bool)decompressZipDataForRule:(id)arg1 withId:(long long)arg2;
- (id)downloadInAppMsgDataForRule:(id)arg1 error:(id *)arg2;
- (void)showInAppMsgForMessage:(id)arg1 withTriggeringAttributes:(id)arg2 setDidDisplay:(_Bool)arg3;
- (void)showInAppMsgForMessage:(id)arg1;
- (id)conditionsForAmpCampaign:(id)arg1;
- (_Bool)ampMessageSatisfiesConditions:(id)arg1 attributes:(id)arg2;
- (void)handleRemoteNotification:(id)arg1;
- (id)ampMessageDictionaryForResults:(id)arg1;
- (id)ampMessageDictionaryForEvent:(id)arg1;
- (id)ampMessageDictionaryForRuleId:(unsigned long long)arg1;
- (id)fetchInAppMsgHTMLForRule:(id)arg1;
- (void)dismissCurrentInAppMessage;
- (void)triggerInAppMsgWithRuleId:(unsigned long long)arg1;
- (void)triggerInAppMsgWithEvent:(id)arg1 andAttributes:(id)arg2;
- (void)triggerInAppMsgWithEvent:(id)arg1;
- (id)fetchAMPRules;
- (void)refreshInAppMessages;
- (void)localyticsDidTagEvent:(id)arg1 attributes:(id)arg2 customerValueIncrease:(id)arg3;
- (void)localyticsSessionDidOpen:(_Bool)arg1 isUpgrade:(_Bool)arg2 isResume:(_Bool)arg3;
- (void)downloadWithCustomerId:(id)arg1;
- (void)prepare;
@property _Bool testModeEnabled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

