//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSData, NSDictionary, NSNumber, NSObject<OS_dispatch_group>, NSString, NSURL;

@protocol LLLocalyticsDelegate <NSObject>
@property(readonly) NSString *libraryVersion;
@property(readonly) NSString *installId;
@property(readonly, nonatomic) long long lastState;
@property(readonly, nonatomic) NSObject<OS_dispatch_group> *dispatchGroupCritical;
@property(getter=isHttpsEnabled) _Bool httpsEnabled;
@property _Bool useSandbox;
@property(readonly) NSString *profilesHost;
@property(readonly) NSString *analyticsHost;
@property(readonly) NSString *messagingHost;
@property(readonly) NSString *appKey;
- (void)setValue:(NSString *)arg1 forCustomDimension:(unsigned long long)arg2;
- (void)tagEvent:(NSString *)arg1 attributes:(NSDictionary *)arg2 customerValueIncrease:(NSNumber *)arg3;
- (void)tagEvent:(NSString *)arg1 attributes:(NSDictionary *)arg2;
- (void)tagEvent:(NSString *)arg1;
- (void)handlePushNotificationOpened:(NSDictionary *)arg1;
- (void)setPushToken:(NSData *)arg1;
- (NSString *)pushToken;
- (_Bool)handleTestModeURL:(NSURL *)arg1;
- (void)dismissCurrentInAppMessage;
- (void)upload;
- (void)closeSession;
- (void)openSession;
- (_Bool)isOptedOut;
- (void)setLoggingEnabled:(_Bool)arg1;
- (_Bool)isTestModeEnabled;
- (NSString *)customerIdInMemory;
- (NSArray *)fetchAMPRules;
- (void)refreshInAppMessages;
- (void)triggerInAppMessageWithRuleId:(unsigned long long)arg1;
- (double)lastSessionStartTimestamp;
- (unsigned long long)sessionNumber;
- (NSDictionary *)customDimensions;
- (NSDictionary *)identifiers;
- (NSString *)localyticsCacheDirectoryPath;
- (NSString *)localyticsDirectoryPath;
@end

