//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LLDBBase, LLNetworkHandlerBase, NSHashTable, NSObject<OS_dispatch_queue>;

@interface LLManagerBase : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSHashTable *_delegates;
    NSObject<OS_dispatch_queue> *_globalQueue;
    id <LLLocalyticsDelegate> _localyticsDelegate;
}

@property(nonatomic) __weak id <LLLocalyticsDelegate> localyticsDelegate; // @synthesize localyticsDelegate=_localyticsDelegate;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *globalQueue; // @synthesize globalQueue=_globalQueue;
@property(retain, nonatomic) NSHashTable *delegates; // @synthesize delegates=_delegates;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (id)databasePathForName:(id)arg1 directoryPath:(id)arg2;
- (_Bool)onManagerQueue;
- (void)callDelegatesWithBlock:(CDUnknownBlockType)arg1;
- (void)syncExecuteBlock:(CDUnknownBlockType)arg1;
- (void)asyncExecuteCriticalBlock:(CDUnknownBlockType)arg1;
- (void)asyncExecuteBlock:(CDUnknownBlockType)arg1;
- (void)prepare;
- (void)cancelCriticalTasks;
- (void)drainQueue;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(retain, nonatomic) LLDBBase *db; // @dynamic db;
@property(retain, nonatomic) LLNetworkHandlerBase *networkHandler; // @dynamic networkHandler;

@end

