//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLNetworkHandlerBase.h"

@interface LLMarketingDownloader : LLNetworkHandlerBase
{
    id <LLDownloaderDataDestination> _dataDestination;
}

@property(nonatomic) __weak id <LLDownloaderDataDestination> dataDestination; // @synthesize dataDestination=_dataDestination;
- (void).cxx_destruct;
- (id)createRequestWithURL:(id)arg1 installId:(id)arg2 libraryVersion:(id)arg3 customerId:(id)arg4;
- (void)beginDownloadWithApplicationKey:(id)arg1 installId:(id)arg2 libraryVersion:(id)arg3 customerId:(id)arg4;
- (id)initWithDataSource:(id)arg1 queue:(id)arg2 andLocalyticsDelegate:(id)arg3;

@end

