//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface LLMarketingTuple : NSObject
{
    _Bool _didDisplay;
    _Bool _internet_required;
    unsigned long long _ruleId;
    unsigned long long _campaignId;
    NSString *_ruleName;
    long long _version;
    NSString *_phoneLocation;
    NSDictionary *_phoneSize;
    long long _phoneSizeWidth;
    long long _phoneSizeHeight;
    NSString *_tabletLocation;
    NSDictionary *_tabletSize;
    long long _tabletSizeWidth;
    long long _tabletSizeHeight;
    unsigned long long _expiration;
    unsigned long long _ttlExpiration;
    unsigned long long _updateOnTTLExpiration;
    long long _displaySeconds;
    long long _displaySession;
    long long _times_to_display;
    NSString *_location;
    NSString *_ab_test;
    NSString *_devices;
}

+ (_Bool)validMarketingMessage:(id)arg1 testModeEnabled:(_Bool)arg2;
@property(copy, nonatomic) NSString *devices; // @synthesize devices=_devices;
@property(copy, nonatomic) NSString *ab_test; // @synthesize ab_test=_ab_test;
@property(copy, nonatomic) NSString *location; // @synthesize location=_location;
@property(nonatomic) _Bool internet_required; // @synthesize internet_required=_internet_required;
@property(nonatomic) long long times_to_display; // @synthesize times_to_display=_times_to_display;
@property(nonatomic) _Bool didDisplay; // @synthesize didDisplay=_didDisplay;
@property(nonatomic) long long displaySession; // @synthesize displaySession=_displaySession;
@property(nonatomic) long long displaySeconds; // @synthesize displaySeconds=_displaySeconds;
@property(nonatomic) unsigned long long updateOnTTLExpiration; // @synthesize updateOnTTLExpiration=_updateOnTTLExpiration;
@property(nonatomic) unsigned long long ttlExpiration; // @synthesize ttlExpiration=_ttlExpiration;
@property(nonatomic) unsigned long long expiration; // @synthesize expiration=_expiration;
@property(nonatomic) long long tabletSizeHeight; // @synthesize tabletSizeHeight=_tabletSizeHeight;
@property(nonatomic) long long tabletSizeWidth; // @synthesize tabletSizeWidth=_tabletSizeWidth;
@property(retain, nonatomic) NSDictionary *tabletSize; // @synthesize tabletSize=_tabletSize;
@property(copy, nonatomic) NSString *tabletLocation; // @synthesize tabletLocation=_tabletLocation;
@property(nonatomic) long long phoneSizeHeight; // @synthesize phoneSizeHeight=_phoneSizeHeight;
@property(nonatomic) long long phoneSizeWidth; // @synthesize phoneSizeWidth=_phoneSizeWidth;
@property(retain, nonatomic) NSDictionary *phoneSize; // @synthesize phoneSize=_phoneSize;
@property(copy, nonatomic) NSString *phoneLocation; // @synthesize phoneLocation=_phoneLocation;
@property(nonatomic) long long version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *ruleName; // @synthesize ruleName=_ruleName;
@property(nonatomic) unsigned long long campaignId; // @synthesize campaignId=_campaignId;
@property(nonatomic) unsigned long long ruleId; // @synthesize ruleId=_ruleId;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

