//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLDBBase.h"

#import "LLDownloaderDataDestination.h"

@class NSString;

@interface LLMarketingDB : LLDBBase <LLDownloaderDataDestination>
{
}

- (void)removeCampaignZipForRuleId:(long long)arg1;
- (void)removeOldCampaigns:(id)arg1;
- (void)saveInAppMarketingMessage:(id)arg1;
- (void)saveInAppMarketingData:(id)arg1;
- (void)downloadDidCompleteWithResponseData:(id)arg1;
- (_Bool)dropDatabase;
- (long long)campaignIdFrom:(id)arg1;
- (_Bool)deleteAMPRuleIds:(id)arg1 fromTable:(id)arg2;
- (_Bool)deleteAMPRuleIds:(id)arg1;
- (id)campaignIdToCampaignTupleTable;
- (void)saveAMPConditions:(id)arg1 forCampaignId:(unsigned long long)arg2;
- (_Bool)saveAMPConditionValues:(id)arg1 forConditionId:(unsigned long long)arg2;
- (void)saveAMPCondition:(id)arg1 forRuleId:(unsigned long long)arg2;
- (id)conditionsForRuleId:(unsigned long long)arg1;
- (_Bool)setDidDisplayForAMPRuleId:(long long)arg1;
- (id)fetchAMPRules;
- (id)retrieveMessageForResultSet:(id)arg1;
- (id)fetchAMPRulesForEvent:(id)arg1;
- (id)fetchAMPRulesForRuleId:(unsigned long long)arg1;
- (void)saveAMPEventName:(id)arg1 toRuleId:(long long)arg2;
- (long long)saveAMPMessage:(id)arg1;
- (id)ruleTupleWithCampaignId:(unsigned long long)arg1;
- (long long)ruleIdWithCampaignId:(unsigned long long)arg1;
- (void)migrateFromV2Database:(id)arg1;
- (_Bool)initializeDatabase:(id)arg1;
- (id)initWithLocalyticsDelegate:(id)arg1;
- (id)migrations;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

