//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LLDelayedBlockHandle, LLURLConnection, NSObject<OS_dispatch_queue>;

@interface LLNetworkHandlerBase : NSObject
{
    id <LLLocalyticsDelegate> _localyticsDelegate;
    LLURLConnection *_currentConnection;
    NSObject<OS_dispatch_queue> *_queue;
    unsigned long long _retryCount;
    LLDelayedBlockHandle *_pendingRetryBlockHandle;
}

+ (id)timeStamp;
@property(retain, nonatomic) LLDelayedBlockHandle *pendingRetryBlockHandle; // @synthesize pendingRetryBlockHandle=_pendingRetryBlockHandle;
@property(nonatomic) unsigned long long retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) LLURLConnection *currentConnection; // @synthesize currentConnection=_currentConnection;
@property(nonatomic) __weak id <LLLocalyticsDelegate> localyticsDelegate; // @synthesize localyticsDelegate=_localyticsDelegate;
- (void).cxx_destruct;
- (_Bool)hasExceededMaxRetries;
- (void)asyncURLRequest:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (id)createRequestWithURL:(id)arg1 installId:(id)arg2 libraryVersion:(id)arg3 customerId:(id)arg4;
- (void)cancelPendingRetry;
- (void)cancelTransfer;
- (id)initWithQueue:(id)arg1 andLocalyticsDelegate:(id)arg2;

@end

