//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLManagerBase.h"

@class LLProfilesDB, LLProfilesUploader, NSString;

@interface LLProfilesManager : LLManagerBase
{
    _Bool _scopeProfilesToOrg;
    LLProfilesDB *_db;
    LLProfilesUploader *_networkHandler;
    NSString *_appKey;
    NSString *_installId;
}

+ (id)normalizeProfileValue:(id)arg1;
+ (_Bool)isValidProfileValueType:(id)arg1;
@property(readonly, copy, nonatomic) NSString *installId; // @synthesize installId=_installId;
@property(readonly, copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(retain, nonatomic) LLProfilesUploader *networkHandler; // @synthesize networkHandler=_networkHandler;
@property(retain, nonatomic) LLProfilesDB *db; // @synthesize db=_db;
- (void).cxx_destruct;
- (void)uploadWithCustomerId:(id)arg1;
- (void)addProfileChange:(id)arg1 value:(id)arg2 forAttribute:(id)arg3 withScope:(long long)arg4 customerId:(id)arg5;
- (void)addProfileChange:(id)arg1 value:(id)arg2 forAttribute:(id)arg3 withScope:(long long)arg4;
- (void)deleteProfileAttribute:(id)arg1 withScope:(long long)arg2;
- (void)incrementValueBy:(long long)arg1 forProfileAttribute:(id)arg2 withScope:(long long)arg3;
- (void)removeValues:(id)arg1 fromSetForProfileAttribute:(id)arg2 withScope:(long long)arg3;
- (void)addValues:(id)arg1 toSetForProfileAttribute:(id)arg2 withScope:(long long)arg3;
- (void)setValue:(id)arg1 forProfileAttribute:(id)arg2 withScope:(long long)arg3;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (void)prepare;
@property(nonatomic) _Bool scopeProfilesToOrg; // @synthesize scopeProfilesToOrg=_scopeProfilesToOrg;

@end

