//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface LLProfileEventTuple : NSObject
{
    long long _elementId;
    NSData *_value;
    NSString *_customer_id;
    long long _scope;
}

+ (id)profileEventTupleFromDictionary:(id)arg1;
+ (id)profileEventTupleFromValue:(id)arg1 customerId:(id)arg2 andScope:(long long)arg3;
@property(nonatomic) long long scope; // @synthesize scope=_scope;
@property(copy, nonatomic) NSString *customer_id; // @synthesize customer_id=_customer_id;
@property(retain, nonatomic) NSData *value; // @synthesize value=_value;
@property(nonatomic) long long elementId; // @synthesize elementId=_elementId;
- (void).cxx_destruct;
- (id)initFromDictionary:(id)arg1;
- (id)initWithValue:(id)arg1 customerId:(id)arg2 andScope:(long long)arg3;
- (id)initWithId:(long long)arg1 value:(id)arg2 customerId:(id)arg3 andScope:(long long)arg4;

@end

