//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LLProxySelectorPair : NSObject
{
    SEL _oldSelector;
    SEL _newSelector;
}

+ (id)pairWithOldSelector:(SEL)arg1 newSelector:(SEL)arg2;
@property(nonatomic) SEL newSelector; // @synthesize newSelector=_newSelector;
@property(nonatomic) SEL oldSelector; // @synthesize oldSelector=_oldSelector;
- (_Bool)oldOrNewMethodImplementedByObject:(id)arg1;
- (_Bool)containsSelector:(SEL)arg1;

@end

