//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLDBBase.h"

#import "LLUploaderDataSource.h"

@class NSString;

@interface LLProfilesDB : LLDBBase <LLUploaderDataSource>
{
}

- (unsigned long long)greatestDatapointId;
- (id)getUploadDataWithMaxId:(unsigned long long)arg1;
- (void)fullUploadDidFinish;
- (void)uploadBatchDidCompleteWithHighestUploadNumber:(unsigned long long)arg1;
- (long long)profileEventCount;
- (_Bool)deleteProfileEventTuple:(id)arg1;
- (id)getNextProfileEventTuples:(unsigned long long)arg1;
- (id)getNextProfileEventTuple;
- (_Bool)queueProfileEventTuple:(id)arg1;
- (void)migrateFromV2Database:(id)arg1;
- (_Bool)initializeDatabase:(id)arg1;
- (id)initWithLocalyticsDelegate:(id)arg1 databasePath:(id)arg2;
- (id)migrations;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

