//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLNetworkHandlerBase.h"

@interface LLUploaderBase : LLNetworkHandlerBase
{
    id <LLUploaderDataSource> _dataSource;
    unsigned long long _uploadHighWaterMark;
}

@property(nonatomic) unsigned long long uploadHighWaterMark; // @synthesize uploadHighWaterMark=_uploadHighWaterMark;
@property(nonatomic) __weak id <LLUploaderDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)asyncURLRequest:(id)arg1 withUploadNumber:(unsigned long long)arg2 CompletionBlock:(CDUnknownBlockType)arg3;
- (void)uploadData:(id)arg1 withApplicationKey:(id)arg2 installId:(id)arg3 libraryVersion:(id)arg4 customerId:(id)arg5;
- (id)createRequestWithURL:(id)arg1 installId:(id)arg2 libraryVersion:(id)arg3 customerId:(id)arg4 uploadData:(id)arg5;
- (void)beginUploadWithApplicationKey:(id)arg1 installId:(id)arg2 libraryVersion:(id)arg3 customerId:(id)arg4 shouldUpdateHighWaterMark:(_Bool)arg5;
- (id)initWithDataSource:(id)arg1 queue:(id)arg2 andLocalyticsDelegate:(id)arg3;

@end

