//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class NSMutableData, NSObject<OS_dispatch_queue>, NSOperationQueue, NSString, NSURLConnection, NSURLResponse;

@interface LLURLConnection : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    NSURLConnection *_urlConnection;
    NSMutableData *_receivedData;
    CDUnknownBlockType _completionHandler;
    NSObject<OS_dispatch_queue> *_completionCallbackQueue;
    NSOperationQueue *_delegateCallbackQueue;
    NSURLResponse *_receivedResponse;
}

+ (id)asynchronousConnectionWithRequest:(id)arg1 queue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) NSURLResponse *receivedResponse; // @synthesize receivedResponse=_receivedResponse;
@property(retain, nonatomic) NSOperationQueue *delegateCallbackQueue; // @synthesize delegateCallbackQueue=_delegateCallbackQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *completionCallbackQueue; // @synthesize completionCallbackQueue=_completionCallbackQueue;
@property(copy) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(retain) NSURLConnection *urlConnection; // @synthesize urlConnection=_urlConnection;
- (void).cxx_destruct;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)endConnection;
- (_Bool)beginConnectionWithRequest:(id)arg1;
- (void)cancel;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

