//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LLUtil : NSObject
{
}

+ (void)localyticsLogAssertionFailureInMethod:(SEL)arg1 object:(id)arg2 file:(id)arg3 lineNumber:(unsigned long long)arg4 description:(id)arg5;
+ (id)dictFromJSON:(id)arg1;
+ (id)safeListFromDictionary:(id)arg1 forKey:(id)arg2;
+ (id)safeDictionaryFromDictionary:(id)arg1 forKey:(id)arg2;
+ (id)safeStringValueFromDictionary:(id)arg1 forKey:(id)arg2;
+ (long long)safeIntegerValueFromDictionary:(id)arg1 forKey:(id)arg2;
+ (void)exceptionCatchBlockCall:(CDUnknownBlockType)arg1 withFailureName:(id)arg2;
+ (id)escapeString:(id)arg1;
+ (id)formatAttributeWithName:(id)arg1 value:(id)arg2 first:(_Bool)arg3;
+ (id)formatAttributeWithName:(id)arg1 value:(id)arg2;
+ (_Bool)isIOS8ScreenScaled;
+ (_Bool)isUIKitIOS8;
+ (id)deviceName;
+ (id)objectForSelector:(SEL)arg1 performedOnTarget:(id)arg2;
+ (id)invocationForSelector:(SEL)arg1 target:(id)arg2;
+ (id)md5HashForFileWithPath:(id)arg1;
+ (id)randomUUID;
+ (id)valueFromQueryStringKey:(id)arg1 url:(id)arg2;
+ (_Bool)advertisingIdentifierEnabled;
+ (void)setAdvertisingIdentifierEnabled:(_Bool)arg1;
+ (_Bool)loggingEnabled;
+ (void)setLoggingEnabled:(_Bool)arg1;
+ (void)logMessage:(id)arg1;

@end

