//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Localytics : NSObject
{
}

+ (_Bool)handleWatchKitExtensionRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;
+ (id)methodSignatureForSelector:(SEL)arg1;
+ (_Bool)localyticsDelegateRespondsToSelector:(SEL)arg1;
+ (void)forwardInvocation:(id)arg1;

@end

