//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MFMailComposeViewController.h"

@interface MFMailComposeViewController (BlocksKit)
+ (void)load;

// Remaining properties
@property(copy, nonatomic, setter=bk_setCompletionBlock:) CDUnknownBlockType bk_completionBlock; // @dynamic bk_completionBlock;
@end

