//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLJSONAdapter.h"

@interface MTLJSONAdapter (Deprecated)
+ (id)modelOfClass:(Class)arg1 fromJSONDictionary:(id)arg2;
- (id)initWithJSONDictionary:(id)arg1 modelClass:(Class)arg2;
@end

