//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSException.h"

@interface NSException (TBStateMachine)
+ (id)tb_noSerialQueueException:(id)arg1;
+ (id)tb_noOutgoingJunctionPathException:(id)arg1;
+ (id)tb_ambiguousCompoundTransitionAttributes:(id)arg1;
+ (id)tb_ambiguousTransitionAttributes:(id)arg1 source:(id)arg2 target:(id)arg3;
+ (id)tb_noLcaForTransition:(id)arg1;
+ (id)tb_missingStateMachineException:(id)arg1;
+ (id)tb_notAStateMachineException:(id)arg1;
+ (id)tb_noNameForEventException;
+ (id)tb_noNameForPseudoStateException;
+ (id)tb_noNameForStateException;
+ (id)tb_noInitialStateException:(id)arg1;
+ (id)tb_nonExistingStateException:(id)arg1;
+ (id)tb_notOfTypeStateException:(id)arg1;
@end

