//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (BeMe)
+ (id)jpgExtension;
+ (id)mp4Extension;
+ (id)movExtension;
+ (id)uniqueFileNameWithExtension:(id)arg1;
+ (id)uniqueFileURLAtFileDirectoryURL:(id)arg1 withFileName:(id)arg2;
+ (id)urlForFileInDirectory:(id)arg1 withFileName:(id)arg2;
+ (id)urlForFileInImageCachesDirectoryWithFileName:(id)arg1;
+ (id)urlForFileInVideoCachesDirectoryWithFileName:(id)arg1;
+ (id)urlForFileInVideoTempDirectoryWithFileName:(id)arg1;
+ (id)imageSubPath;
+ (id)videoSubPath;
+ (_Bool)confirmPathOrCreate:(id)arg1;
+ (_Bool)cleanDirectoryPathURL:(id)arg1;
+ (id)supportDirectoryForURLAtSubpath:(id)arg1;
+ (id)supportDirectoryForImageURL;
+ (id)supportDirectoryForVideoURL;
+ (id)tempDirectoryForImageURL;
+ (id)tempDirectoryForVideoURL;
+ (id)uniqueURLWithJPGExtension;
+ (id)uniqueFileNameWithJPGExtension;
+ (id)uniqueURLWithMP4Extension;
+ (id)uniqueFileNameWithMP4Extension;
+ (id)uniqueURLWithMOVExtension;
+ (id)uniqueFileNameWithMOVExtension;
+ (void)cleanCachesDirectoryForVideo;
+ (void)cleanTempDirectoryForVideo;
+ (_Bool)isURLactualFile:(id)arg1;
+ (id)URLForBeMeImageWithFileName:(id)arg1;
+ (id)URLForBeMeVideoWithFileName:(id)arg1;
@end

