//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (Beme)
+ (id)_beme_uniqueFileNameWithExtension:(id)arg1;
+ (id)_beme_uniqueFileURLAtFileDirectoryURL:(id)arg1 withFileName:(id)arg2;
+ (id)_beme_urlForFileInDirectory:(id)arg1 withFileName:(id)arg2;
+ (id)_beme_urlForFileInVideoCachesDirectoryWithFileName:(id)arg1;
+ (id)_beme_imageSubPath;
+ (id)_beme_videoSubPath;
+ (_Bool)_beme_confirmPathOrCreate:(id)arg1;
+ (_Bool)_beme_cleanDirectoryPathURL:(id)arg1;
+ (id)_beme_supportDirectoryForURLAtSubpath:(id)arg1;
+ (id)_beme_supportDirectoryForImageURL;
+ (id)beme_supportDirectoryForVideoURL;
+ (id)beme_uniqueURLWithJPGExtension;
+ (id)beme_uniqueFileNameWithJPGExtension;
+ (id)beme_uniqueURLWithMP4Extension;
+ (id)beme_uniqueFileNameWithMP4Extension;
+ (id)beme_uniqueURLWithMOVExtension;
+ (id)beme_uniqueFileNameWithMOVExtension;
+ (void)beme_cleanCachesDirectoryForVideo;
+ (_Bool)_beme_isURLactualFile:(id)arg1;
+ (id)beme_URLForVideoWithFileName:(id)arg1;
@end

