//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValue.h"

@interface NSValue (NSValueADDCornerInsetExtensions)
+ (id)valueWithADDCornerInset:(struct __ADDCornerInset)arg1;
- (struct __ADDCornerInset)ADDCornerInsetValue;
@end

