//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OMGHTTPURLRQ : NSObject
{
}

+ (id)DELETE:(id)arg1:(id)arg2;
+ (id)PUT:(id)arg1 JSON:(id)arg2;
+ (id)PUT:(id)arg1:(id)arg2;
+ (id)POST:(id)arg1 JSON:(id)arg2;
+ (id)POST:(id)arg1:(id)arg2;
+ (id)GET:(id)arg1:(id)arg2;

@end

