//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPRequestOperationManager.h"

@class NSManagedObjectContext;

@interface OVCHTTPRequestOperationManager : AFHTTPRequestOperationManager
{
    NSManagedObjectContext *_managedObjectContext;
    NSManagedObjectContext *_backgroundContext;
    id _contextObserver;
}

+ (id)responseClassesByResourcePath;
+ (id)modelClassesByResourcePath;
+ (Class)errorModelClass;
+ (Class)responseClass;
@property(retain, nonatomic) id contextObserver; // @synthesize contextObserver=_contextObserver;
@property(retain, nonatomic) NSManagedObjectContext *backgroundContext; // @synthesize backgroundContext=_backgroundContext;
@property(readonly, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
- (void).cxx_destruct;
- (void)setupBackgroundContext;
- (void)setupResponseSerializer;
- (id)DELETE:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)PATCH:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)PUT:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)POST:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (id)POST:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)HEAD:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)GET:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)cancelAllRequests;
- (id)initWithBaseURL:(id)arg1 managedObjectContext:(id)arg2;
- (id)initWithBaseURL:(id)arg1;
- (void)dealloc;

@end

