//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFJSONResponseSerializer.h"

@class NSManagedObjectContext, OVCURLMatcher;

@interface OVCModelResponseSerializer : AFJSONResponseSerializer
{
    OVCURLMatcher *_URLMatcher;
    OVCURLMatcher *_URLResponseClassMatcher;
    NSManagedObjectContext *_managedObjectContext;
    Class _responseClass;
    Class _errorModelClass;
}

+ (id)serializerWithURLMatcher:(id)arg1 responseClassURLMatcher:(id)arg2 managedObjectContext:(id)arg3 responseClass:(Class)arg4 errorModelClass:(Class)arg5;
@property(retain, nonatomic) Class errorModelClass; // @synthesize errorModelClass=_errorModelClass;
@property(retain, nonatomic) Class responseClass; // @synthesize responseClass=_responseClass;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(retain, nonatomic) OVCURLMatcher *URLResponseClassMatcher; // @synthesize URLResponseClassMatcher=_URLResponseClassMatcher;
@property(retain, nonatomic) OVCURLMatcher *URLMatcher; // @synthesize URLMatcher=_URLMatcher;
- (void).cxx_destruct;
- (void)saveResult:(id)arg1;
- (id)responseObjectForResponse:(id)arg1 data:(id)arg2 error:(id *)arg3;

@end

