//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSManagedObjectModel, NSPersistentStoreCoordinator, NSString;

@interface OVCManagedStore : NSObject
{
    NSPersistentStoreCoordinator *_persistentStoreCoordinator;
    NSManagedObjectModel *_managedObjectModel;
    NSString *_path;
}

+ (id)managedStoreWithCacheName:(id)arg1;
+ (id)temporaryManagedStore;
+ (id)managedStoreWithModel:(id)arg1;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(retain, nonatomic) NSManagedObjectModel *managedObjectModel; // @synthesize managedObjectModel=_managedObjectModel;
@property(retain, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator; // @synthesize persistentStoreCoordinator=_persistentStoreCoordinator;
- (void).cxx_destruct;
- (id)initWithPath:(id)arg1 managedObjectModel:(id)arg2;
- (id)init;

@end

