//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface OVCURLMatcher : NSObject
{
    NSString *_basePath;
    long long _type;
    NSString *_text;
    Class _modelClass;
    NSMutableArray *_children;
}

@property(retain, nonatomic) NSMutableArray *children; // @synthesize children=_children;
@property(retain, nonatomic) Class modelClass; // @synthesize modelClass=_modelClass;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *basePath; // @synthesize basePath=_basePath;
- (void).cxx_destruct;
- (void)addModelClass:(Class)arg1 forPath:(id)arg2;
- (id)description;
- (Class)modelClassForURL:(id)arg1;
- (id)initWithBasePath:(id)arg1 modelClassesByPath:(id)arg2;
- (id)init;

@end

