//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BMSnakeProgressView, UIScrollView;

@interface SVPullToRefreshView : UIView
{
    _Bool _wasTriggeredByUser;
    _Bool _showsPullToRefresh;
    _Bool _isObserving;
    unsigned long long _state;
    unsigned long long _position;
    CDUnknownBlockType _pullToRefreshActionHandler;
    BMSnakeProgressView *_snakeProgressView;
    UIScrollView *_scrollView;
    double _originalTopInset;
    double _originalBottomInset;
}

@property(nonatomic) _Bool isObserving; // @synthesize isObserving=_isObserving;
@property(nonatomic) _Bool showsPullToRefresh; // @synthesize showsPullToRefresh=_showsPullToRefresh;
@property(nonatomic) _Bool wasTriggeredByUser; // @synthesize wasTriggeredByUser=_wasTriggeredByUser;
@property(nonatomic) double originalBottomInset; // @synthesize originalBottomInset=_originalBottomInset;
@property(nonatomic) double originalTopInset; // @synthesize originalTopInset=_originalTopInset;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) BMSnakeProgressView *snakeProgressView; // @synthesize snakeProgressView=_snakeProgressView;
@property(copy, nonatomic) CDUnknownBlockType pullToRefreshActionHandler; // @synthesize pullToRefreshActionHandler=_pullToRefreshActionHandler;
@property(nonatomic) unsigned long long position; // @synthesize position=_position;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)stopAnimating;
- (void)startAnimating;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)scrollViewDidScroll:(struct CGPoint)arg1;
- (struct CGPoint)indicatorCenterWithScrollViewContentOffset:(struct CGPoint)arg1;
- (void)setScrollViewContentInset:(struct UIEdgeInsets)arg1;
- (void)setScrollViewContentInsetForLoading;
- (void)resetScrollViewContentInset;
- (void)layoutSubviews;
- (void)willMoveToSuperview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

