//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TBSMState;

@interface TBSMJunctionPath : NSObject
{
    TBSMState *_targetState;
    CDUnknownBlockType _action;
    CDUnknownBlockType _guard;
}

@property(copy, nonatomic) CDUnknownBlockType guard; // @synthesize guard=_guard;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(retain, nonatomic) TBSMState *targetState; // @synthesize targetState=_targetState;
- (void).cxx_destruct;

@end

