//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSMTransition.h"

@class TBSMPseudoState;

@interface TBSMCompoundTransition : TBSMTransition
{
    TBSMPseudoState *_targetPseudoState;
}

+ (id)compoundTransitionWithSourceState:(id)arg1 targetPseudoState:(id)arg2 action:(CDUnknownBlockType)arg3 guard:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) TBSMPseudoState *targetPseudoState; // @synthesize targetPseudoState=_targetPseudoState;
- (void).cxx_destruct;
- (void)_validatePseudoState:(id)arg1 states:(id)arg2 region:(id)arg3;
- (void)_performJunctionTransitionWithData:(id)arg1;
- (void)_performJoinTransitionWithData:(id)arg1;
- (void)_performForkTransitionWithData:(id)arg1;
- (_Bool)performTransitionWithData:(id)arg1;
- (id)name;
- (id)initWithSourceState:(id)arg1 targetPseudoState:(id)arg2 action:(CDUnknownBlockType)arg3 guard:(CDUnknownBlockType)arg4;

@end

