//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TBSMEventHandler : NSObject
{
    NSString *_name;
    id <TBSMTransitionVertex> _target;
    unsigned long long _kind;
    CDUnknownBlockType _action;
    CDUnknownBlockType _guard;
}

+ (id)eventHandlerWithName:(id)arg1 target:(id)arg2 kind:(unsigned long long)arg3 action:(CDUnknownBlockType)arg4 guard:(CDUnknownBlockType)arg5;
@property(copy, nonatomic) CDUnknownBlockType guard; // @synthesize guard=_guard;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(nonatomic) unsigned long long kind; // @synthesize kind=_kind;
@property(retain, nonatomic) id <TBSMTransitionVertex> target; // @synthesize target=_target;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1 target:(id)arg2 kind:(unsigned long long)arg3 action:(CDUnknownBlockType)arg4 guard:(CDUnknownBlockType)arg5;

@end

