//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TBSMContainingNode.h"

@class NSMutableDictionary, NSOperationQueue, NSString, TBSMState;

@interface TBSMStateMachine : NSObject <TBSMContainingNode>
{
    NSOperationQueue *_scheduledEventsQueue;
    TBSMState *_initialState;
    TBSMState *_currentState;
    NSString *_name;
    id <TBSMNode> _parentNode;
    NSMutableDictionary *_priv_states;
}

+ (id)stateMachineWithName:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *priv_states; // @synthesize priv_states=_priv_states;
@property(nonatomic) __weak id <TBSMNode> parentNode; // @synthesize parentNode=_parentNode;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) TBSMState *currentState; // @synthesize currentState=_currentState;
@property(retain, nonatomic) TBSMState *initialState; // @synthesize initialState=_initialState;
@property(retain, nonatomic) NSOperationQueue *scheduledEventsQueue; // @synthesize scheduledEventsQueue=_scheduledEventsQueue;
- (void).cxx_destruct;
- (id)path;
- (void)exit:(id)arg1 targetState:(id)arg2 data:(id)arg3;
- (void)enter:(id)arg1 targetStates:(id)arg2 region:(id)arg3 data:(id)arg4;
- (void)enter:(id)arg1 targetState:(id)arg2 data:(id)arg3;
- (void)switchState:(id)arg1 targetStates:(id)arg2 region:(id)arg3 action:(CDUnknownBlockType)arg4 data:(id)arg5;
- (void)switchState:(id)arg1 targetState:(id)arg2 action:(CDUnknownBlockType)arg3 data:(id)arg4;
- (_Bool)handleEvent:(id)arg1;
- (void)scheduleEvent:(id)arg1;
- (void)tearDown:(id)arg1;
- (void)setUp:(id)arg1;
- (void)setStates:(id)arg1;
- (id)states;
- (id)initWithName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

