//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSString, TBSMState;

@protocol TBSMNode <NSObject>
- (void)exit:(TBSMState *)arg1 targetState:(TBSMState *)arg2 data:(NSDictionary *)arg3;
- (void)enter:(TBSMState *)arg1 targetState:(TBSMState *)arg2 data:(NSDictionary *)arg3;
- (void)setParentNode:(id <TBSMNode>)arg1;
- (id <TBSMNode>)parentNode;
- (NSMutableArray *)path;
- (NSString *)name;
@end

