//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSMState.h"

#import "TBSMContainingNode.h"

@class NSMutableArray, NSString;

@interface TBSMParallelState : TBSMState <TBSMContainingNode>
{
    id <TBSMNode> _parentNode;
    NSMutableArray *_priv_parallelStateMachines;
}

+ (id)parallelStateWithName:(id)arg1;
@property(retain, nonatomic) NSMutableArray *priv_parallelStateMachines; // @synthesize priv_parallelStateMachines=_priv_parallelStateMachines;
- (void)setParentNode:(id)arg1;
- (id)parentNode;
- (void).cxx_destruct;
- (_Bool)handleEvent:(id)arg1;
- (void)exit:(id)arg1 targetState:(id)arg2 data:(id)arg3;
- (void)enter:(id)arg1 targetStates:(id)arg2 region:(id)arg3 data:(id)arg4;
- (void)enter:(id)arg1 targetState:(id)arg2 data:(id)arg3;
- (void)setStateMachines:(id)arg1;
- (id)stateMachines;
- (id)initWithName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

