//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSMPseudoState.h"

@class NSArray, TBSMParallelState;

@interface TBSMFork : TBSMPseudoState
{
    TBSMParallelState *_region;
    NSArray *_priv_targetStates;
}

+ (id)forkWithName:(id)arg1;
@property(retain, nonatomic) NSArray *priv_targetStates; // @synthesize priv_targetStates=_priv_targetStates;
@property(readonly, nonatomic) TBSMParallelState *region; // @synthesize region=_region;
- (void).cxx_destruct;
- (void)setTargetStates:(id)arg1 inRegion:(id)arg2;
- (id)targetStates;
- (id)targetState;

@end

