//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSMPseudoState.h"

@class NSMutableArray;

@interface TBSMJunction : TBSMPseudoState
{
    NSMutableArray *_outgoingPaths;
}

+ (id)junctionWithName:(id)arg1;
@property(retain, nonatomic) NSMutableArray *outgoingPaths; // @synthesize outgoingPaths=_outgoingPaths;
- (void).cxx_destruct;
- (id)outgoingPathForTransition:(id)arg1 data:(id)arg2;
- (void)addOutgoingPathWithTarget:(id)arg1 action:(CDUnknownBlockType)arg2 guard:(CDUnknownBlockType)arg3;
- (id)targetStates;
- (id)initWithName:(id)arg1;

@end

