//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSMState.h"

#import "TBSMContainingNode.h"

@class NSString, TBSMStateMachine;

@interface TBSMSubState : TBSMState <TBSMContainingNode>
{
    TBSMStateMachine *_stateMachine;
}

+ (id)subStateWithName:(id)arg1;
@property(retain, nonatomic) TBSMStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
- (void).cxx_destruct;
- (_Bool)handleEvent:(id)arg1;
- (void)exit:(id)arg1 targetState:(id)arg2 data:(id)arg3;
- (void)enter:(id)arg1 targetStates:(id)arg2 region:(id)arg3 data:(id)arg4;
- (void)enter:(id)arg1 targetState:(id)arg2 data:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

