//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSMPseudoState.h"

@class NSArray, NSMutableSet, TBSMParallelState, TBSMState;

@interface TBSMJoin : TBSMPseudoState
{
    TBSMParallelState *_region;
    NSArray *_priv_sourceStates;
    NSMutableSet *_joinedSourceStates;
    TBSMState *_target;
}

+ (id)joinWithName:(id)arg1;
@property(retain, nonatomic) TBSMState *target; // @synthesize target=_target;
@property(retain, nonatomic) NSMutableSet *joinedSourceStates; // @synthesize joinedSourceStates=_joinedSourceStates;
@property(retain, nonatomic) NSArray *priv_sourceStates; // @synthesize priv_sourceStates=_priv_sourceStates;
@property(readonly, nonatomic) TBSMParallelState *region; // @synthesize region=_region;
- (void).cxx_destruct;
- (_Bool)joinSourceState:(id)arg1;
- (void)setSourceStates:(id)arg1 inRegion:(id)arg2 target:(id)arg3;
- (id)sourceStates;
- (id)targetState;
- (id)initWithName:(id)arg1;

@end

