//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSMNode.h"

@class NSArray, NSDictionary, TBSMEvent, TBSMParallelState, TBSMState;

@protocol TBSMContainingNode <TBSMNode>
- (_Bool)handleEvent:(TBSMEvent *)arg1;
- (void)enter:(TBSMState *)arg1 targetStates:(NSArray *)arg2 region:(TBSMParallelState *)arg3 data:(NSDictionary *)arg4;
@end

