//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertView.h"

@interface UIAlertView (Beme)
+ (id)alertViewWithHTTPErrorCode:(long long)arg1 defaultTitle:(id)arg2 defaultMessage:(id)arg3 errorCodeTitleMap:(id)arg4 errorCodeMessageMap:(id)arg5 cancelButtonTitle:(id)arg6;
@end

