//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (Beme)
+ (id)beme_buttonDisabledDark;
+ (id)beme_buttonHighlightedDark;
+ (id)beme_buttonNormalDark;
+ (id)beme_buttonDisabledLight;
+ (id)beme_buttonHighlightedLight;
+ (id)beme_greenColor;
+ (id)beme_blueColor;
+ (id)beme_dark_redColor;
+ (id)beme_redColor;
+ (id)beme_progressColor;
+ (id)beme_darkGray;
+ (id)beme_lightGray;
+ (id)beme_darkerBackgroundColor;
+ (id)beme_RGB929292Color;
+ (id)beme_RGB70greycolor;
+ (id)beme_RGB878787Color;
+ (id)beme_RGB646464Color;
+ (id)beme_RGB454545Color;
+ (id)beme_RGB10GreyColor;
+ (id)beme_RGB363636Color;
+ (id)beme_RGB222222Color;
+ (id)beme_RGB202020Color;
+ (id)beme_darkBackgroundColor;
+ (id)beme_backgroundColor;
@end

