//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (Beme)
+ (id)beme_akkuratMonoFontWithSize:(double)arg1;
+ (id)beme_akkuratLightFontWithSize:(double)arg1;
+ (id)beme_loadAndReturnFont:(id)arg1 fontFileName:(id)arg2 extension:(id)arg3 size:(double)arg4 onceToken:(long long *)arg5;
@end

