//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Additions)
+ (id)add_resizableImageWithGradient:(id)arg1 size:(struct CGSize)arg2 direction:(int)arg3;
+ (id)add_imageWithGradient:(id)arg1 size:(struct CGSize)arg2 direction:(int)arg3;
+ (id)add_imageWithColor:(id)arg1 size:(struct CGSize)arg2 cornerInset:(struct __ADDCornerInset)arg3 saveInCache:(_Bool)arg4;
+ (id)add_keyForImageWithDescriptors:(id)arg1;
+ (void)add_cacheImage:(id)arg1 withDescriptors:(id)arg2;
+ (id)add_cachedImageWithDescriptors:(id)arg1;
+ (id)add_cache;
+ (id)add_imageNamed:(id)arg1 tintColor:(id)arg2 style:(int)arg3;
+ (id)add_clearColorImage;
+ (id)add_brownColorImage;
+ (id)add_purpleColorImage;
+ (id)add_orangeColorImage;
+ (id)add_magentaColorImage;
+ (id)add_yellowColorImage;
+ (id)add_cyanColorImage;
+ (id)add_blueColorImage;
+ (id)add_greenColorImage;
+ (id)add_redColorImage;
+ (id)add_grayColorImage;
+ (id)add_whiteColorImage;
+ (id)add_lightGrayColorImage;
+ (id)add_darkGrayColorImage;
+ (id)add_blackColorImage;
+ (id)add_resizableImageWithColor:(id)arg1 cornerInset:(struct __ADDCornerInset)arg2;
+ (id)add_resizableImageWithColor:(id)arg1 cornerRadius:(double)arg2;
+ (id)add_resizableImageWithColor:(id)arg1;
+ (id)add_imageWithColor:(id)arg1 size:(struct CGSize)arg2 cornerInset:(struct __ADDCornerInset)arg3;
+ (id)add_imageWithColor:(id)arg1 size:(struct CGSize)arg2 cornerRadius:(double)arg3;
+ (id)add_imageWithColor:(id)arg1 size:(struct CGSize)arg2;
+ (id)add_imageWithColor:(id)arg1;
- (id)add_imageByFixingOrientation;
- (struct CGAffineTransform)add_transformForOrientation:(struct CGSize)arg1;
- (id)add_resizedImage:(struct CGSize)arg1 transform:(struct CGAffineTransform)arg2 drawTransposed:(_Bool)arg3 interpolationQuality:(int)arg4;
- (id)add_imageWithSize:(struct CGSize)arg1 interpolationQuality:(int)arg2;
- (id)add_imageAddingImage:(id)arg1 offset:(struct CGPoint)arg2;
- (id)add_imageAddingImage:(id)arg1;
- (_Bool)add_isValidCornerInset:(struct __ADDCornerInset)arg1;
- (id)add_imageWithCornerInset:(struct __ADDCornerInset)arg1;
- (id)add_imageWithCornerRadius:(double)arg1;
- (id)add_imageWithRoundedBounds;
- (id)add_tintedImageWithColor:(id)arg1 style:(int)arg2;
@end

