//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImagePickerController.h"

@interface UIImagePickerController (BlocksKit)
+ (void)load;

// Remaining properties
@property(copy, nonatomic) CDUnknownBlockType bk_didCancelBlock; // @dynamic bk_didCancelBlock;
@property(copy, nonatomic) CDUnknownBlockType bk_didFinishPickingMediaBlock; // @dynamic bk_didFinishPickingMediaBlock;
@end

