//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPopoverController.h"

@interface UIPopoverController (BlocksKit)
+ (void)load;

// Remaining properties
@property(copy, nonatomic, setter=bk_setDidDismissBlock:) CDUnknownBlockType bk_didDismissBlock; // @dynamic bk_didDismissBlock;
@property(copy, nonatomic, setter=bk_setShouldDismissBlock:) CDUnknownBlockType bk_shouldDismissBlock; // @dynamic bk_shouldDismissBlock;
@end

