//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@interface UITextField (Beme)
+ (_Bool)beme_isValidAccessCodeCharacter:(id)arg1;
+ (_Bool)beme_isValidMobileNumberCharacter:(id)arg1;
+ (_Bool)beme_isValidUserNameCharacter:(id)arg1;
+ (_Bool)beme_isValidUserNameCharacters:(id)arg1;
- (_Bool)beme_validateAccessCode;
- (_Bool)beme_validateMobileNumber;
- (_Bool)beme_validateUserName;
@end

