//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@interface UITextField (BeMe)
+ (_Bool)isValidAccessCodeCharacter:(id)arg1;
+ (_Bool)isValidMobileNumberCharacter:(id)arg1;
+ (_Bool)isValidUserNameCharacter:(id)arg1;
+ (_Bool)isValidUserNameCharacters:(id)arg1;
- (_Bool)validateAcccessCode;
- (_Bool)validateMobileNumber;
- (_Bool)validateUserName;
@end

