//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@interface UITextField (BlocksKit)
+ (void)load;

// Remaining properties
@property(copy, nonatomic) CDUnknownBlockType bk_didBeginEditingBlock; // @dynamic bk_didBeginEditingBlock;
@property(copy, nonatomic) CDUnknownBlockType bk_didEndEditingBlock; // @dynamic bk_didEndEditingBlock;
@property(copy, nonatomic) CDUnknownBlockType bk_shouldBeginEditingBlock; // @dynamic bk_shouldBeginEditingBlock;
@property(copy, nonatomic) CDUnknownBlockType bk_shouldChangeCharactersInRangeWithReplacementStringBlock; // @dynamic bk_shouldChangeCharactersInRangeWithReplacementStringBlock;
@property(copy, nonatomic) CDUnknownBlockType bk_shouldClearBlock; // @dynamic bk_shouldClearBlock;
@property(copy, nonatomic) CDUnknownBlockType bk_shouldEndEditingBlock; // @dynamic bk_shouldEndEditingBlock;
@property(copy, nonatomic) CDUnknownBlockType bk_shouldReturnBlock; // @dynamic bk_shouldReturnBlock;
@end

