//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Beme)
@property(nonatomic) double height;
@property(nonatomic) double width;
@property(nonatomic) double y;
@property(nonatomic) double x;
- (void)beme_setFrameAtCenterLeft;
- (void)beme_resizeToFitSubviews;
- (id)beme_parentViewController;
@end

