//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (PromiseKit)
- (void)reject:(id)arg1;
- (void)fulfill:(id)arg1;
- (void)PromiseKitUIKit_prepareForSegue:(id)arg1 sender:(id)arg2;
- (id)promiseSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (id)promiseViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
@end

