//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@interface UIWebView (BlocksKit)
+ (void)load;

// Remaining properties
@property(copy, nonatomic, setter=bk_setDidFinishLoadBlock:) CDUnknownBlockType bk_didFinishLoadBlock; // @dynamic bk_didFinishLoadBlock;
@property(copy, nonatomic, setter=bk_setDidFinishWithErrorBlock:) CDUnknownBlockType bk_didFinishWithErrorBlock; // @dynamic bk_didFinishWithErrorBlock;
@property(copy, nonatomic, setter=bk_setDidStartLoadBlock:) CDUnknownBlockType bk_didStartLoadBlock; // @dynamic bk_didStartLoadBlock;
@property(copy, nonatomic, setter=bk_setShouldStartLoadBlock:) CDUnknownBlockType bk_shouldStartLoadBlock; // @dynamic bk_shouldStartLoadBlock;
@end

